<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 3 - Introdução à estatística descritiva | _main.knit</title>
  <meta name="description" content="Apostila com alguns tópicos de estatística e probabilidade." />
  <meta name="generator" content="bookdown 0.30 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 3 - Introdução à estatística descritiva | _main.knit" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="https://fjrcosta.github.io/apostila/images/logo-uel.png" />
  <meta property="og:description" content="Apostila com alguns tópicos de estatística e probabilidade." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 3 - Introdução à estatística descritiva | _main.knit" />
  
  <meta name="twitter:description" content="Apostila com alguns tópicos de estatística e probabilidade." />
  <meta name="twitter:image" content="https://fjrcosta.github.io/apostila/images/logo-uel.png" />




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="conceitos_gerais.html"/>
<link rel="next" href="probabilidade.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Índice</a></li>

<li class="divider"></li>
<li><a href="index.html#section" id="toc-section"></a></li>
<li class="chapter" data-level="1" data-path="historia.html"><a href="historia.html"><i class="fa fa-check"></i><b>1</b> - Introdução histórica da estatística</a>
<ul>
<li class="chapter" data-level="1.1" data-path="historia.html"><a href="historia.html#primeiros-levantamentos-estudos-e-publicações-demografia-e-aritmética-política"><i class="fa fa-check"></i><b>1.1</b> Primeiros levantamentos, estudos e publicações &amp; Demografia e aritmética política</a></li>
<li class="chapter" data-level="1.2" data-path="historia.html"><a href="historia.html#visualização-de-dados-estudos-e-primeiras-publicações"><i class="fa fa-check"></i><b>1.2</b> Visualização de dados &amp; Estudos e primeiras publicações</a></li>
<li class="chapter" data-level="1.3" data-path="historia.html"><a href="historia.html#nomes-notáveis"><i class="fa fa-check"></i><b>1.3</b> Nomes notáveis</a></li>
<li class="chapter" data-level="1.4" data-path="historia.html"><a href="historia.html#revista-biometrika"><i class="fa fa-check"></i><b>1.4</b> Revista Biometrika</a></li>
<li class="chapter" data-level="1.5" data-path="historia.html"><a href="historia.html#eugenia"><i class="fa fa-check"></i><b>1.5</b> Eugenia</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="conceitos_gerais.html"><a href="conceitos_gerais.html"><i class="fa fa-check"></i><b>2</b> - Introdução conceitual essencial</a>
<ul>
<li class="chapter" data-level="2.1" data-path="conceitos_gerais.html"><a href="conceitos_gerais.html#estatística-descritiva"><i class="fa fa-check"></i><b>2.1</b> Estatística descritiva</a></li>
<li class="chapter" data-level="2.2" data-path="conceitos_gerais.html"><a href="conceitos_gerais.html#estatística-inferencial"><i class="fa fa-check"></i><b>2.2</b> Estatística inferencial</a></li>
<li class="chapter" data-level="2.3" data-path="conceitos_gerais.html"><a href="conceitos_gerais.html#produção-de-conhecimento"><i class="fa fa-check"></i><b>2.3</b> Produção de conhecimento</a></li>
<li class="chapter" data-level="2.4" data-path="conceitos_gerais.html"><a href="conceitos_gerais.html#população-universo-amostra"><i class="fa fa-check"></i><b>2.4</b> População (universo) &amp; amostra</a></li>
<li class="chapter" data-level="2.5" data-path="conceitos_gerais.html"><a href="conceitos_gerais.html#parâmetros-e-estatísticas"><i class="fa fa-check"></i><b>2.5</b> Parâmetros e estatísticas</a></li>
<li class="chapter" data-level="2.6" data-path="conceitos_gerais.html"><a href="conceitos_gerais.html#tipos-de-variáveis"><i class="fa fa-check"></i><b>2.6</b> Tipos de variáveis</a></li>
<li class="chapter" data-level="2.7" data-path="conceitos_gerais.html"><a href="conceitos_gerais.html#noções-básicas-sobre-somatórios-sigma"><i class="fa fa-check"></i><b>2.7</b> Noções básicas sobre somatórios (<span class="math inline">\(\Sigma\)</span>)}</a></li>
<li class="chapter" data-level="2.8" data-path="conceitos_gerais.html"><a href="conceitos_gerais.html#noções-básicas-para-o-uso-de-calculadora-cassio-fx-82ms"><i class="fa fa-check"></i><b>2.8</b> Noções básicas para o uso de calculadora (Cassio fx-82MS)</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="descritiva.html"><a href="descritiva.html"><i class="fa fa-check"></i><b>3</b> - Introdução à estatística descritiva</a>
<ul>
<li class="chapter" data-level="3.1" data-path="descritiva.html"><a href="descritiva.html#análise-exploratória"><i class="fa fa-check"></i><b>3.1</b> Análise exploratória</a></li>
<li class="chapter" data-level="3.2" data-path="descritiva.html"><a href="descritiva.html#dados-brutos-em-rol-diagrama-de-ramos-folhas-e-de-dispersão-unidimensional"><i class="fa fa-check"></i><b>3.2</b> Dados brutos, em rol, diagrama de ramos &amp; folhas e de dispersão unidimensional</a></li>
<li class="chapter" data-level="3.3" data-path="descritiva.html"><a href="descritiva.html#sínteses-numéricas-descritivas"><i class="fa fa-check"></i><b>3.3</b> Sínteses numéricas descritivas</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="descritiva.html"><a href="descritiva.html#medidas-de-tendência-central-posição"><i class="fa fa-check"></i><b>3.3.1</b> Medidas de tendência central (posição)</a></li>
<li class="chapter" data-level="3.3.2" data-path="descritiva.html"><a href="descritiva.html#medidas-de-dispersão-variabilidade"><i class="fa fa-check"></i><b>3.3.2</b> Medidas de dispersão (variabilidade)</a></li>
<li class="chapter" data-level="3.3.3" data-path="descritiva.html"><a href="descritiva.html#medidas-de-subdivisão-separatrizes"><i class="fa fa-check"></i><b>3.3.3</b> Medidas de subdivisão (separatrizes)</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="descritiva.html"><a href="descritiva.html#medidas-de-forma-assimetria-curtose"><i class="fa fa-check"></i><b>3.4</b> Medidas de forma (assimetria &amp; curtose)</a></li>
<li class="chapter" data-level="3.5" data-path="descritiva.html"><a href="descritiva.html#apresentação-gráfica-de-dados"><i class="fa fa-check"></i><b>3.5</b> Apresentação gráfica de dados</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="descritiva.html"><a href="descritiva.html#barras"><i class="fa fa-check"></i><b>3.5.1</b> Barras</a></li>
<li class="chapter" data-level="3.5.2" data-path="descritiva.html"><a href="descritiva.html#setores"><i class="fa fa-check"></i><b>3.5.2</b> Setores</a></li>
<li class="chapter" data-level="3.5.3" data-path="descritiva.html"><a href="descritiva.html#box-plot"><i class="fa fa-check"></i><b>3.5.3</b> Box-plot</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="descritiva.html"><a href="descritiva.html#apresentação-tabular-de-dados-quantitativos"><i class="fa fa-check"></i><b>3.6</b> Apresentação tabular de dados quantitativos</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="descritiva.html"><a href="descritiva.html#média-1"><i class="fa fa-check"></i><b>3.6.1</b> Média</a></li>
<li class="chapter" data-level="3.6.2" data-path="descritiva.html"><a href="descritiva.html#moda-1"><i class="fa fa-check"></i><b>3.6.2</b> Moda</a></li>
<li class="chapter" data-level="3.6.3" data-path="descritiva.html"><a href="descritiva.html#variância"><i class="fa fa-check"></i><b>3.6.3</b> Variância</a></li>
<li class="chapter" data-level="3.6.4" data-path="descritiva.html"><a href="descritiva.html#histograma"><i class="fa fa-check"></i><b>3.6.4</b> Histograma</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="descritiva.html"><a href="descritiva.html#apresentação-tabular-de-dados-qualitativos"><i class="fa fa-check"></i><b>3.7</b> Apresentação tabular de dados qualitativos</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="probabilidade.html"><a href="probabilidade.html"><i class="fa fa-check"></i><b>4</b> - Introdução ao cálculo de probabilidades</a>
<ul>
<li class="chapter" data-level="4.1" data-path="probabilidade.html"><a href="probabilidade.html#introdução-conceitual-essencial"><i class="fa fa-check"></i><b>4.1</b> Introdução conceitual essencial</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="probabilidade.html"><a href="probabilidade.html#experimentos-determinísticos-e-experimentos-probabilísticos-aleatórios"><i class="fa fa-check"></i><b>4.1.1</b> Experimentos determinísticos e experimentos probabilísticos (aleatórios)</a></li>
<li class="chapter" data-level="4.1.2" data-path="probabilidade.html"><a href="probabilidade.html#espaço-amostral-e-seus-elementos"><i class="fa fa-check"></i><b>4.1.2</b> Espaço amostral e seus elementos</a></li>
<li class="chapter" data-level="4.1.3" data-path="probabilidade.html"><a href="probabilidade.html#evento-de-interesse-sucesso"><i class="fa fa-check"></i><b>4.1.3</b> Evento de interesse (sucesso)</a></li>
<li class="chapter" data-level="4.1.4" data-path="probabilidade.html"><a href="probabilidade.html#evento"><i class="fa fa-check"></i><b>4.1.4</b> Evento</a></li>
<li class="chapter" data-level="4.1.5" data-path="probabilidade.html"><a href="probabilidade.html#operações-com-conjuntos-diagramas-de-venn"><i class="fa fa-check"></i><b>4.1.5</b> Operações com conjuntos &amp; Diagramas de Venn</a></li>
<li class="chapter" data-level="4.1.6" data-path="probabilidade.html"><a href="probabilidade.html#eventos-equiprováveis-e-não-equiprováveis"><i class="fa fa-check"></i><b>4.1.6</b> Eventos equiprováveis e não equiprováveis</a></li>
<li class="chapter" data-level="4.1.7" data-path="probabilidade.html"><a href="probabilidade.html#eventos-independentes"><i class="fa fa-check"></i><b>4.1.7</b> Eventos independentes</a></li>
<li class="chapter" data-level="4.1.8" data-path="probabilidade.html"><a href="probabilidade.html#eventos-mutuamente-exclusivos"><i class="fa fa-check"></i><b>4.1.8</b> Eventos mutuamente exclusivos</a></li>
<li class="chapter" data-level="4.1.9" data-path="probabilidade.html"><a href="probabilidade.html#eventos-complementares"><i class="fa fa-check"></i><b>4.1.9</b> Eventos complementares</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="probabilidade.html"><a href="probabilidade.html#probabilidade-1"><i class="fa fa-check"></i><b>4.2</b> Probabilidade</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="probabilidade.html"><a href="probabilidade.html#introdução-histórica"><i class="fa fa-check"></i><b>4.2.1</b> Introdução histórica</a></li>
<li class="chapter" data-level="4.2.2" data-path="probabilidade.html"><a href="probabilidade.html#conceito-clássico-ou-a-priori"><i class="fa fa-check"></i><b>4.2.2</b> Conceito clássico ou <em>a priori</em></a></li>
<li class="chapter" data-level="4.2.3" data-path="probabilidade.html"><a href="probabilidade.html#conceito-frequentista-ou-a-posteriori"><i class="fa fa-check"></i><b>4.2.3</b> Conceito frequentista ou <em>a posteriori</em></a></li>
<li class="chapter" data-level="4.2.4" data-path="probabilidade.html"><a href="probabilidade.html#conceito-axiomático"><i class="fa fa-check"></i><b>4.2.4</b> Conceito axiomático</a></li>
<li class="chapter" data-level="4.2.5" data-path="probabilidade.html"><a href="probabilidade.html#regra-geral-da-adição-de-probabilidades-de-eventos"><i class="fa fa-check"></i><b>4.2.5</b> Regra geral da adição de probabilidades de eventos</a></li>
<li class="chapter" data-level="4.2.6" data-path="probabilidade.html"><a href="probabilidade.html#probabilidade-de-eventos-condicionados"><i class="fa fa-check"></i><b>4.2.6</b> Probabilidade de eventos condicionados</a></li>
<li class="chapter" data-level="4.2.7" data-path="probabilidade.html"><a href="probabilidade.html#dependência-independência-de-eventos"><i class="fa fa-check"></i><b>4.2.7</b> Dependência &amp; independência de eventos</a></li>
<li class="chapter" data-level="4.2.8" data-path="probabilidade.html"><a href="probabilidade.html#regra-geral-do-produto-das-probabilidades-para-eventos-independentes"><i class="fa fa-check"></i><b>4.2.8</b> Regra geral do produto das probabilidades para eventos independentes</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="probabilidade.html"><a href="probabilidade.html#teorema-de-bayes"><i class="fa fa-check"></i><b>4.3</b> Teorema de Bayes</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="var_aleatoria.html"><a href="var_aleatoria.html"><i class="fa fa-check"></i><b>5</b> - Introdução a variáveis aleatórias</a></li>
<li class="chapter" data-level="6" data-path="modelos_probabilidade.html"><a href="modelos_probabilidade.html"><i class="fa fa-check"></i><b>6</b> - Introdução a modelos teóricos de probabilidade</a></li>
<li class="chapter" data-level="7" data-path="planejamento_pesquisas.html"><a href="planejamento_pesquisas.html"><i class="fa fa-check"></i><b>7</b> - Introdução ao planejamento de pesquisas</a></li>
<li class="chapter" data-level="8" data-path="estatistica_epidemiologia.html"><a href="estatistica_epidemiologia.html"><i class="fa fa-check"></i><b>8</b> - Introdução à estatística na epidemiologia</a></li>
<li class="chapter" data-level="9" data-path="dist_medias_amostrais.html"><a href="dist_medias_amostrais.html"><i class="fa fa-check"></i><b>9</b> - Introdução à distribuição das médias amostrais, suas diferenças e seus intervalos de confiança</a></li>
<li class="chapter" data-level="10" data-path="dist_prop_amostrais.html"><a href="dist_prop_amostrais.html"><i class="fa fa-check"></i><b>10</b> - Introdução à distribuição das proporções amostrais, suas diferenças e seus intervalos de confiança</a></li>
<li class="chapter" data-level="11" data-path="teste_hipoteses.html"><a href="teste_hipoteses.html"><i class="fa fa-check"></i><b>11</b> - Introdução a testes de hipóteses</a></li>
<li class="chapter" data-level="12" data-path="reg_simples.html"><a href="reg_simples.html"><i class="fa fa-check"></i><b>12</b> - Introdução ao modelo clássico de regressão linear simples</a></li>
<li class="chapter" data-level="13" data-path="disc_fisher.html"><a href="disc_fisher.html"><i class="fa fa-check"></i><b>13</b> - Introdução à análise multivariada: discriminante linear de Fisher</a></li>
<li class="chapter" data-level="14" data-path="anova.html"><a href="anova.html"><i class="fa fa-check"></i><b>14</b> - Introdução à estatística experimental: análise de variância (DIC e DBC)</a></li>
<li class="divider"></li>
<li><a href="https://fjrcosta.github.io/apostila/" target="blank">FJCosta Github</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"><div class="line-block">UNIVERSIDADE ESTADUAL DE LONDRINA<br />
CCE - Centro de Ciências Exatas<br />
DSTA - Departamento de Estatística<br />
Apostila de Estatística<br />
Prof. M.e Eng. Felinto Junior Da Costa</div></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="descritiva" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">Capítulo 3</span> - Introdução à estatística descritiva<a href="descritiva.html#descritiva" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Do prefácio da tradução do livro de Jack Levin (Estatística aplicada às ciências humanas), Sérgio Francisco Costa diz que o livro:</p>
<blockquote>
<p>``destina-se a um público muito específico: estudantes de Ciências Humanas, refúgio errôneo dos que fogem das equações e dos cálculos, pois que, embora humanas - e talvez por isso mesmo - não podemos prescindir das tão odiadas quantificações […]’’</p>
</blockquote>
<div id="análise-exploratória" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Análise exploratória<a href="descritiva.html#análise-exploratória" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A análise exploratória de dados ( <em>EDA: Exploratory Data Analisys</em> , originalmente desenvolvida pelo matemático e estatístico norte-americano John Tukey na década de 1970) é usada para se investigar conjuntos de dados e resumir suas principais características, muitas vezes usando métodos de visualização de dados por gráficos e apresentação de tabelas.</p>
<p><br />
</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-28"></span>
<img src="images3/tukey.jpeg" alt="John Tukey (1915-2000)" width="50%" />
<p class="caption">
Figure 3.1: John Tukey (1915-2000)
</p>
</div>
<p><br />
</p>
<p>Habitualmente uma <em>EDA</em> envolve:</p>
<ul>
<li>verificar quais são os tipos de variáveis presentes nos dados;</li>
<li>sintetizar os valores assumidos por cada uma das variáveis;</li>
<li>verificar os padrões de cada variável e eventuais associações entre duas ou mais delas; e,</li>
<li>apresentação de tabelas e gráficos expositivos variados.</li>
</ul>
</div>
<div id="dados-brutos-em-rol-diagrama-de-ramos-folhas-e-de-dispersão-unidimensional" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> Dados brutos, em rol, diagrama de ramos &amp; folhas e de dispersão unidimensional<a href="descritiva.html#dados-brutos-em-rol-diagrama-de-ramos-folhas-e-de-dispersão-unidimensional" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Consideremos os dados obtidos da medição das alturas em metros de 60 estudantes de uma determinada classe de um certo curso aqui na UEL:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="descritiva.html#cb1-1" aria-hidden="true" tabindex="-1"></a>alturas<span class="ot">=</span><span class="fu">c</span>(<span class="fl">1.63</span>,<span class="fl">1.67</span>,<span class="fl">1.47</span>,<span class="fl">1.64</span>,<span class="fl">1.66</span>,<span class="fl">1.73</span>,<span class="fl">2.00</span>,<span class="fl">1.62</span>,<span class="fl">1.65</span>,<span class="fl">1.56</span>,<span class="fl">1.65</span>,<span class="fl">1.85</span>,<span class="fl">1.73</span>,</span>
<span id="cb1-2"><a href="descritiva.html#cb1-2" aria-hidden="true" tabindex="-1"></a>          <span class="fl">1.78</span>,<span class="fl">1.82</span>,<span class="fl">1.68</span>,<span class="fl">1.67</span>,<span class="fl">1.83</span>,<span class="fl">1.72</span>,<span class="fl">1.71</span>,<span class="fl">1.73</span>,<span class="fl">1.67</span>,<span class="fl">1.66</span>,<span class="fl">1.95</span>,<span class="fl">1.76</span>,<span class="fl">1.73</span>,</span>
<span id="cb1-3"><a href="descritiva.html#cb1-3" aria-hidden="true" tabindex="-1"></a>          <span class="fl">1.77</span>,<span class="fl">1.68</span>,<span class="fl">1.65</span>,<span class="fl">1.64</span>,<span class="fl">1.66</span>,<span class="fl">1.68</span>,<span class="fl">1.61</span>,<span class="fl">1.73</span>,<span class="fl">1.72</span>,<span class="fl">1.83</span>,<span class="fl">1.69</span>,<span class="fl">1.84</span>,<span class="fl">1.66</span>,</span>
<span id="cb1-4"><a href="descritiva.html#cb1-4" aria-hidden="true" tabindex="-1"></a>          <span class="fl">1.78</span>,<span class="fl">1.54</span>,<span class="fl">1.74</span>,<span class="fl">1.56</span>,<span class="fl">1.66</span>,<span class="fl">1.56</span>,<span class="fl">1.62</span>,<span class="fl">1.55</span>,<span class="fl">1.86</span>,<span class="fl">1.44</span>,<span class="fl">1.67</span>,<span class="fl">1.76</span>,<span class="fl">1.79</span>,</span>
<span id="cb1-5"><a href="descritiva.html#cb1-5" aria-hidden="true" tabindex="-1"></a>          <span class="fl">1.75</span>,<span class="fl">1.41</span>,<span class="fl">1.65</span>,<span class="fl">1.58</span>,<span class="fl">1.93</span>,<span class="fl">1.57</span>,<span class="fl">1.71</span>,<span class="fl">1.58</span>)</span>
<span id="cb1-6"><a href="descritiva.html#cb1-6" aria-hidden="true" tabindex="-1"></a>alturas</span></code></pre></div>
<pre><code>##  [1] 1.63 1.67 1.47 1.64 1.66 1.73 2.00 1.62 1.65 1.56 1.65 1.85 1.73 1.78 1.82
## [16] 1.68 1.67 1.83 1.72 1.71 1.73 1.67 1.66 1.95 1.76 1.73 1.77 1.68 1.65 1.64
## [31] 1.66 1.68 1.61 1.73 1.72 1.83 1.69 1.84 1.66 1.78 1.54 1.74 1.56 1.66 1.56
## [46] 1.62 1.55 1.86 1.44 1.67 1.76 1.79 1.75 1.41 1.65 1.58 1.93 1.57 1.71 1.58</code></pre>
<p>Esse conjunto de dados certamente contém diversas informações acerca da altura dessas pessoas; todavia, da maneira como estão expostos, a visualização dessas informações fica bastante difícil. Esse modo de apresentação é chamado de dados <em>brutos</em>.</p>
<p>Com um pequeno refinamento, como pela simples ordenação desses dados (são medidas numéricas contínuas), algumas informações começam a se destacar:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="descritiva.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(alturas)</span></code></pre></div>
<pre><code>##  [1] 1.41 1.44 1.47 1.54 1.55 1.56 1.56 1.56 1.57 1.58 1.58 1.61 1.62 1.62 1.63
## [16] 1.64 1.64 1.65 1.65 1.65 1.65 1.66 1.66 1.66 1.66 1.66 1.67 1.67 1.67 1.67
## [31] 1.68 1.68 1.68 1.69 1.71 1.71 1.72 1.72 1.73 1.73 1.73 1.73 1.73 1.74 1.75
## [46] 1.76 1.76 1.77 1.78 1.78 1.79 1.82 1.83 1.83 1.84 1.85 1.86 1.93 1.95 2.00</code></pre>
<p>A interpretabilidade das informações trazidas por esses dados começa a ficar mais fácil como, por exemplo, as alturas:</p>
<ul>
<li>mínima; e,</li>
<li>máxima dos estudantes.</li>
</ul>
<p>A uma listagem de valores ordenada (de modo crescente ou decrescente) dá-se o nome de <em>rol</em>.</p>
<p>Outra forma de apresentação desses dados é por um <em>Diagrama de Ramos e Folhas</em>, uma apresentação híbrida pois ao mesmo tempo que espelha a quantidade de medidas observadas para cada altura, mantém as informações da listagem.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="descritiva.html#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stem</span>(alturas)</span></code></pre></div>
<pre><code>## 
##   The decimal point is 1 digit(s) to the left of the |
## 
##   14 | 147
##   15 | 45666788
##   16 | 12234455556666677778889
##   17 | 11223333345667889
##   18 | 233456
##   19 | 35
##   20 | 0</code></pre>
<p>À esquerda do traço vertical (os ramos) são apresentadas frações das medidas das alturas (no caso, decímetros) e à direita (as folhas) são apresentadas os complementos dessas medidas (os centímetros) de tal modo que cada um dos dados da amostral original possa ter sua medida resgatada fazendo-se a leitura dos valores à esquerda com cada um deles à direita.</p>
<p>Essa apresentação também oferece uma apreciação visual a respeito de como os valores se distribuem.</p>
<p>Um <em>Gráfico de dispersão unidimensional (stripchart)</em> expressa visualmente duas informações: a localização de cada uma das medidas e a dispersão dos dados.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="descritiva.html#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stripchart</span>(alturas, <span class="at">method =</span> <span class="st">&quot;stack&quot;</span>, <span class="at">offset=</span><span class="dv">1</span>,</span>
<span id="cb7-2"><a href="descritiva.html#cb7-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">pch=</span><span class="dv">20</span>, <span class="at">at=</span><span class="fl">0.5</span>,</span>
<span id="cb7-3"><a href="descritiva.html#cb7-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">main=</span><span class="st">&quot;Gráfico de dispersão unidimensional&quot;</span>,</span>
<span id="cb7-4"><a href="descritiva.html#cb7-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">col=</span><span class="st">&quot;blue&quot;</span>,<span class="at">cex=</span><span class="dv">1</span>,</span>
<span id="cb7-5"><a href="descritiva.html#cb7-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">xlab=</span><span class="st">&quot;Alturas dos estudantes (m)&quot;</span>,</span>
<span id="cb7-6"><a href="descritiva.html#cb7-6" aria-hidden="true" tabindex="-1"></a>           <span class="at">ylab=</span><span class="st">&quot;Quantidades observadas (un)&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-32"></span>
<img src="_main_files/figure-html/unnamed-chunk-32-1.png" alt="Gráfico de dispersão unidimensional (stripchart)" width="672" />
<p class="caption">
Figure 3.2: Gráfico de dispersão unidimensional (stripchart)
</p>
</div>
</div>
<div id="sínteses-numéricas-descritivas" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> Sínteses numéricas descritivas<a href="descritiva.html#sínteses-numéricas-descritivas" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Além da apresentação elementar de algumas informações relacionadas aos dados brutos da amostra, tais como os valores <em>mínimo</em> e <em>máximo</em> observados, a estatística descritiva possui muitas outras ferramentas para <em>condensar</em> a informação contida nos dados.</p>
<p>São chamadas de <em>sínteses numéricas</em>, medidas que condensam variados aspectos relacionados aos valores dos dados. As principais <em>sínteses numéricas</em> são:</p>
<ul>
<li>de tendência central (posição): média (simples ou aritmética, geométrica, harmônica, anarmônica, quadrática, biquadrática), moda e mediana;</li>
<li>de dispersão (variabilidade): absolutas (amplitude total, variância e desvio padrão) ou relativas (coeficiente de variação, unidades padronizadas); e,</li>
<li>de subdivisão (separatrizes, quantis): mediana (50%), quartis (25%, 50%, 75%), decis (10%, ….90%) e percentis (1%….99%).</li>
</ul>
<p>Uma medida de posição ou dispersão é dita <strong>resistente</strong> quando forem pouco afetadas pela alteração de uma pequena porção dos dados. A mediana é uma medida resistente, já a média e a variância não são.</p>
<div id="medidas-de-tendência-central-posição" class="section level3 hasAnchor" number="3.3.1">
<h3><span class="header-section-number">3.3.1</span> Medidas de tendência central (posição)<a href="descritiva.html#medidas-de-tendência-central-posição" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="média" class="section level4 hasAnchor" number="3.3.1.1">
<h4><span class="header-section-number">3.3.1.1</span> Média<a href="descritiva.html#média" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Sejam <span class="math inline">\(x_{1}, x_{2}, ..., x_{n}\)</span> os <span class="math inline">\(n\)</span> valores assumidos pela variável <span class="math inline">\(X\)</span> (dados brutos). A <em>média aritmética simples</em> será dada por:</p>
<p><span class="math display">\[
\stackrel{-}{x}=\frac{\sum _{i=1}^{n}{x}_{i}}{n}
\]</span></p>
<p>Propriedades da média aritmética:</p>
<ul>
<li>somando-se (ou subtraindo-se) cada um dos elementos do conjunto de dados por uma constante arbitrária qualquer <span class="math inline">\(k\)</span>, a média aritmética ficará adicionada (ou subtraída) dessa essa constante <span class="math inline">\(k\)</span></li>
</ul>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="descritiva.html#cb8-1" aria-hidden="true" tabindex="-1"></a>alturas_ad<span class="ot">=</span>alturas<span class="fl">+0.05</span></span>
<span id="cb8-2"><a href="descritiva.html#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="descritiva.html#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb8-4"><a href="descritiva.html#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="descritiva.html#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="fu">stripchart</span>(alturas,<span class="at">method =</span> <span class="st">&quot;stack&quot;</span>,  <span class="at">at=</span><span class="fl">0.5</span>, </span>
<span id="cb8-6"><a href="descritiva.html#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="at">main=</span><span class="st">&quot;&quot;</span>,<span class="at">pch =</span> <span class="dv">20</span>,</span>
<span id="cb8-7"><a href="descritiva.html#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="at">col=</span><span class="st">&quot;blue&quot;</span>, <span class="at">cex=</span><span class="dv">1</span>, <span class="at">xlab=</span><span class="st">&quot;Alturas originais dos estudantes (m)&quot;</span>, </span>
<span id="cb8-8"><a href="descritiva.html#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="at">ylab=</span><span class="st">&quot;Quantidades observadas (un)&quot;</span>)</span>
<span id="cb8-9"><a href="descritiva.html#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">mean</span>(alturas), <span class="at">col=</span><span class="st">&quot;red&quot;</span>) </span>
<span id="cb8-10"><a href="descritiva.html#cb8-10" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="fu">mean</span>(alturas)<span class="sc">-</span><span class="fl">0.2</span>, <span class="dv">1</span>, <span class="st">&quot;Média=1,69 m&quot;</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">srt=</span><span class="dv">90</span>) </span>
<span id="cb8-11"><a href="descritiva.html#cb8-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-12"><a href="descritiva.html#cb8-12" aria-hidden="true" tabindex="-1"></a><span class="fu">stripchart</span>(alturas_ad,<span class="at">method =</span> <span class="st">&quot;stack&quot;</span>,  <span class="at">at=</span><span class="fl">0.5</span>, </span>
<span id="cb8-13"><a href="descritiva.html#cb8-13" aria-hidden="true" tabindex="-1"></a><span class="at">main=</span><span class="st">&quot;&quot;</span>,<span class="at">pch =</span> <span class="dv">20</span>,</span>
<span id="cb8-14"><a href="descritiva.html#cb8-14" aria-hidden="true" tabindex="-1"></a><span class="at">col=</span><span class="st">&quot;blue&quot;</span>, <span class="at">cex=</span><span class="dv">1</span>, <span class="at">xlab=</span><span class="st">&quot;Alt. dos estudantes (m) adic. de 5cm&quot;</span>, </span>
<span id="cb8-15"><a href="descritiva.html#cb8-15" aria-hidden="true" tabindex="-1"></a><span class="at">ylab=</span><span class="st">&quot;Quantidades observadas (un)&quot;</span>)</span>
<span id="cb8-16"><a href="descritiva.html#cb8-16" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">mean</span>(alturas_ad), <span class="at">col=</span><span class="st">&quot;red&quot;</span>) </span>
<span id="cb8-17"><a href="descritiva.html#cb8-17" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="fu">mean</span>(alturas_ad)<span class="sc">-</span><span class="fl">0.2</span>, <span class="dv">1</span>, <span class="st">&quot;Média=1,74 m&quot;</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">srt=</span><span class="dv">90</span>) </span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-33"></span>
<img src="_main_files/figure-html/unnamed-chunk-33-1.png" alt="Mudanças na média pela adição (subtração) de uma constante $k=0.05$" width="672" />
<p class="caption">
Figure 3.3: Mudanças na média pela adição (subtração) de uma constante <span class="math inline">\(k=0.05\)</span>
</p>
</div>
<ul>
<li>multiplicando-se (ou dividindo-se) cada um dos elementos do conjunto de dados por uma constante arbitrária <span class="math inline">\(k\)</span>, a média aritmética ficará multiplicada (ou dividida) por essa constante <span class="math inline">\(k\)</span></li>
</ul>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="descritiva.html#cb9-1" aria-hidden="true" tabindex="-1"></a>alturas_mult<span class="ot">=</span>alturas<span class="sc">*</span><span class="fl">1.2</span></span>
<span id="cb9-2"><a href="descritiva.html#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="descritiva.html#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb9-4"><a href="descritiva.html#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="descritiva.html#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="fu">stripchart</span>(alturas,<span class="at">method =</span> <span class="st">&quot;stack&quot;</span>,  <span class="at">at=</span><span class="fl">0.5</span>, </span>
<span id="cb9-6"><a href="descritiva.html#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="at">main=</span><span class="st">&quot;&quot;</span>,<span class="at">pch =</span> <span class="dv">20</span>,</span>
<span id="cb9-7"><a href="descritiva.html#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="at">col=</span><span class="st">&quot;blue&quot;</span>,  <span class="at">xlab=</span><span class="st">&quot;Alturas originais dos estudantes (m)&quot;</span>, </span>
<span id="cb9-8"><a href="descritiva.html#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="at">ylab=</span><span class="st">&quot;Quantidades observadas (un)&quot;</span>)</span>
<span id="cb9-9"><a href="descritiva.html#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">mean</span>(alturas), <span class="at">col=</span><span class="st">&quot;red&quot;</span>) </span>
<span id="cb9-10"><a href="descritiva.html#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="fu">mean</span>(alturas)<span class="sc">-</span><span class="fl">0.1</span>, <span class="dv">1</span>, <span class="st">&quot;Média=1,69 m&quot;</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">srt=</span><span class="dv">90</span>) </span>
<span id="cb9-11"><a href="descritiva.html#cb9-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-12"><a href="descritiva.html#cb9-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-13"><a href="descritiva.html#cb9-13" aria-hidden="true" tabindex="-1"></a><span class="fu">stripchart</span>(alturas_mult,<span class="at">method =</span> <span class="st">&quot;stack&quot;</span>,  <span class="at">at=</span><span class="fl">0.5</span>, </span>
<span id="cb9-14"><a href="descritiva.html#cb9-14" aria-hidden="true" tabindex="-1"></a><span class="at">main=</span><span class="st">&quot;&quot;</span>,<span class="at">pch =</span> <span class="dv">20</span>,</span>
<span id="cb9-15"><a href="descritiva.html#cb9-15" aria-hidden="true" tabindex="-1"></a><span class="at">col=</span><span class="st">&quot;blue&quot;</span>,  <span class="at">xlab=</span><span class="st">&quot;Alt. dos estudantes (m) mult. por 1,2&quot;</span>, </span>
<span id="cb9-16"><a href="descritiva.html#cb9-16" aria-hidden="true" tabindex="-1"></a><span class="at">ylab=</span><span class="st">&quot;Quantidades observadas (un)&quot;</span>)</span>
<span id="cb9-17"><a href="descritiva.html#cb9-17" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">mean</span>(alturas_mult), <span class="at">col=</span><span class="st">&quot;red&quot;</span>) </span>
<span id="cb9-18"><a href="descritiva.html#cb9-18" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="fu">mean</span>(alturas_mult)<span class="sc">-</span><span class="fl">0.1</span>, <span class="dv">1</span>, <span class="st">&quot;Média= 2,02 m&quot;</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">srt=</span><span class="dv">90</span>) </span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-34"></span>
<img src="_main_files/figure-html/unnamed-chunk-34-1.png" alt="Mudanças na média pela multiplicação (divisão) de uma constante $k=1.2$" width="672" />
<p class="caption">
Figure 3.4: Mudanças na média pela multiplicação (divisão) de uma constante <span class="math inline">\(k=1.2\)</span>
</p>
</div>
<ul>
<li>a soma dos desvios observados entre cada um dos valores assumidos pela variável <span class="math inline">\(X\)</span> e sua média <span class="math inline">\(\stackrel{-}{x}\)</span> é nula;</li>
<li>a soma dos quadrados dos desvios é mínima;</li>
<li>em uma distribuição de frequências, a soma dos produtos dos desvios entre a média o valor médio de cada uma das classes, pelas respectivas frequências é nula; e,</li>
<li>multiplicando-se (ou dividindo-se) todas as frequências de uma distribuição por uma constante arbitrária, a média aritmética não se altera.</li>
</ul>
<p>Usando os dados das medidas das alturas dos 60 estudantes teremos o seguinte valor para a <strong>média</strong>:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="descritiva.html#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">mean</span>(alturas),<span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 1.69</code></pre>
</div>
<div id="moda" class="section level4 hasAnchor" number="3.3.1.2">
<h4><span class="header-section-number">3.3.1.2</span> Moda<a href="descritiva.html#moda" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Moda é o valor que ocorre com maior frequência na amostra. Uma amostra pode se apresentar como:
- unimodal;
- bimodal;
- plurimodal; ou,
- amodal.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="descritiva.html#cb12-1" aria-hidden="true" tabindex="-1"></a>tab_alturas<span class="ot">=</span><span class="fu">table</span>(alturas)</span>
<span id="cb12-2"><a href="descritiva.html#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="descritiva.html#cb12-3" aria-hidden="true" tabindex="-1"></a>tab_alturas</span></code></pre></div>
<pre><code>## alturas
## 1.41 1.44 1.47 1.54 1.55 1.56 1.57 1.58 1.61 1.62 1.63 1.64 1.65 1.66 1.67 1.68 
##    1    1    1    1    1    3    1    2    1    2    1    2    4    5    4    3 
## 1.69 1.71 1.72 1.73 1.74 1.75 1.76 1.77 1.78 1.79 1.82 1.83 1.84 1.85 1.86 1.93 
##    1    2    2    5    1    1    2    1    2    1    1    2    1    1    1    1 
## 1.95    2 
##    1    1</code></pre>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="descritiva.html#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(tab_alturas,</span>
<span id="cb14-2"><a href="descritiva.html#cb14-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">main=</span><span class="st">&quot;Valores observados da alturas dos estudantes&quot;</span>,</span>
<span id="cb14-3"><a href="descritiva.html#cb14-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab=</span><span class="st">&quot;Altura (cm)&quot;</span>,</span>
<span id="cb14-4"><a href="descritiva.html#cb14-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab=</span><span class="st">&quot;Quantidade observada (un)&quot;</span>,</span>
<span id="cb14-5"><a href="descritiva.html#cb14-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">6</span>),</span>
<span id="cb14-6"><a href="descritiva.html#cb14-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">col=</span><span class="st">&quot;blue&quot;</span>,</span>
<span id="cb14-7"><a href="descritiva.html#cb14-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">las=</span><span class="dv">0</span>, </span>
<span id="cb14-8"><a href="descritiva.html#cb14-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">hor=</span><span class="st">&quot;FALSE&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-36"></span>
<img src="_main_files/figure-html/unnamed-chunk-36-1.png" alt="Bimodal: 1,66 m e 1,73 m" width="672" />
<p class="caption">
Figure 3.5: Bimodal: 1,66 m e 1,73 m
</p>
</div>
<p>Usando os dados das medidas das alturas dos 60 estudantes teremos os seguintes valores para a <strong>moda</strong>:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="descritiva.html#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># função em R para extrair a moda:</span></span>
<span id="cb15-2"><a href="descritiva.html#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="descritiva.html#cb15-3" aria-hidden="true" tabindex="-1"></a>Modes <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb15-4"><a href="descritiva.html#cb15-4" aria-hidden="true" tabindex="-1"></a>  ux <span class="ot">&lt;-</span> <span class="fu">unique</span>(x)</span>
<span id="cb15-5"><a href="descritiva.html#cb15-5" aria-hidden="true" tabindex="-1"></a>  tab <span class="ot">&lt;-</span> <span class="fu">tabulate</span>(<span class="fu">match</span>(x, ux))</span>
<span id="cb15-6"><a href="descritiva.html#cb15-6" aria-hidden="true" tabindex="-1"></a>  ux[tab <span class="sc">==</span> <span class="fu">max</span>(tab)]</span>
<span id="cb15-7"><a href="descritiva.html#cb15-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb15-8"><a href="descritiva.html#cb15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="descritiva.html#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="fu">Modes</span>(alturas)</span></code></pre></div>
<pre><code>## [1] 1.66 1.73</code></pre>
</div>
<div id="mediana" class="section level4 hasAnchor" number="3.3.1.3">
<h4><span class="header-section-number">3.3.1.3</span> Mediana<a href="descritiva.html#mediana" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Mediana é o valor do <em>i-ésimo</em> dado da amostra que ocupa a posição central na distribuição ordenada de modo crescente (ou decrescente), dividindo-a em duas partes de <em>quantidades de dados iguais</em>.</p>
<p>Sendo uma medida separatriz de 50%, equivale ao <span class="math inline">\(2^{o}\)</span> quartil, ao <span class="math inline">\(5^{o}\)</span> decil e ao <span class="math inline">\(50^{o}\)</span> percentil.</p>
<p>1- amostra com um número <strong>ímpar</strong> (<span class="math inline">\(n\)</span>) de elementos: a mediana será o valor do _i-ésimo} elemento (elemento na posição central) da amostra ordenada:</p>
<p><span class="math display">\[
Md=x_{i}
\]</span></p>
<p>onde:</p>
<ul>
<li><span class="math inline">\(i=\frac{n+1}{2}\)</span> (<span class="math inline">\(n\)</span> é o número de observações);</li>
</ul>
<p>2- amostra com um número <strong>par</strong> (<span class="math inline">\(n\)</span>) de elementos: a mediana será a <em>média aritmética</em> dos elementos nas posições imediatamente anterior (<span class="math inline">\(i_{ant}\)</span>) e posterior (<span class="math inline">\(i_{post}\)</span>) à sua posição central virtual:</p>
<p><span class="math display">\[
Md=média(x_{i_{ant}} ; x_{i_{post}})
\]</span></p>
<p>onde:</p>
<ul>
<li><span class="math inline">\(i_{ant} = \frac{n}{2}\)</span> e <span class="math inline">\(i_{post} =\frac{n}{2}+1\)</span> (<span class="math inline">\(n\)</span> é o número de observações).</li>
</ul>
<p>Mediana para dados apresentados na forma de uma distribuição de frequências:</p>
<p><span class="math display">\[
Md = l_{inf} + [ \frac{(\frac{n}{2} -  F_{(i_{md}-1)})}{n_{md}} ]\times \Delta_{i}
\]</span></p>
<p>onde:</p>
<ul>
<li><span class="math inline">\(l_{inf}\)</span>: limite inferior da <strong>classe mediana</strong>: a classe que contem o elemento de ordem <span class="math inline">\(\frac{n}{2}\)</span>;</li>
<li><span class="math inline">\(F_{(i_{md}-1)}\)</span>: é a frequência absoluta acumulada até a <strong>classe anterior à classe mediana</strong>;</li>
<li><span class="math inline">\(n_{md}\)</span>: é a frequência absoluta da <strong>classe mediana</strong>; e,</li>
<li><span class="math inline">\(\Delta_{i}\)</span>: é o intervalo de cada classe.</li>
</ul>
<p>Usando os dados das medidas das alturas dos 60 estudantes teremos o seguinte valor para a <strong>mediana</strong>:</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="descritiva.html#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(alturas)</span></code></pre></div>
<pre><code>##  [1] 1.41 1.44 1.47 1.54 1.55 1.56 1.56 1.56 1.57 1.58 1.58 1.61 1.62 1.62 1.63
## [16] 1.64 1.64 1.65 1.65 1.65 1.65 1.66 1.66 1.66 1.66 1.66 1.67 1.67 1.67 1.67
## [31] 1.68 1.68 1.68 1.69 1.71 1.71 1.72 1.72 1.73 1.73 1.73 1.73 1.73 1.74 1.75
## [46] 1.76 1.76 1.77 1.78 1.78 1.79 1.82 1.83 1.83 1.84 1.85 1.86 1.93 1.95 2.00</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="descritiva.html#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(alturas)</span></code></pre></div>
<pre><code>## [1] 1.675</code></pre>
</div>
<div id="diferentes-posições-da-média-moda-e-mediana" class="section level4 hasAnchor" number="3.3.1.4">
<h4><span class="header-section-number">3.3.1.4</span> Diferentes posições da média, moda e mediana<a href="descritiva.html#diferentes-posições-da-média-moda-e-mediana" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Essas três medidas podem se apresentar com valores em posições alternadas quando as comparamos:</p>
<ul>
<li><p>quando a moda=mediana=média temos uma distribuição de frequências razoavelmente <strong>simétrica</strong>;</p></li>
<li><p>quando a moda <span class="math inline">\(\leq\)</span> mediana <span class="math inline">\(\leq\)</span> média (há uma quantidade maior de dados com grandes valores, arrastando a média para a direita, para cima) temos uma distribuição de frequências <strong>positivamente assimétrica</strong>, ; e,<br />
</p></li>
<li><p>quando a moda <span class="math inline">\(\geq\)</span> mediana <span class="math inline">\(\geq\)</span> média (há uma quantidade maior de dados com pequenos valores, arrastando a média para a esquerda, para baixo) temos uma distribuição de frequências <strong>negativamente assimétrica</strong>.</p></li>
</ul>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="descritiva.html#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(tab_alturas,</span>
<span id="cb21-2"><a href="descritiva.html#cb21-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">main=</span><span class="st">&quot;Valores observados da alturas dos estudantes&quot;</span>,</span>
<span id="cb21-3"><a href="descritiva.html#cb21-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab=</span><span class="st">&quot;Altura (cm)&quot;</span>,</span>
<span id="cb21-4"><a href="descritiva.html#cb21-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab=</span><span class="st">&quot;Quantidade observada (un)&quot;</span>,</span>
<span id="cb21-5"><a href="descritiva.html#cb21-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">6</span>),</span>
<span id="cb21-6"><a href="descritiva.html#cb21-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">col=</span><span class="st">&quot;blue&quot;</span>,</span>
<span id="cb21-7"><a href="descritiva.html#cb21-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">las=</span><span class="dv">0</span>, </span>
<span id="cb21-8"><a href="descritiva.html#cb21-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">hor=</span><span class="st">&quot;FALSE&quot;</span>)</span>
<span id="cb21-9"><a href="descritiva.html#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">mean</span>(<span class="fl">19.9</span>, <span class="fl">21.1</span>), <span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span>
<span id="cb21-10"><a href="descritiva.html#cb21-10" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>( <span class="fu">mean</span>(<span class="fl">19.9</span>, <span class="fl">21.1</span>)<span class="sc">-</span><span class="fl">0.5</span>, <span class="dv">5</span>, <span class="st">&quot;Média=1,69 m&quot;</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">srt=</span><span class="dv">90</span>)</span>
<span id="cb21-11"><a href="descritiva.html#cb21-11" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">median</span>(<span class="fl">18.7</span> , <span class="fl">19.9</span>), <span class="at">col=</span><span class="st">&quot;darkgreen&quot;</span>) </span>
<span id="cb21-12"><a href="descritiva.html#cb21-12" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="fu">median</span>(<span class="fl">18.7</span> , <span class="fl">19.9</span>)<span class="sc">-</span><span class="fl">0.5</span>, <span class="dv">5</span>, <span class="st">&quot;Mediana=1,675 m&quot;</span>, <span class="at">col =</span> <span class="st">&quot;darkgreen&quot;</span>, <span class="at">srt=</span><span class="dv">90</span>)</span>
<span id="cb21-13"><a href="descritiva.html#cb21-13" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">c</span>(<span class="fl">16.3</span>, <span class="fl">23.5</span>), <span class="at">col=</span><span class="st">&quot;darkgrey&quot;</span>) </span>
<span id="cb21-14"><a href="descritiva.html#cb21-14" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="fu">c</span>(<span class="fl">16.3-0.5</span>, <span class="fl">23.5-0.5</span>), <span class="dv">5</span>, <span class="fu">c</span>(<span class="st">&quot;Moda=1,66&quot;</span>,<span class="st">&quot;Moda=1,73&quot;</span>), <span class="at">col =</span> <span class="st">&quot;darkgray&quot;</span>, <span class="at">srt=</span><span class="dv">90</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-40"></span>
<img src="_main_files/figure-html/unnamed-chunk-40-1.png" alt="Valores observados das alturas dos estudantes e as posições da média, moda e mediana" width="672" />
<p class="caption">
Figure 3.6: Valores observados das alturas dos estudantes e as posições da média, moda e mediana
</p>
</div>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="descritiva.html#cb22-1" aria-hidden="true" tabindex="-1"></a>h1<span class="ot">=</span><span class="fu">hist</span>(alturas, <span class="at">breaks=</span><span class="fu">seq</span>(<span class="fl">1.30</span> , <span class="fl">2.10</span> , <span class="fl">0.1</span>), <span class="at">main=</span> <span class="st">&quot;Histograma das alturas dos estudantes&quot;</span>, <span class="at">col=</span><span class="st">&quot;blue&quot;</span>, </span>
<span id="cb22-2"><a href="descritiva.html#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="at">xlab=</span><span class="st">&quot;Classes de comprimento (cm)&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Frequência absoluta observada (un)&quot;</span> , <span class="at">cex=</span><span class="fl">0.7</span>, <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">30</span>))</span>
<span id="cb22-3"><a href="descritiva.html#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(h1<span class="sc">$</span>mids,h1<span class="sc">$</span>counts,<span class="at">labels=</span>h1<span class="sc">$</span>counts, <span class="at">adj=</span><span class="fu">c</span>(<span class="fl">0.5</span>, <span class="sc">-</span><span class="fl">0.5</span>))</span>
<span id="cb22-4"><a href="descritiva.html#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">mean</span>(alturas), <span class="at">col=</span><span class="st">&quot;red&quot;</span>) </span>
<span id="cb22-5"><a href="descritiva.html#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="fu">mean</span>(alturas)<span class="sc">-</span><span class="fl">0.01</span>, <span class="dv">28</span>, <span class="st">&quot;Média=1,69 m&quot;</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">srt=</span><span class="dv">90</span>)</span>
<span id="cb22-6"><a href="descritiva.html#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">median</span>(alturas), <span class="at">col=</span><span class="st">&quot;darkgreen&quot;</span>) </span>
<span id="cb22-7"><a href="descritiva.html#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="fu">median</span>(alturas)<span class="sc">-</span><span class="fl">0.01</span>, <span class="fl">27.2</span>, <span class="st">&quot;Mediana=1,675 m&quot;</span>, <span class="at">col =</span> <span class="st">&quot;darkgreen&quot;</span>, <span class="at">srt=</span><span class="dv">90</span>)</span>
<span id="cb22-8"><a href="descritiva.html#cb22-8" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">Modes</span>(alturas), <span class="at">col=</span><span class="st">&quot;darkgrey&quot;</span>) </span>
<span id="cb22-9"><a href="descritiva.html#cb22-9" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="fu">Modes</span>(alturas)<span class="sc">+</span><span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.01</span>, <span class="sc">-</span><span class="fl">0.01</span>), <span class="dv">27</span>, <span class="fu">c</span>(<span class="st">&quot;Moda=1,66&quot;</span>,<span class="st">&quot;Moda=1,73&quot;</span>), <span class="at">col =</span> <span class="st">&quot;darkgray&quot;</span>, <span class="at">srt=</span><span class="dv">90</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-41"></span>
<img src="_main_files/figure-html/unnamed-chunk-41-1.png" alt="Histograma das alturas dos estudantes com as posições da média, moda e mediana" width="672" />
<p class="caption">
Figure 3.7: Histograma das alturas dos estudantes com as posições da média, moda e mediana
</p>
</div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-42"></span>
<img src="images3/comp_sinteses.jpg" alt="Quadro comparativo entre as medidas de tendência central (posição)" width="50%" />
<p class="caption">
Figure 3.8: Quadro comparativo entre as medidas de tendência central (posição)
</p>
</div>
</div>
</div>
<div id="medidas-de-dispersão-variabilidade" class="section level3 hasAnchor" number="3.3.2">
<h3><span class="header-section-number">3.3.2</span> Medidas de dispersão (variabilidade)<a href="descritiva.html#medidas-de-dispersão-variabilidade" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>O conhecimento de uma medida de tendência central nos provê uma informação útil mas incompleta. As medidas de dispersão nos ajudam a ter uma perspectiva melhor dos dados.</p>
<ul>
<li>medidas absolutas: são expressas na mesma unidade de medida do fenômeno estudado.
<ul>
<li>amplitude total dos dados: diferença entre o maior e o menor dos valores observados; e,</li>
<li>variância e desvio padrão: é considerada a mais útil das medidas de dispersão.</li>
</ul></li>
</ul>
<p><br />
</p>
<ul>
<li>medidas relativas: usadas para se comparar a variabilidade de duas ou mais distribuições, mesmo quando estas se refiram a diferentes fenômenos ou que sejam expressas em unidades diferentes.
<ul>
<li>coeficiente de variação; e,</li>
<li>unidades padronizadas.</li>
</ul></li>
</ul>
<div id="estimação-da-variância-e-desvio-padrão." class="section level4 hasAnchor" number="3.3.2.1">
<h4><span class="header-section-number">3.3.2.1</span> Estimação da variância (e desvio padrão).<a href="descritiva.html#estimação-da-variância-e-desvio-padrão." class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Sejam <span class="math inline">\(x_{1}, x_{2}, ..., x_{n}\)</span> os <span class="math inline">\(n\)</span> valores assumidos pela variável <span class="math inline">\(X\)</span>. Dá-se o nome de desvios a contar da média as diferenças entre cada uma das observações e a média: <span class="math inline">\(x_{i} - \stackrel{-}{x}\)</span> com <span class="math inline">\(i=1,2,...,n\)</span>.</p>
<p>Não é possível considerar a possibilidade de se adotar o valor médio desses desvios pois uma das propriedades da média é que a soma dos desvios em torno de si é nula.</p>
<p><span class="math display">\[
\stackrel{-}{d} = \frac{\sum _{i=1}^{n}\left(x_{i}-\stackrel{-}{x}\right)}{n}
\]</span>
<span class="math display">\[
\sum _{i=1}^{n}\left(x_{i}-\stackrel{-}{x}\right)=0
\]</span></p>
<p>constitui-se numa restrição linear dos desvios porque qualquer <span class="math inline">\(n-1\)</span> deles completamente determina o outro. Tampouco se considera a possibilidade de se adotar o valor médio desses desvios em módulo, pelas dificuldades teóricas em problemas de inferência.</p>
<p><span class="math display">\[
\stackrel{-}{d}  = \frac{\sum _{i=1}^{n}\left|x_{i}-\stackrel{-}{x}\right|}{n}
\]</span>
Uma alternativa é adotar o valor médio do <strong>quadrado</strong> desses desvios.</p>
<p><span class="math display">\[
S^{2}=\frac{\sum _{i=1}^{n}\left(x_{i}-\stackrel{-}{x}\right)^{2}}{n-1}
\]</span></p>
<p>ou,</p>
<p><span class="math display">\[
S^{2}=\frac{1}{(n-1)} \times \left[ \sum _{i=1}^{n} (x_{i}^{2}) - \frac{({\sum _{i=1}^{n}x_{i})}^{2} }{n}\right]
\]</span></p>
<p>Diz-se que a variância amostral (variância <em>ajustada</em>) possui <span class="math inline">\((n-1)\)</span> graus de liberdade, denotado pela letra grega <span class="math inline">\(\nu\)</span>. A perda de <em>um</em> grau de liberdade deve-se à necessidade de se substituir a média populacional desconhecida (<span class="math inline">\(\mu\)</span>) por sua estimativa amostral (<span class="math inline">\(\stackrel{-}{x}\)</span>), deduzida a partir dos dados coletados.</p>
<p>Pode-se demonstrar que em razão dessa restrição a melhor estimativa para a variância populacional é obtida dividindo-se a soma dos quadrados dos desvios por <span class="math inline">\((n-1)\)</span>. Assim <span class="math inline">\(S^{2}\)</span> será um estimador não tendencioso para a variância amostral ao ser dividido por <span class="math inline">\((n-1)\)</span>}.</p>
<p>Uma medida de dispersão que apresenta a mesma unidade que a das observações originais é o <strong>desvio-padrão</strong>, definido como a raiz quadrada positiva da variância.</p>
<p><span class="math display">\[
S= \sqrt{\frac{\sum _{i=1}^{n}\left(x_{i}-\stackrel{-}{x}\right)^{2}}{n-1}}
\]</span></p>
<p>Tanto a variância quanto o desvio padrão indicam, em média, qual será o erro (desvio) cometido ao tentar substituir cada observação pela medida resumo do conjunto de dados (média).</p>
<p>Usando os dados das medidas das alturas dos 60 estudantes teremos o seguinte valor para a <strong>variância</strong> (com unidade igual a <span class="math inline">\(m^{2}\)</span>) e o <strong>desvio padrão</strong> (com unidade igual a <span class="math inline">\(m\)</span>:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="descritiva.html#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Variãncia</span></span>
<span id="cb23-2"><a href="descritiva.html#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(alturas)</span></code></pre></div>
<pre><code>## [1] 0.0130809</code></pre>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="descritiva.html#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Desvio padrão</span></span>
<span id="cb25-2"><a href="descritiva.html#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(alturas) </span></code></pre></div>
<pre><code>## [1] 0.1143718</code></pre>
<p>Propriedades da variância:</p>
<ul>
<li>somando-se (ou subtraindo-se) cada um dos elementos do conjunto de dados por uma constante arbitrária, a variância (e o desvio padrão) não se altera; e,</li>
<li>multiplicando-se (ou dividindo-se) cada um dos elementos do conjunto de dados por uma constante arbitrária, a variância ficará multiplicada (ou dividida) pelo quadrado dessa constante. O desvio padrão fica multiplicado (ou dividido) por essa constante</li>
</ul>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="descritiva.html#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Adicionando-se uma constante k=0.05</span></span>
<span id="cb27-2"><a href="descritiva.html#cb27-2" aria-hidden="true" tabindex="-1"></a>alturas_ad<span class="ot">=</span>alturas<span class="fl">+0.05</span></span>
<span id="cb27-3"><a href="descritiva.html#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="descritiva.html#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Variância não se altera</span></span>
<span id="cb27-5"><a href="descritiva.html#cb27-5" aria-hidden="true" tabindex="-1"></a>var_ad<span class="ot">=</span> <span class="fu">var</span>(alturas_ad)</span>
<span id="cb27-6"><a href="descritiva.html#cb27-6" aria-hidden="true" tabindex="-1"></a>var_ad</span></code></pre></div>
<pre><code>## [1] 0.0130809</code></pre>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="descritiva.html#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Multiplicando-se uma constante k=1.2</span></span>
<span id="cb29-2"><a href="descritiva.html#cb29-2" aria-hidden="true" tabindex="-1"></a>alturas_mult<span class="ot">=</span>alturas<span class="sc">*</span><span class="fl">1.2</span></span>
<span id="cb29-3"><a href="descritiva.html#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="descritiva.html#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Variância fica multiplicada (dividida) pelo quadrado dessa constante)</span></span>
<span id="cb29-5"><a href="descritiva.html#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(alturas_mult)</span></code></pre></div>
<pre><code>## [1] 0.0188365</code></pre>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="descritiva.html#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">all.equal</span>(<span class="fu">var</span>(alturas_mult), <span class="fu">var</span>(alturas)<span class="sc">*</span>(<span class="fl">1.2</span><span class="sc">^</span><span class="dv">2</span>)) </span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
</div>
<div id="coeficiente-de-variação." class="section level4 hasAnchor" number="3.3.2.2">
<h4><span class="header-section-number">3.3.2.2</span> Coeficiente de variação.<a href="descritiva.html#coeficiente-de-variação." class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>O coeficiente de variação (uma medidad adimensional) é dado pela razão do desvio padrão pela média:</p>
<p><span class="math display">\[
CV= 100\cdot(\frac{s}{\stackrel{-}{x}})
\]</span></p>
</div>
<div id="padronização-z-scores" class="section level4 hasAnchor" number="3.3.2.3">
<h4><span class="header-section-number">3.3.2.3</span> Padronização (<em>z-scores</em>)<a href="descritiva.html#padronização-z-scores" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>À conversão do valor assumido por uma variável em unidades de desvio padrão acima (ou abaixo) do valor médio de sua distribuição é dado o nome de <em>padronização</em>. Essa métrica permite comparações com outras, procedentes de outros fenômenos.</p>
<p>Para padronizar (achar o seu <em>z-score</em> Z) o valor de uma variável procede-se segundo a fórmula:</p>
<p><span class="math display">\[
Z=\frac{x_{i} - \stackrel{-}{x}}{s}
\]</span></p>
<p>O valor <span class="math inline">\(Z\)</span> expressa quantos desvios esse dado está acima (ou abaixo) da média da distribuição.</p>
<p>Pelo <em>Teorema de Tchebichev</em> pode-se estimar a probabilidade mínima dos dados situados a certa distância de <span class="math inline">\(k\)</span> desvios da média dessa distribuição:</p>
<p><span class="math display">\[
P(|X-\mu|\ge k\sigma) \leq 1 - \frac{1}{k^{2}}
\]</span>
Assim, se <span class="math inline">\(k=2\)</span> <strong>ao menos</strong> 75% das observações devem estar entre a média e dois desvios padrões acima ou abaixo da média.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="descritiva.html#cb33-1" aria-hidden="true" tabindex="-1"></a>med<span class="ot">=</span><span class="fu">round</span>(<span class="fu">mean</span>(alturas),<span class="dv">2</span>)</span>
<span id="cb33-2"><a href="descritiva.html#cb33-2" aria-hidden="true" tabindex="-1"></a>desv<span class="ot">=</span> <span class="fu">round</span>(<span class="fu">sd</span>(alturas),<span class="dv">2</span>)</span></code></pre></div>
<p>No exemplo das alturas dos estudantes temos a média de 1.69 m e um desvio padrão de 0.11 m. Assim, <strong>ao menos</strong> 75% das alturas deverão estar entre 1.47 m e 1.91 m.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="descritiva.html#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(alturas)</span></code></pre></div>
<pre><code>##  [1] 1.41 1.44 1.47 1.54 1.55 1.56 1.56 1.56 1.57 1.58 1.58 1.61 1.62 1.62 1.63
## [16] 1.64 1.64 1.65 1.65 1.65 1.65 1.66 1.66 1.66 1.66 1.66 1.67 1.67 1.67 1.67
## [31] 1.68 1.68 1.68 1.69 1.71 1.71 1.72 1.72 1.73 1.73 1.73 1.73 1.73 1.74 1.75
## [46] 1.76 1.76 1.77 1.78 1.78 1.79 1.82 1.83 1.83 1.84 1.85 1.86 1.93 1.95 2.00</code></pre>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="descritiva.html#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Duas observações menores que 1,47m e trẽs maiores que 1,91m.</span></span>
<span id="cb36-2"><a href="descritiva.html#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Assim, 54 observações dentro do intervalo, equivalendo a 91,66% do total.</span></span></code></pre></div>
</div>
</div>
<div id="medidas-de-subdivisão-separatrizes" class="section level3 hasAnchor" number="3.3.3">
<h3><span class="header-section-number">3.3.3</span> Medidas de subdivisão (separatrizes)<a href="descritiva.html#medidas-de-subdivisão-separatrizes" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Separatrizes (quantis) são valores que delimitam uma proporção de observações existentes de um conjunto de dados previamente ordenados menores que ele.</p>
<p>De modo geral, um <em>quantil</em> de ordem <span class="math inline">\(p\)</span> (ou também <span class="math inline">\(p-quantil\)</span>, indicado por <span class="math inline">\(q_{p}\)</span>) é uma medida onde <span class="math inline">\(p\)</span> é uma proporção qualquer (limitada no intervalo 0 &lt; p &lt; 1), tal que 100<span class="math inline">\(p\)</span>% das observações sejam menores que seu valor <span class="math inline">\(q_{p}\)</span>. Os <em>quantis</em> mais relevantes são:</p>
<ul>
<li>1<span class="math inline">\(^{o}\)</span> Quartil (<span class="math inline">\(q_{0,25}\)</span>): 25% dos dados possuem valores abaixo desse valor e 75% estão acima;</li>
<li>2<span class="math inline">\(^{o}\)</span> Quartil ou mediana (<span class="math inline">\(q_{0,50}\)</span>): 50% dos dados possuem valores abaixo desse valor e 50% estão acima; e,</li>
<li>3<span class="math inline">\(^{o}\)</span> Quartil (<span class="math inline">\(q_{0,75}\)</span>): 75% dos dados possuem valores abaixo desse valor e 25% estão acima.</li>
</ul>
<p>Para se calcular a <strong>posição</strong> <em>L</em> de um quantil de ordem <em>p</em> em um rol de dados, pode-se usar a seguinte regra:</p>
<p><span class="math display">\[
L=\frac{p}{100} \times (n+1)
\]</span></p>
<p>Duas situações possíveis para a posição <strong>L</strong>: ser um número fracionário ou inteiro:</p>
<ul>
<li>se a posição <strong>L for fracionária</strong> deve-se fazer a média entre os dois valores que estão nas posições imediatamente anterior e imediatamente posterior à posição calculada;</li>
<li>se a posição <strong>L for um inteiro</strong> essa será a posição do valor referente ao quantil desejado.</li>
</ul>
<p>Onde:</p>
<ul>
<li><em>p</em> é a <strong>ordem</strong> do quantil em % (50% no caso mediana, por exemplo);</li>
<li><em>n</em> é o número de dados do rol; e,</li>
<li><em>L</em> é a <strong>posição</strong> do valor referente ao quantil desejado.</li>
</ul>
<p>Juntamente com as observações mínima (<span class="math inline">\(x_{i}\)</span>) e máxima (<span class="math inline">\(x_{n}\)</span>), o 1<span class="math inline">\(^{o}\)</span>, 2<span class="math inline">\(^{o}\)</span> e 3<span class="math inline">\(^{o}\)</span> Quartis são importantes para se ter uma boa idéia da assimetria da distribuição dos dados.</p>
<p>Para uma distribuição simétrica (ou aproximadamente simétrica) deveremos observar (Distribuição Gaussiana):</p>
<ul>
<li>a dispersão inferior: <span class="math inline">\(q_{2} - x_{1} \approx x_{n} - q_{2}\)</span> à dispersão superior ;</li>
<li><span class="math inline">\(q_{2} - q_{1} \approx q_{3} - q_{2}\)</span>; e,</li>
<li><span class="math inline">\(q_{1} - x_{1} \approx x_{n} - q_{3}\)</span>.</li>
</ul>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="descritiva.html#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1000</span>)</span>
<span id="cb37-2"><a href="descritiva.html#cb37-2" aria-hidden="true" tabindex="-1"></a>y_normal<span class="ot">=</span><span class="fu">rnorm</span>(<span class="dv">1000</span> , <span class="dv">20</span> , <span class="dv">5</span> )</span>
<span id="cb37-3"><a href="descritiva.html#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(y_normal)</span></code></pre></div>
<pre><code>## [1]  3.191432 33.350358</code></pre>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="descritiva.html#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(y_normal)</span></code></pre></div>
<pre><code>##        0%       25%       50%       75%      100% 
##  3.191432 16.685004 20.112604 23.220489 33.350358</code></pre>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="descritiva.html#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(y_normal, <span class="at">prob=</span><span class="cn">TRUE</span>, <span class="at">breaks=</span><span class="dv">20</span>, <span class="at">ylab=</span><span class="st">&quot;&quot;</span>, <span class="at">xlab=</span><span class="st">&quot;&quot;</span>, <span class="at">yaxt=</span><span class="st">&quot;n&quot;</span>,  <span class="at">xaxt=</span><span class="st">&quot;n&quot;</span>, <span class="at">main=</span><span class="st">&quot;Histograma de uma variável com Distribuição Normal&quot;</span>)</span>
<span id="cb41-2"><a href="descritiva.html#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x, <span class="fu">mean</span>(y_normal), <span class="fu">sd</span>(y_normal)), <span class="at">add=</span><span class="cn">TRUE</span>, <span class="at">col=</span><span class="st">&quot;darkblue&quot;</span>, <span class="at">lwd=</span><span class="dv">2</span>)</span>
<span id="cb41-3"><a href="descritiva.html#cb41-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-4"><a href="descritiva.html#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fl">3.19</span>, <span class="at">col=</span><span class="st">&quot;red&quot;</span>) </span>
<span id="cb41-5"><a href="descritiva.html#cb41-5" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="fl">3.19</span> <span class="sc">-</span><span class="fl">0.6</span>, <span class="fl">0.02</span>, <span class="st">&quot;x(1)&quot;</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">srt=</span><span class="dv">90</span>)</span>
<span id="cb41-6"><a href="descritiva.html#cb41-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fl">16.68</span>, <span class="at">col=</span><span class="st">&quot;red&quot;</span>) </span>
<span id="cb41-7"><a href="descritiva.html#cb41-7" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="fl">16.68</span> <span class="sc">-</span><span class="fl">0.6</span>, <span class="fl">0.02</span>, <span class="st">&quot;1? Quartil&quot;</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">srt=</span><span class="dv">90</span>)</span>
<span id="cb41-8"><a href="descritiva.html#cb41-8" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fl">20.11</span>, <span class="at">col=</span><span class="st">&quot;red&quot;</span>) </span>
<span id="cb41-9"><a href="descritiva.html#cb41-9" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="fl">20.11</span> <span class="sc">-</span> <span class="fl">0.6</span>, <span class="fl">0.02</span>, <span class="st">&quot;2? Quartil&quot;</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">srt=</span><span class="dv">90</span>)</span>
<span id="cb41-10"><a href="descritiva.html#cb41-10" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fl">23.22</span>, <span class="at">col=</span><span class="st">&quot;red&quot;</span>) </span>
<span id="cb41-11"><a href="descritiva.html#cb41-11" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="fl">23.22</span> <span class="sc">-</span> <span class="fl">0.6</span>, <span class="fl">0.02</span>, <span class="st">&quot;3? Quartil&quot;</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">srt=</span><span class="dv">90</span>)</span>
<span id="cb41-12"><a href="descritiva.html#cb41-12" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fl">33.35</span>, <span class="at">col=</span><span class="st">&quot;red&quot;</span>) </span>
<span id="cb41-13"><a href="descritiva.html#cb41-13" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="fl">33.35</span> <span class="sc">-</span><span class="fl">0.6</span>, <span class="fl">0.02</span>, <span class="st">&quot;x(n)&quot;</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">srt=</span><span class="dv">90</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-47"></span>
<img src="_main_files/figure-html/unnamed-chunk-47-1.png" alt="Histograma de uma variável com Distribuição Normal (média 20 e variãncia 5" width="672" />
<p class="caption">
Figure 3.9: Histograma de uma variável com Distribuição Normal (média 20 e variãncia 5
</p>
</div>
</div>
</div>
<div id="medidas-de-forma-assimetria-curtose" class="section level2 hasAnchor" number="3.4">
<h2><span class="header-section-number">3.4</span> Medidas de forma (assimetria &amp; curtose)<a href="descritiva.html#medidas-de-forma-assimetria-curtose" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Quando analisamos o histograma (a representação gráfica da distribuição das frequências dos valores agrupados em classes) de uma determinada variável, não é muito comum que ele se mostre simétrico tal como seria se os dados fossem distribuídos de modo exatamente Normal.</p>
<p>Ao observarmos que a cauda se mostra mais alongada para a direita (indicativo da existência de uma quantidade maior de dados com grandes valores, <em>arrastando</em> a média para a direita: moda <span class="math inline">\(&lt;\)</span> mediana <span class="math inline">\(&lt;\)</span> média) diz-se que a <em>distribuição é assimétrica à direita</em>. Na situação oposta (moda <span class="math inline">\(&gt;\)</span> mediana <span class="math inline">\(&gt;\)</span> média) diz-se que ela é <em>assimétrica à esquerda</em>.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="descritiva.html#cb42-1" aria-hidden="true" tabindex="-1"></a>a<span class="ot">=</span><span class="fu">rbeta</span>(<span class="dv">10000</span>,<span class="dv">5</span>,<span class="dv">2</span>)</span>
<span id="cb42-2"><a href="descritiva.html#cb42-2" aria-hidden="true" tabindex="-1"></a>c<span class="ot">=</span><span class="fu">rbeta</span>(<span class="dv">10000</span>,<span class="dv">5</span>,<span class="dv">5</span>)</span>
<span id="cb42-3"><a href="descritiva.html#cb42-3" aria-hidden="true" tabindex="-1"></a>b<span class="ot">=</span><span class="fu">rbeta</span>(<span class="dv">10000</span>,<span class="dv">2</span>,<span class="dv">5</span>)</span>
<span id="cb42-4"><a href="descritiva.html#cb42-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-5"><a href="descritiva.html#cb42-5" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>))</span>
<span id="cb42-6"><a href="descritiva.html#cb42-6" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(a, </span>
<span id="cb42-7"><a href="descritiva.html#cb42-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;Valores&quot;</span>,<span class="at">col =</span> <span class="st">&#39;lightblue&#39;</span>,</span>
<span id="cb42-8"><a href="descritiva.html#cb42-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">&quot;Frequência&quot;</span>,</span>
<span id="cb42-9"><a href="descritiva.html#cb42-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;Assimetria à esq.&quot;</span>)</span>
<span id="cb42-10"><a href="descritiva.html#cb42-10" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(c, </span>
<span id="cb42-11"><a href="descritiva.html#cb42-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;Valores&quot;</span>,<span class="at">col =</span> <span class="st">&#39;lightblue&#39;</span>,</span>
<span id="cb42-12"><a href="descritiva.html#cb42-12" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">&quot;Frequência&quot;</span>,</span>
<span id="cb42-13"><a href="descritiva.html#cb42-13" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;Relativa simetria&quot;</span>)</span>
<span id="cb42-14"><a href="descritiva.html#cb42-14" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(b, </span>
<span id="cb42-15"><a href="descritiva.html#cb42-15" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;Valores&quot;</span>,<span class="at">col =</span> <span class="st">&#39;lightblue&#39;</span>,</span>
<span id="cb42-16"><a href="descritiva.html#cb42-16" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">&quot;Frequência&quot;</span>,</span>
<span id="cb42-17"><a href="descritiva.html#cb42-17" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;Assimetria à dir.&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-48"></span>
<img src="_main_files/figure-html/unnamed-chunk-48-1.png" alt="Diferentes formas na distribuição dos dados" width="80%" />
<p class="caption">
Figure 3.10: Diferentes formas na distribuição dos dados
</p>
</div>
<p>De modo assemelhado, o histograma pode denotar uma forma mais <em>plana</em> ou menos <em>aguda</em>, onde um <em>cume</em> mostra-se mais destacado.</p>
<p>Nesse aspecto da forma, uma variável com distribuição Gaussiana apresentaria uma curva a que denominamos <em>mesocúrtica</em>. Distribuições com um aspecto mais plano são denominadas de <em>platicúrticas</em> e as com um cume agudo são denominadas <em>leptocúrticas</em>.</p>
<p>A curtose é uma medida da agudeza da distribuição dos dados em relação à distribuição Gaussiana.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-49"></span>
<img src="images3/curtose.jpg" alt="Diferentes aspectos de uma distribuição quanto à sua inclinação" width="50%" />
<p class="caption">
Figure 3.11: Diferentes aspectos de uma distribuição quanto à sua inclinação
</p>
</div>
<p>Essas possíveis variações na forma de uma distribuição podem ser numericamente quantificadas através dos <em>coeficientes de assimetria e curtose</em>.</p>
<p>Uma das medidas do coeficiente de assimetria é através do <em>primeiro ou segundo coeficientes de Pearson</em>, dados pelas seguintes relações:</p>
<ul>
<li>Primeiro coeficiente de assimetria de Pearson: <span class="math inline">\(AS= \frac{ \stackrel{-}{x} - M_{o} }{ s }\)</span></li>
<li>Segundo coeficiente de assimetria de Pearson: <span class="math inline">\(AS = \frac{ 3 ( \stackrel{-}{x} - M_{d}) } { s }\)</span></li>
</ul>
<p>Onde:</p>
<ul>
<li><span class="math inline">\(\stackrel{-}{x}\)</span> é a média;</li>
<li><span class="math inline">\(M_{o}\)</span> é a moda;</li>
<li><span class="math inline">\(S\)</span> é o desvio padrão; e,</li>
<li><span class="math inline">\(M_{d}\)</span> é a mediana.</li>
</ul>
<p>A <em>assimetria</em> é classificada do modo seguinte:</p>
<ul>
<li>AS=0: distribuição simétrica;</li>
<li>AS&lt;0: distribuição com assimetria negativa; e,</li>
<li>AS&gt;0: distribuição com assimetria positiva.</li>
</ul>
<p>Uma das medidas do coeficiente de curtose é através da seguinte relação entre <em>quartis</em> e <em>percentis</em>:</p>
<p><span class="math display">\[
K = \frac{\frac{Q_{3} - Q_{1}}{2}   }   {P_{90} - P_{10}}
\]</span></p>
<p>Onde:</p>
<ul>
<li><span class="math inline">\(Q_{3}\)</span> = <span class="math inline">\(3^{o}\)</span> quartil;</li>
<li><span class="math inline">\(Q_{1}\)</span> = <span class="math inline">\(1^{o}\)</span> quartil;</li>
<li><span class="math inline">\(P_{90}\)</span> = <span class="math inline">\(90^{o}\)</span> percentil; e,</li>
<li><span class="math inline">\(P_{10}\)</span> = <span class="math inline">\(10^{o}\)</span> percentil.</li>
</ul>
<p>O <em>coeficiente de curtose</em> é classificado do modo seguinte:</p>
<ul>
<li>k = 0; 263: distribuição mesocúrtica;</li>
<li>k &lt; 0; 263: distribuição leptocúrtica; e,</li>
<li>k &gt; 0; 263: distribuição platicúrtica.</li>
</ul>
</div>
<div id="apresentação-gráfica-de-dados" class="section level2 hasAnchor" number="3.5">
<h2><span class="header-section-number">3.5</span> Apresentação gráfica de dados<a href="descritiva.html#apresentação-gráfica-de-dados" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Uma apresentação na forma gráfica torna ainda mais fácil a visualização das informações contidas nos dados.</p>
<p>Há uma gama enorme de gráficos para a representação de dados a depender de sua natureza (qualitativa ou quantitativa). Alguns dos tipos mais comuns são:</p>
<ol style="list-style-type: decimal">
<li>qualitativas</li>
</ol>
<ul>
<li>ranking: barras;</li>
<li>parte em relação ao todo: setores;</li>
</ul>
<ol start="2" style="list-style-type: decimal">
<li>quantitativas</li>
</ol>
<ul>
<li>ranking: barras;</li>
<li>parte em relação ao todo: setores;</li>
<li>dispersão unidimensional;</li>
<li>distribuição: histograma e o <em>box plot</em>;</li>
<li>correlação: pontos dispersos; e,</li>
<li>tendência: linha</li>
</ul>
<p>Se modificarmos o diagrama de ramos e folhas dos comprimentos e quantidades observadas, representando cada uma das alturas medidas por um <em>retângulo</em> cujas alturas sejam proporcionais à quantidade contada de cada uma dessas alturas teremos um <em>Gráfico de barras</em>.</p>
<div id="barras" class="section level3 hasAnchor" number="3.5.1">
<h3><span class="header-section-number">3.5.1</span> Barras<a href="descritiva.html#barras" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="descritiva.html#cb43-1" aria-hidden="true" tabindex="-1"></a>tab_alturas<span class="ot">=</span><span class="fu">table</span>(alturas)</span>
<span id="cb43-2"><a href="descritiva.html#cb43-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-3"><a href="descritiva.html#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(tab_alturas,</span>
<span id="cb43-4"><a href="descritiva.html#cb43-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">main=</span><span class="st">&quot;Valores observados da alturas dos estudantes&quot;</span>,</span>
<span id="cb43-5"><a href="descritiva.html#cb43-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab=</span><span class="st">&quot;Altura (cm)&quot;</span>,</span>
<span id="cb43-6"><a href="descritiva.html#cb43-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab=</span><span class="st">&quot;Quantidade observada (un)&quot;</span>,</span>
<span id="cb43-7"><a href="descritiva.html#cb43-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">6</span>),</span>
<span id="cb43-8"><a href="descritiva.html#cb43-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">col=</span><span class="st">&quot;blue&quot;</span>,</span>
<span id="cb43-9"><a href="descritiva.html#cb43-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">las=</span><span class="dv">0</span>, </span>
<span id="cb43-10"><a href="descritiva.html#cb43-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">hor=</span><span class="st">&quot;FALSE&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-50"></span>
<img src="_main_files/figure-html/unnamed-chunk-50-1.png" alt="Gráfico de barras dos dados brutos: uma barra para cada observação e sua altura expressando o número de observações com esse valor" width="672" />
<p class="caption">
Figure 3.12: Gráfico de barras dos dados brutos: uma barra para cada observação e sua altura expressando o número de observações com esse valor
</p>
</div>
<p>Para dados quantitativos, o agrupamento dos valores brutos observados em classes (cada uma com um valor mínimo e máximo fixado) permite a geração de um <em>Histograma</em>, um tipo diferente de <em>Gráfico de barras</em> onde cada coluna está unida às colunas imediatamente adjacentes (indicando a continuidade de valores das medidas) e sua altura expressa a quantidade de observações contidas nessa classe.</p>
<p>Se adotarmos arbitrariamente como classes para as alturas: 1,30-1,40; 1,40-1,50; 1,50-1,60; 1,60-1,70; 1,70-1,80; 1,80-1,90; 1,90-2,00; 2,00-2,10, o histograma terá esse aspecto:</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="descritiva.html#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(alturas, <span class="at">breaks=</span><span class="fu">seq</span>(<span class="fl">1.30</span> , <span class="fl">2.10</span> , <span class="fl">0.10</span>), <span class="at">main=</span> <span class="st">&quot;Histograma das alturas dos estudantes&quot;</span>, <span class="at">col=</span><span class="st">&quot;blue&quot;</span>, </span>
<span id="cb44-2"><a href="descritiva.html#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="at">xlab=</span><span class="st">&quot;Classes de altura (m)&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Frequência observada (un)&quot;</span> , <span class="at">cex=</span><span class="fl">0.7</span>, <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">30</span>))</span>
<span id="cb44-3"><a href="descritiva.html#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(h1<span class="sc">$</span>mids,h1<span class="sc">$</span>counts,<span class="at">labels=</span>h1<span class="sc">$</span>counts, <span class="at">adj=</span><span class="fu">c</span>(<span class="fl">0.5</span>, <span class="sc">-</span><span class="fl">0.5</span>))</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-51"></span>
<img src="_main_files/figure-html/unnamed-chunk-51-1.png" alt="Histograma das alturas dos estudantes. Uma barra para cada classe de altura  e sua altura expressando a quantidade de observações com valores dentro dessa classe (intencionalmente criamos duas classe sem nenhuma observação)" width="672" />
<p class="caption">
Figure 3.13: Histograma das alturas dos estudantes. Uma barra para cada classe de altura e sua altura expressando a quantidade de observações com valores dentro dessa classe (intencionalmente criamos duas classe sem nenhuma observação)
</p>
</div>
</div>
<div id="setores" class="section level3 hasAnchor" number="3.5.2">
<h3><span class="header-section-number">3.5.2</span> Setores<a href="descritiva.html#setores" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Em um <em>Gráfico de setores</em> a representação das quantidades está associada a uma fração do comprimento de um círculo. Para sua confecção considera-se a proporção da quantidade observada específica da quantidade total de dados, expressa na forma de fração do ângulo de um setor circular em relação ao ângulo interno total de um círculo (360<sup>o</sup>).</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="descritiva.html#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span>
<span id="cb45-2"><a href="descritiva.html#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb45-3"><a href="descritiva.html#cb45-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-4"><a href="descritiva.html#cb45-4" aria-hidden="true" tabindex="-1"></a>alturas_classes<span class="ot">=</span><span class="fu">data.frame</span>(</span>
<span id="cb45-5"><a href="descritiva.html#cb45-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">group =</span> <span class="fu">c</span>(<span class="st">&quot;1,40-1,50&quot;</span>,</span>
<span id="cb45-6"><a href="descritiva.html#cb45-6" aria-hidden="true" tabindex="-1"></a>            <span class="st">&quot;1,50-1,60&quot;</span>,</span>
<span id="cb45-7"><a href="descritiva.html#cb45-7" aria-hidden="true" tabindex="-1"></a>            <span class="st">&quot;1,60-1,70&quot;</span>,</span>
<span id="cb45-8"><a href="descritiva.html#cb45-8" aria-hidden="true" tabindex="-1"></a>            <span class="st">&quot;1,70-1,80&quot;</span>,</span>
<span id="cb45-9"><a href="descritiva.html#cb45-9" aria-hidden="true" tabindex="-1"></a>            <span class="st">&quot;1,80-1,90&quot;</span>,</span>
<span id="cb45-10"><a href="descritiva.html#cb45-10" aria-hidden="true" tabindex="-1"></a>            <span class="st">&quot;1,90-2,00&quot;</span>),</span>
<span id="cb45-11"><a href="descritiva.html#cb45-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">value =</span> <span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">8</span>,<span class="dv">23</span>,<span class="dv">17</span>,<span class="dv">6</span>,<span class="dv">3</span>)</span>
<span id="cb45-12"><a href="descritiva.html#cb45-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb45-13"><a href="descritiva.html#cb45-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-14"><a href="descritiva.html#cb45-14" aria-hidden="true" tabindex="-1"></a>bp<span class="ot">=</span><span class="fu">ggplot</span>(alturas_classes, <span class="fu">aes</span>(<span class="at">x=</span><span class="st">&quot;&quot;</span>, <span class="at">y=</span>value, <span class="at">fill=</span>group))<span class="sc">+</span></span>
<span id="cb45-15"><a href="descritiva.html#cb45-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">width =</span> <span class="dv">1</span>, <span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>)</span>
<span id="cb45-16"><a href="descritiva.html#cb45-16" aria-hidden="true" tabindex="-1"></a>pie<span class="ot">=</span>bp <span class="sc">+</span> <span class="fu">coord_polar</span>(<span class="st">&quot;y&quot;</span>, <span class="at">start=</span><span class="dv">0</span>)</span>
<span id="cb45-17"><a href="descritiva.html#cb45-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-18"><a href="descritiva.html#cb45-18" aria-hidden="true" tabindex="-1"></a>blank_theme <span class="ot">&lt;-</span> <span class="fu">theme_minimal</span>()<span class="sc">+</span></span>
<span id="cb45-19"><a href="descritiva.html#cb45-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb45-20"><a href="descritiva.html#cb45-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb45-21"><a href="descritiva.html#cb45-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb45-22"><a href="descritiva.html#cb45-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.border =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb45-23"><a href="descritiva.html#cb45-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid=</span><span class="fu">element_blank</span>(),</span>
<span id="cb45-24"><a href="descritiva.html#cb45-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.ticks =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb45-25"><a href="descritiva.html#cb45-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title=</span><span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">14</span>, <span class="at">face=</span><span class="st">&quot;bold&quot;</span>)</span>
<span id="cb45-26"><a href="descritiva.html#cb45-26" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb45-27"><a href="descritiva.html#cb45-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-28"><a href="descritiva.html#cb45-28" aria-hidden="true" tabindex="-1"></a>pie <span class="sc">+</span> </span>
<span id="cb45-29"><a href="descritiva.html#cb45-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="st">&quot;Blues&quot;</span>)<span class="sc">+</span></span>
<span id="cb45-30"><a href="descritiva.html#cb45-30" aria-hidden="true" tabindex="-1"></a>  blank_theme <span class="sc">+</span></span>
<span id="cb45-31"><a href="descritiva.html#cb45-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x=</span><span class="fu">element_blank</span>()) <span class="sc">+</span></span>
<span id="cb45-32"><a href="descritiva.html#cb45-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">y =</span> value<span class="sc">/</span><span class="dv">3</span> <span class="sc">+</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fu">cumsum</span>(value)[<span class="sc">-</span><span class="fu">length</span>(value)]), </span>
<span id="cb45-33"><a href="descritiva.html#cb45-33" aria-hidden="true" tabindex="-1"></a>                <span class="at">label =</span> <span class="fu">percent</span>(value<span class="sc">/</span><span class="dv">100</span>)), <span class="at">size=</span><span class="dv">5</span>)<span class="sc">+</span></span>
<span id="cb45-34"><a href="descritiva.html#cb45-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Alturas dos estudantes&quot;</span>) <span class="sc">+</span></span>
<span id="cb45-35"><a href="descritiva.html#cb45-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;right&quot;</span>, <span class="at">legend.justification =</span> <span class="st">&quot;center&quot;</span>, <span class="at">legend.direction =</span> <span class="st">&quot;vertical&quot;</span>,</span>
<span id="cb45-36"><a href="descritiva.html#cb45-36" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.spacing.x =</span> <span class="fu">unit</span>(<span class="fl">0.5</span>, <span class="st">&#39;cm&#39;</span>),<span class="at">legend.spacing.y =</span> <span class="fu">unit</span>(<span class="fl">0.5</span>, <span class="st">&#39;cm&#39;</span>))<span class="sc">+</span></span>
<span id="cb45-37"><a href="descritiva.html#cb45-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill =</span> <span class="fu">guide_legend</span>(<span class="at">title =</span> <span class="st">&quot;Classes de valores (m)&quot;</span>,</span>
<span id="cb45-38"><a href="descritiva.html#cb45-38" aria-hidden="true" tabindex="-1"></a>                             <span class="at">label.position =</span> <span class="st">&quot;right&quot;</span>,</span>
<span id="cb45-39"><a href="descritiva.html#cb45-39" aria-hidden="true" tabindex="-1"></a>                             <span class="at">title.position =</span> <span class="st">&quot;top&quot;</span>, <span class="at">title.vjust =</span> <span class="dv">1</span>)) </span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-52"></span>
<img src="_main_files/figure-html/unnamed-chunk-52-1.png" alt="Gráfico de setores das alturas dos estudantes" width="672" />
<p class="caption">
Figure 3.14: Gráfico de setores das alturas dos estudantes
</p>
</div>
</div>
<div id="box-plot" class="section level3 hasAnchor" number="3.5.3">
<h3><span class="header-section-number">3.5.3</span> Box-plot<a href="descritiva.html#box-plot" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>O gráfico <strong>Box-plot</strong> ( <em>box and whisker plot</em> ): esse gráfico apresenta de modo conjunto, informações sobre a posição, dispersão, assimetria e dados discrepantes do conjunto analisado:</p>
<ul>
<li>a mediana (<span class="math inline">\(q_{2}\)</span>);</li>
<li>os valores mínimo: <span class="math inline">\(x_{1}\)</span> e máximo: <span class="math inline">\(x_{n}\)</span> (dados ordenados);</li>
<li>o 1<span class="math inline">\(^{o}\)</span> e 3<span class="math inline">\(^{o}\)</span> quartis;</li>
<li>a dispersão (intervalo interquartílico: <span class="math inline">\(q_{3}\)</span> - <span class="math inline">\(q_{1}\)</span>);</li>
<li>os limites superior: LS= <span class="math inline">\(q_{3}\)</span> + 1,50<span class="math inline">\(d_{q}\)</span>, e inferior: LI= <span class="math inline">\(q_{1}\)</span> - 1,50<span class="math inline">\(d_{q}\)</span> ( <em>bigodes</em>);</li>
<li>as observações adjacentes aos limites: situadas entre o 1<span class="math inline">\(^{o}\)</span> quartil e o LI, e o 3<span class="math inline">\(^{o}\)</span> quartil e o LS; e,</li>
<li>as observações exteriores aos limites: situadas abaixo do <em>LI</em> ou acima do <em>LS</em> que <strong>podem ou não</strong> ser <em>outliers</em> (dados atípicos).</li>
</ul>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="descritiva.html#cb46-1" aria-hidden="true" tabindex="-1"></a>res<span class="ot">=</span><span class="fu">summary</span>(y_normal)</span>
<span id="cb46-2"><a href="descritiva.html#cb46-2" aria-hidden="true" tabindex="-1"></a>min<span class="ot">=</span>res[<span class="dv">1</span>]</span>
<span id="cb46-3"><a href="descritiva.html#cb46-3" aria-hidden="true" tabindex="-1"></a>q1<span class="ot">=</span>res[<span class="dv">2</span>]</span>
<span id="cb46-4"><a href="descritiva.html#cb46-4" aria-hidden="true" tabindex="-1"></a>q2<span class="ot">=</span>res[<span class="dv">3</span>]</span>
<span id="cb46-5"><a href="descritiva.html#cb46-5" aria-hidden="true" tabindex="-1"></a>med<span class="ot">=</span>res[<span class="dv">4</span>]</span>
<span id="cb46-6"><a href="descritiva.html#cb46-6" aria-hidden="true" tabindex="-1"></a>q3<span class="ot">=</span>res[<span class="dv">5</span>]</span>
<span id="cb46-7"><a href="descritiva.html#cb46-7" aria-hidden="true" tabindex="-1"></a>max<span class="ot">=</span>res[<span class="dv">6</span>]</span>
<span id="cb46-8"><a href="descritiva.html#cb46-8" aria-hidden="true" tabindex="-1"></a>dist<span class="ot">=</span>q3<span class="sc">-</span>q1</span>
<span id="cb46-9"><a href="descritiva.html#cb46-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-10"><a href="descritiva.html#cb46-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-11"><a href="descritiva.html#cb46-11" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(y_normal, <span class="at">main=</span><span class="st">&quot;&quot;</span>)</span>
<span id="cb46-12"><a href="descritiva.html#cb46-12" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>( <span class="at">y=</span><span class="fu">c</span>(min, min), <span class="at">x=</span><span class="fu">c</span>(<span class="fl">0.6</span>,<span class="dv">1</span>), <span class="at">col=</span><span class="st">&quot;red&quot;</span>) </span>
<span id="cb46-13"><a href="descritiva.html#cb46-13" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x=</span><span class="fl">0.60</span>, <span class="at">y=</span>min <span class="sc">-</span><span class="fl">0.6</span>, <span class="st">&quot;Primeira observação&quot;</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">srt=</span><span class="dv">0</span>)</span>
<span id="cb46-14"><a href="descritiva.html#cb46-14" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>( <span class="at">y=</span><span class="fu">c</span>(max,max), <span class="at">x=</span><span class="fu">c</span>(<span class="fl">0.6</span>,<span class="dv">1</span>), <span class="at">col=</span><span class="st">&quot;red&quot;</span>) </span>
<span id="cb46-15"><a href="descritiva.html#cb46-15" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x=</span><span class="fl">0.60</span>, <span class="at">y=</span>max<span class="fl">-0.6</span>, <span class="st">&quot;Úlitma observação&quot;</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">srt=</span><span class="dv">0</span>)</span>
<span id="cb46-16"><a href="descritiva.html#cb46-16" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">y=</span><span class="fu">c</span>(q2, q2),  <span class="at">x=</span><span class="fu">c</span>(<span class="fl">0.6</span>,<span class="dv">1</span>), <span class="at">col=</span><span class="st">&quot;red&quot;</span>) </span>
<span id="cb46-17"><a href="descritiva.html#cb46-17" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x=</span><span class="fl">0.60</span> , <span class="at">y=</span> q2 <span class="sc">-</span> <span class="fl">0.6</span>, <span class="st">&quot;Mediana&quot;</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">srt=</span><span class="dv">0</span>)</span>
<span id="cb46-18"><a href="descritiva.html#cb46-18" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">y=</span><span class="fu">c</span>(med, med),  <span class="at">x=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="fl">1.4</span>), <span class="at">col=</span><span class="st">&quot;red&quot;</span>) </span>
<span id="cb46-19"><a href="descritiva.html#cb46-19" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x=</span><span class="fl">1.4</span> , <span class="at">y=</span> med <span class="sc">-</span> <span class="fl">0.6</span>, <span class="st">&quot;Média&quot;</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">srt=</span><span class="dv">0</span>)</span>
<span id="cb46-20"><a href="descritiva.html#cb46-20" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">y=</span><span class="fu">c</span>(q3, q3), <span class="at">x=</span><span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">1.4</span>), <span class="at">col=</span><span class="st">&quot;red&quot;</span>) </span>
<span id="cb46-21"><a href="descritiva.html#cb46-21" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x=</span> <span class="fl">1.4</span> , <span class="at">y=</span>q3 <span class="sc">-</span> <span class="fl">0.6</span>, <span class="st">&quot;Terceiro Quartil&quot;</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">srt=</span><span class="dv">0</span>)</span>
<span id="cb46-22"><a href="descritiva.html#cb46-22" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">y=</span><span class="fu">c</span>(q1, q1), <span class="at">x=</span><span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">1.4</span>), <span class="at">col=</span><span class="st">&quot;red&quot;</span>) </span>
<span id="cb46-23"><a href="descritiva.html#cb46-23" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x=</span><span class="fl">1.4</span>, <span class="at">y=</span>q1 <span class="sc">-</span><span class="fl">0.6</span>, <span class="st">&quot;Primeiro Quartil&quot;</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">srt=</span><span class="dv">0</span>)</span>
<span id="cb46-24"><a href="descritiva.html#cb46-24" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">y=</span><span class="fu">c</span>(q1<span class="fl">-1.5</span><span class="sc">*</span>dist, q1<span class="fl">-1.5</span><span class="sc">*</span>dist) , <span class="at">x=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="fl">1.4</span>) , <span class="at">col=</span><span class="st">&quot;blue&quot;</span>) </span>
<span id="cb46-25"><a href="descritiva.html#cb46-25" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x=</span><span class="fl">1.2</span>, <span class="at">y=</span>q1<span class="fl">-1.5</span><span class="sc">*</span>dist<span class="fl">-0.6</span> , <span class="st">&quot;Obs. limitante inferior&quot;</span>, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">srt=</span><span class="dv">0</span>)</span>
<span id="cb46-26"><a href="descritiva.html#cb46-26" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">y=</span><span class="fu">c</span>(q3<span class="fl">+1.5</span><span class="sc">*</span>dist, q3<span class="fl">+1.5</span><span class="sc">*</span>dist) , <span class="at">x=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="fl">1.4</span>) , <span class="at">col=</span><span class="st">&quot;blue&quot;</span>) </span>
<span id="cb46-27"><a href="descritiva.html#cb46-27" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x=</span><span class="fl">1.2</span>, <span class="at">y=</span>q3<span class="fl">+1.5</span><span class="sc">*</span>dist <span class="sc">-</span><span class="fl">0.6</span> , <span class="st">&quot;Obs. limitante superior&quot;</span>, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">srt=</span><span class="dv">0</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-53"></span>
<img src="_main_files/figure-html/unnamed-chunk-53-1.png" alt="Box-plot de um rol de valores com Distribuição Normal (média 20 e variãncia 5" width="672" />
<p class="caption">
Figure 3.15: Box-plot de um rol de valores com Distribuição Normal (média 20 e variãncia 5
</p>
</div>
</div>
</div>
<div id="apresentação-tabular-de-dados-quantitativos" class="section level2 hasAnchor" number="3.6">
<h2><span class="header-section-number">3.6</span> Apresentação tabular de dados quantitativos<a href="descritiva.html#apresentação-tabular-de-dados-quantitativos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Ao se lidar com grandes conjuntos de dados a visualização da informação contida nos dados pode ficar comprometida. Um dos modos de se lidar com isso é condensando a informação dos dados brutos em tabelas. Uma tabela é uma forma não discursiva de apresentar informações nas quais o dado numérico se destaca como informação central.</p>
<p>Uma tabela se diferencia de um quadro por este ter todos os seus campos delimitados por linhas e conter apenas informações de natureza qualitativa.</p>
<p>Uma tabela deve ter:</p>
<ul>
<li>título que explique o que a tabela contém, local, data;</li>
<li>cabeçalho com os nomes das variáveis;</li>
<li>corpo formado pelos dados referentes às variáveis;</li>
<li>fonte;</li>
<li>uniformidade no número de casas decimais; e,</li>
<li>todas as casas devem apresentar valores ou símbolos que expliquem a ausência da informação (NI, NE).</li>
</ul>
<p>Trabalhos de natureza acadêmica ou científica deveriam obrigatoriamente seguir, quando publicados no Brasil, a norma vigente publicada pela ABNT: Associação Brasileira de Normas Técnicas.</p>
<p>Observa-se frequentemente, todavia, que as publicações seguem normas particulares das instituições de ensino (para trabalhos de conclusão de curso, monografias, dissertações e teses) ou das editoras (artigos), muitas vezes mescladas com recomendações da ABNT.</p>
<p>Com o propósito de mostrar alguns gráficos nos exemplos anteriores escolhemos, de modo arbitrário, agrupar seus valores (as alturas) em <em>classes</em>.</p>
<p>O procedimento estatístico de agrupar os dados em <em>classes</em> ou <em>categorias</em> envolve construir uma <em>tabela de distribuição de frequências</em>.</p>
<p>Uma <em>tabela de distribuição de frequências</em> associa cada <em>classe</em> (intervalo) de valores da variável estudada ao número de ocorrências observadas. Como <em>regra prática</em>, a repartição dos dados brutos em classes deve sempre observar para que não haja um número excessivo de classes (diminuição da finalidade de resumir os dados, criação de classes sem nenhuma observação) nem tampouco poucas (que não possibilitem a visualização da distribuição e promovam perda da informação original).</p>
<p>A construção de uma <em>distribuição de frequências</em> consiste essencialmente em:</p>
<ul>
<li>escolher as <em>classes</em> ou <em>intervalos</em> (dados quantitativos) ou <em>categorias</em> (dados qualitativos);</li>
<li>separar ou enquadrar os dados nessas <em>classes</em> ou <em>categorias</em>; e,</li>
<li>contar o número de dados de cada <em>classe</em> ou <em>categoria</em>.</li>
</ul>
<p>Devemos sempre ter certeza de que cada dado (medida ou observação) se enquadre em uma, e apenas uma, <em>classe</em> ou <em>categoria</em>.</p>
<p>A literatura propõe vários modos para se determinar o número <em>k</em> de classes:</p>
<p><br />
</p>
<table>
<colgroup>
<col width="43%" />
<col width="35%" />
<col width="20%" />
</colgroup>
<thead>
<tr class="header">
<th>Crítério</th>
<th>Tamanho da amostra (<em>n</em>)</th>
<th>Fórmula</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Raiz quadrada</td>
<td>25 <span class="math inline">\(\leq\)</span> n <span class="math inline">\(\leq\)</span> 220</td>
<td>k=<span class="math inline">\(\sqrt{n}\)</span></td>
</tr>
<tr class="even">
<td>Herbert <strong>Sturges</strong> (<em>log</em>)</td>
<td>135 <span class="math inline">\(\leq\)</span> 572237</td>
<td>k=1+3,3log(n)</td>
</tr>
<tr class="odd">
<td>Giuseppe <strong>Milone</strong> (<em>ln</em>)</td>
<td>20 <span class="math inline">\(\leq 36315\)</span></td>
<td>k=-1+2ln(n)</td>
</tr>
</tbody>
</table>
<p><br />
</p>
<p>Ao se escolher um número de classes deve-se ponderar para que:</p>
<ul>
<li>os intervalos das classes tenham, geralmente, a mesma amplitude;</li>
<li>os intervalos: do limite inferior da <strong>primeira classe</strong> ao limite superior da **última classe*, devem conter todos os valores possíveis da variável;</li>
<li>cada valor observado deve pertencer apenas a uma classe;</li>
<li>não adotar um número muito elevado de classes de modo que cada classe possua poucas observações (ou mesmo nenhuma); e,</li>
<li>não adotar um número muito reduzido de classes de modo a esconder a variabilidade dos dados ao se reunir todas as observações em poucas faixas de valores.</li>
</ul>
<p>Em nosso exemplo das alturas dos estudantes, a determinação do número de classes pelo critério da <em>raiz quadrada</em> (<em>n</em>=60) sugere 8 classes:</p>
<p><span class="math display">\[\begin{align*}
k &amp; =\sqrt{n} \\
&amp; = 7,74 \\
&amp; \sim 8
\end{align*}\]</span></p>
<p>A <em>amplitude total</em> (<em>C</em>) dos valores observados, <em>ie</em>, a diferença entre o <em>valor máximo</em> (2,00 m) e o <em>valor mínimo</em> (1,41 m) será:</p>
<p><span class="math display">\[\begin{align*}
C &amp; =2,00-1,41 \\
&amp; =0,59 m
\end{align*}\]</span></p>
<p>A amplitude de cada uma das classes (<em>c</em>) será dada pelo quociente da <em>amplitude total</em> (<em>C</em>) pelo <em>número de classes</em> (<em>k</em>).</p>
<p><br />
</p>
<p><span class="math display">\[\begin{align*}
c &amp; = \frac{C}{k} \\
  &amp; = \frac{0,59}{8}\\
  &amp; = 0,07375 m
\end{align*}\]</span></p>
<p>A amplitude de cada classe é um valor fracionário que, se adotado, não irá tornar a visualização dos dados mais clara. Mesmo se adotássemos um número imediatamente maior ou menor de classes (<em>k</em>=9 ou <em>k</em>=7) esse problema persistiria.</p>
<p>Usando bom senso, adotaremos para como intervalo de classe o valor c=0,10 m e a primeira classe começando na altura de 1,40 m.
O total de 6 classes (1,40 m a 2,00 m) cobre toda faixa de variação dos valores dos dados e é de rápida assimilação pelo leitor.</p>
<p>Símbolos gráficos para intervalos:</p>
<ul>
<li>Os símbolos abaixo indicam que o valor situado à sua esquerda <strong>está incluído</strong> no intervalo e o da direita <strong>não está</strong>:</li>
</ul>
<p><span class="math display">\[
\vdash \\
{\bullet}-{\circ}
\]</span></p>
<ul>
<li>Os símbolos abaixo indicam que o valor situado à sua esquerda <strong>não está</strong> incluído no intervalo e o da direita **está incluído*:</li>
</ul>
<p><span class="math display">\[
\dashv  \\
{\circ}-{\bullet}
\]</span></p>
<p>Cada uma das classes terá os seguintes limites inferior e superior:</p>
<p><br />
</p>
<p>1,40 m <span class="math inline">\(\vdash\)</span> 1,50 m<br />
1,50 m <span class="math inline">\(\vdash\)</span> 1,60 m<br />
1,60 m <span class="math inline">\(\vdash\)</span> 1,70 m<br />
1,70 m <span class="math inline">\(\vdash\)</span> 1,80 m<br />
1,80 m <span class="math inline">\(\vdash\)</span> 1,90 m<br />
1,90 m <span class="math inline">\(\vdash\)</span> 2,00 m</p>
<p><br />
</p>
<p>Veja os dados em rol, onde a cor <font color='blue'>azul</font> indica a mudança de classe com o progredir dos valores das alturas:</p>
<p><br />
</p>
<p><font color='blue'>1,41 ; 1,44 ; 1,47 ;</font>
1,54 ; 1,55 ; 1,56 ; 1,56 ; 1,56 ; 1,57 ; 1,58 ; 1,58 ;
<font color='blue'>1,61 ; 1,62 ; 1,62 ; 1,63 ; 1,64 ;<br />
1,64 ; 1,65 ; 1,65 ; 1,65 ; 1,65 ; 1,66 ; 1,66 ; 1,66 ; 1,66 ; 1,66 ; 1,67 ; 1,67 ; 1,67 ; 1,67 ; 1,68 ; 1,68 ;<br />
1,68 ; 1,69 ;</font>
1,71 ; 1,71 ; 1,72 ; 1,72 ; 1,73 ; 1,73 ; 1,73 ; 1,73 ; 1,73 ; 1,74 ; 1,75 ; 1,76 ; 1,76 ; 1,77 ;<br />
1,78 ; 1,78 ;1,79 ; <font color='blue'>1,82 ; 1,83 ; 1,83 ; 1,84 ; 1,85 ; 1,86 ; } 1,93 ; 1,95 ; 2,00.</font></p>
<p><br />
</p>
<p>A versão mais simplificada de uma <em>tabela de distribuição de frequências</em> (o número de observações nas classes) é de fácil construção, bastando contar o número de observações em cada classe:</p>
<p><br />
</p>
<table>
<thead>
<tr class="header">
<th>Classe</th>
<th>Frequência (<span class="math inline">\(n_{i}\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1,40 m <span class="math inline">\(\vdash\)</span> 1,50 m</td>
<td>3</td>
</tr>
<tr class="even">
<td>1,50 m <span class="math inline">\(\vdash\)</span> 1,60 m</td>
<td>8</td>
</tr>
<tr class="odd">
<td>1,60 m <span class="math inline">\(\vdash\)</span> 1,70 m</td>
<td>23</td>
</tr>
<tr class="even">
<td>1,70 m <span class="math inline">\(\vdash\)</span> 1,80 m</td>
<td>17</td>
</tr>
<tr class="odd">
<td>1,80 m <span class="math inline">\(\vdash\)</span> 1,90 m</td>
<td>6</td>
</tr>
<tr class="even">
<td>1,90 m <span class="math inline">\(\vdash\)</span> 2,00 m</td>
<td>3</td>
</tr>
<tr class="odd">
<td>Total</td>
<td>60</td>
</tr>
</tbody>
</table>
<p><br />
</p>
<p><em>Tabelas de distribuição de frequências</em> mais completas podem montadas agregando muitas informações adicionais em novas colunas.</p>
<p>Essas informações servem para tornar a visualização mais imediata e muitas delas são obtidas com operações matemáticas elementares:</p>
<p><br />
</p>
<ul>
<li>Classe <em>i</em>: é a simples identificação de cada classe;</li>
<li>Amplitude (<span class="math inline">\(\Delta_{i}\)</span>) da classe <span class="math inline">\(i\)</span>: a diferença entre o valor do limite superior e o do inferior de cada classe;</li>
<li>Intervalo de valores da classe <span class="math inline">\(i\)</span> (onde seu limite inferior <strong>está contido</strong> e o limite superior <strong>não está contido</strong>);</li>
<li>Valor médio (<span class="math inline">\(\stackrel{-}{x}_{i}\)</span>) de cada classe <span class="math inline">\(i\)</span>: a média aritmética entre os valores dos limites inferior e superior da classa considerada;</li>
<li>Frequência absoluta (<span class="math inline">\(f_{i}\)</span>) da classe <span class="math inline">\(i\)</span>: o número de observações contidas no intervalo da classe considerada;</li>
<li>Frequência relativa (<span class="math inline">\(fr_{i}= \frac{f_{i}}{N}\)</span>) da classe <span class="math inline">\(i\)</span> (ou frequência relativa percentual, se assim apresentada): o quociente do número de observações contidas no intervalo da classe (<span class="math inline">\(f_{i}\)</span>) pelo número total de observações (<span class="math inline">\(N\)</span>);</li>
<li>Frequência acumulada (<span class="math inline">\(fac_{i}\)</span>) da classe <span class="math inline">\(i\)</span> (ou frequência acumulada percentual, se assim apresentada): o número de observações com medidas contidas na classe <span class="math inline">\(i\)</span> e nas anteriores a ela;</li>
<li>Densidade (<span class="math inline">\(\delta_{i}=\frac{f_{i}}{\Delta_{i}}\)</span>): o quociente do número de observações da classe (<span class="math inline">\(f_{i}\)</span>) pela sua amplitude (<span class="math inline">\(\Delta_{i}\)</span>);</li>
<li>Densidade <span class="math inline">\(\delta_{fr_{i}}=\frac{fr_{i}}{\Delta_{i}}\)</span>: o quociente da frequência relativa (<span class="math inline">\(fr_{i}\)</span>) pela amplitude (<span class="math inline">\(\Delta_{i}\)</span>) da classe.</li>
</ul>
<p><br />
</p>
<p>Vejo como exemplo as tabelas abaixo:</p>
<p><br />
</p>
<table>
<colgroup>
<col width="5%" />
<col width="15%" />
<col width="18%" />
<col width="8%" />
<col width="11%" />
<col width="13%" />
<col width="12%" />
<col width="13%" />
</colgroup>
<thead>
<tr class="header">
<th>Classe</th>
<th>Int. de valores</th>
<th>Alt. média</th>
<th>Freq.</th>
<th>Freq. relativa</th>
<th>Freq. rel. (%)</th>
<th>Freq. acumulada</th>
<th>Freq. acum. (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td></td>
<td>(<span class="math inline">\(\stackrel{-}{x}_{i}\)</span>)</td>
<td>(<span class="math inline">\(f_{i}\)</span>)</td>
<td>(<span class="math inline">\(fr_{i}\)</span>)</td>
<td>(<span class="math inline">\(fr_{i}\%\)</span>)</td>
<td>(<span class="math inline">\(fac_{i}\)</span>)</td>
<td>(<span class="math inline">\(fac_{i}\%\)</span>)</td>
</tr>
<tr class="even">
<td>1</td>
<td>1,40 <span class="math inline">\(\vdash\)</span> 1,50</td>
<td>1,45</td>
<td>3</td>
<td>0,05</td>
<td>5</td>
<td>3</td>
<td>5</td>
</tr>
<tr class="odd">
<td>2</td>
<td>1,50 <span class="math inline">\(\vdash\)</span> 1,60</td>
<td>1,55</td>
<td>8</td>
<td>0,13</td>
<td>13,33</td>
<td>11</td>
<td>18,33</td>
</tr>
<tr class="even">
<td>3</td>
<td>1,60 <span class="math inline">\(\vdash\)</span> 1,70</td>
<td>1,65</td>
<td>23</td>
<td>0,38</td>
<td>38,34</td>
<td>34</td>
<td>56,57</td>
</tr>
<tr class="odd">
<td>4</td>
<td>1,70 <span class="math inline">\(\vdash\)</span> 1,80</td>
<td>1,75</td>
<td>17</td>
<td>0,28</td>
<td>28,33</td>
<td>51</td>
<td>84,87</td>
</tr>
<tr class="even">
<td>5</td>
<td>1,80 <span class="math inline">\(\vdash\)</span> 1,90</td>
<td>1,85</td>
<td>6</td>
<td>0,10</td>
<td>10</td>
<td>57</td>
<td>94,57</td>
</tr>
<tr class="odd">
<td>6</td>
<td>1,90 <span class="math inline">\(\vdash\)</span> 2,00</td>
<td>1,95</td>
<td>3</td>
<td>0,05</td>
<td>5</td>
<td>60</td>
<td>99,87</td>
</tr>
<tr class="even">
<td>Totais</td>
<td>-</td>
<td></td>
<td>60</td>
<td>1,00</td>
<td>100,00</td>
<td>-</td>
<td>-</td>
</tr>
</tbody>
</table>
<p><br />
</p>
<table>
<colgroup>
<col width="7%" />
<col width="19%" />
<col width="10%" />
<col width="14%" />
<col width="14%" />
<col width="11%" />
<col width="21%" />
</colgroup>
<thead>
<tr class="header">
<th>Classe</th>
<th>Int. de valores</th>
<th>Freq.</th>
<th>Amplitude</th>
<th>Densidade</th>
<th>Freq. rel.</th>
<th>Dens. da freq. rel.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td></td>
<td>(<span class="math inline">\(f_{i}\)</span>)</td>
<td>(<span class="math inline">\(\Delta_{i}\)</span>)</td>
<td>(<span class="math inline">\(\delta_{i}\)</span>)</td>
<td>(<span class="math inline">\(fr_{i}\)</span>)</td>
<td>(<span class="math inline">\(\delta_{fr_{i}}\)</span>)</td>
</tr>
<tr class="even">
<td>1</td>
<td>1,40 <span class="math inline">\(\vdash\)</span> 1,50</td>
<td>3</td>
<td>0,10</td>
<td>30</td>
<td>0,05</td>
<td>0,5</td>
</tr>
<tr class="odd">
<td>2</td>
<td>1,50 <span class="math inline">\(\vdash\)</span> 1,60</td>
<td>8</td>
<td>0,10</td>
<td>80</td>
<td>0,13</td>
<td>1,33</td>
</tr>
<tr class="even">
<td>3</td>
<td>1,60 <span class="math inline">\(\vdash\)</span> 1,70</td>
<td>23</td>
<td>0,10</td>
<td>230</td>
<td>0,39</td>
<td>3,83</td>
</tr>
<tr class="odd">
<td>4</td>
<td>1,70 <span class="math inline">\(\vdash\)</span> 1,80</td>
<td>17</td>
<td>0,10</td>
<td>170</td>
<td>0,28</td>
<td>2,83</td>
</tr>
<tr class="even">
<td>5</td>
<td>1,80 <span class="math inline">\(\vdash\)</span> 1,90</td>
<td>6</td>
<td>0,10</td>
<td>60</td>
<td>0,10</td>
<td>1</td>
</tr>
<tr class="odd">
<td>6</td>
<td>1,90 <span class="math inline">\(\vdash\)</span> 2,00</td>
<td>3</td>
<td>0,10</td>
<td>30</td>
<td>0,05</td>
<td>0,5</td>
</tr>
<tr class="even">
<td>Totais</td>
<td>-</td>
<td>60</td>
<td>-</td>
<td>-</td>
<td>1,00</td>
<td>-</td>
</tr>
</tbody>
</table>
<p><br />
</p>
<div id="média-1" class="section level3 hasAnchor" number="3.6.1">
<h3><span class="header-section-number">3.6.1</span> Média<a href="descritiva.html#média-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><br />
</p>
<p>Nas tabelas de <em>distribuições de frequências</em> os resultados estão agrupados em <em>intervalos de classes (<span class="math inline">\(i\)</span>)</em>. Por essa razão, os dados perdem sua identidade individual e passam a se representados pelo valor médio de cada intervalo (<span class="math inline">\(\stackrel{-}{x}_{i}\)</span>).</p>
<p>A média será então dada pelo produto deste valor médio de cada intervalo (<span class="math inline">\(\stackrel{-}{x}_{i}\)</span>) pela frequência absoluta que ele apresentou (<span class="math inline">\({n}_{i}\)</span>), dividido pela quantidade de dados (<span class="math inline">\(N\)</span>).</p>
<p>Sejam <span class="math inline">\(n_{1}, n_{2}, ..., n_{n}\)</span> as frequências apresentadas para cada intervalo <span class="math inline">\(i\)</span> dos valores assumidos pela variável <span class="math inline">\(X\)</span> para o total <span class="math inline">\(N\)</span> de observações. Assim a <em>média aritmética simples</em> para dados agrupados será dada por:</p>
<p><br />
</p>
<p><span class="math display">\[
\stackrel{-}{x}=\frac{\sum _{i=1}^{n}{n}_{i}\cdot{\stackrel{-}{x}}_{i}}{N}
\]</span><br />
</p>
</div>
<div id="moda-1" class="section level3 hasAnchor" number="3.6.2">
<h3><span class="header-section-number">3.6.2</span> Moda<a href="descritiva.html#moda-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><br />
</p>
<p>Moda para dados apresentados na forma de uma distribuição de frequências:</p>
<p><span class="math display">\[
Mo = l_{inf} + (\frac{\Delta_{1}}{\Delta_{1} + \Delta_{2}}) \times \Delta_{i}
\]</span><br />
<br />
</p>
<p>onde:</p>
<ul>
<li><span class="math inline">\(l_{inf}\)</span>: limite inferior da classe modal, <strong>a classe de maior frequência absoluta</strong>;</li>
<li><span class="math inline">\(\Delta_{1}\)</span> frequência absoluta da <strong>classe modal</strong> menos a frequência absoluta da <strong>classe anterior</strong>;</li>
<li><span class="math inline">\(\Delta_{2}\)</span> frequência absoluta da <strong>classe modal</strong> menos a frequência absoluta da <strong>classe posterior</strong>; e,</li>
<li><span class="math inline">\(\Delta_{i}\)</span> é o intervalo de cada classe.</li>
</ul>
</div>
<div id="variância" class="section level3 hasAnchor" number="3.6.3">
<h3><span class="header-section-number">3.6.3</span> Variância<a href="descritiva.html#variância" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><br />
</p>
<p>Variância para dados agrupados:</p>
<p><span class="math display">\[
S^{2}= \frac{1}{n-1} \times \left[  \sum _{i=1}^{n}{(\stackrel{-}{x}}_{i})^{2} \cdot {n}_{i} - \frac{{\left(\sum _{i=1}^{n}{\stackrel{-}{x}}_{i} \cdot {n}_{i}\right)}^{2}  }{n}\right]
\]</span></p>
<p>Onde:</p>
<ul>
<li><span class="math inline">\(n_{i}\)</span> é a frequência absoluta em cada classe <span class="math inline">\(i\)</span>; e,</li>
<li><span class="math inline">\(\stackrel{-}{x}_{i}\)</span> é o valor médio de cada classe <span class="math inline">\(i\)</span>.</li>
</ul>
</div>
<div id="histograma" class="section level3 hasAnchor" number="3.6.4">
<h3><span class="header-section-number">3.6.4</span> Histograma<a href="descritiva.html#histograma" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Um <em>histograma</em> é a representação gráfica de uma <em>tabela de distribuição de frequências</em> em colunas (retângulos).</p>
<p>A base de cada retângulo representa o intervalo de cada classe e a altura, a quantidade ou a <em>frequência absoluta</em> com que aquele valor da classe ocorre no conjunto de dados.</p>
<p>O termo <em>histograma</em> foi cunhado por Karl Pearson (c. 1891) e vem da composição em grego de <em>istos</em> (mastro) com <em>gramma</em> (escrita), convertida em inglês para <em>historical diagram: histogram</em>.</p>
<p>Como elemento gráfico, seu uso é anterior à sua denominação (maiores detalhes em:
<a href="https://www.ine.es/ss/Satellite?blobcol=urldata&amp;blobheader=application%2Fpdf&amp;blobheadername1=Content-Disposition&amp;blobheadervalue1=attachment%3B+filename%3Dart_192_2.pdf&amp;blobkey=urldata&amp;blobtable=MungoBlobs&amp;blobwhere=229%2F670%2Fart_192_2.pdf&amp;ssbinary=true">(link)</a> ).</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="descritiva.html#cb47-1" aria-hidden="true" tabindex="-1"></a>h1<span class="ot">=</span><span class="fu">hist</span>(alturas, <span class="at">breaks=</span><span class="fu">seq</span>(<span class="fl">1.30</span> , <span class="fl">2.10</span> , <span class="fl">0.10</span>), <span class="at">main=</span> <span class="st">&quot;Histograma das alturas dos estudantes&quot;</span>, <span class="at">col=</span><span class="st">&quot;blue&quot;</span>, </span>
<span id="cb47-2"><a href="descritiva.html#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="at">xlab=</span><span class="st">&quot;Classes de altura (m)&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Frequência observada (un)&quot;</span> , <span class="at">cex=</span><span class="fl">0.7</span>, <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">30</span>))</span>
<span id="cb47-3"><a href="descritiva.html#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(h1<span class="sc">$</span>mids,h1<span class="sc">$</span>counts,<span class="at">labels=</span>h1<span class="sc">$</span>counts, <span class="at">adj=</span><span class="fu">c</span>(<span class="fl">0.5</span>, <span class="sc">-</span><span class="fl">0.5</span>))</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-54"></span>
<img src="_main_files/figure-html/unnamed-chunk-54-1.png" alt="Histograma das alturas dos estudantes. Uma barra para cada classe de altura  e sua altura expressando a quantidade de observações com valores dentro dessa classe (intencionalmente criamos duas classe sem nenhuma observação)" width="672" />
<p class="caption">
Figure 3.16: Histograma das alturas dos estudantes. Uma barra para cada classe de altura e sua altura expressando a quantidade de observações com valores dentro dessa classe (intencionalmente criamos duas classe sem nenhuma observação)
</p>
</div>
<p>As informações da <em>Tabela de distribuição de frequências</em> dão origem a variados tipos de histogramas, como aquele feito com as frequências relativas:</p>
<p><br />
</p>
<p>Num histograma de densidade, a altura de cada retângulo representa a densidade da ocorrência da <em>frequência relativa</em>.</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="descritiva.html#cb48-1" aria-hidden="true" tabindex="-1"></a>h2<span class="ot">=</span><span class="fu">hist</span>(alturas,<span class="at">breaks=</span><span class="fu">seq</span>(<span class="fl">1.30</span> , <span class="fl">2.10</span> , <span class="fl">0.10</span>), <span class="at">main=</span> <span class="st">&quot;Histograma das alturas dos estudantes&quot;</span>, <span class="at">col=</span><span class="st">&quot;blue&quot;</span>, </span>
<span id="cb48-2"><a href="descritiva.html#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="at">xlab=</span><span class="st">&quot;Classes de alturas (m)&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Frequência relativa observada&quot;</span>, <span class="at">prob=</span><span class="st">&quot;TRUE&quot;</span>, <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">5</span>))</span>
<span id="cb48-3"><a href="descritiva.html#cb48-3" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(h2<span class="sc">$</span>mids,h2<span class="sc">$</span>density,<span class="at">labels=</span><span class="fu">round</span>(h2<span class="sc">$</span>density, <span class="dv">5</span>), <span class="at">adj=</span><span class="fu">c</span>(<span class="fl">0.5</span>, <span class="sc">-</span><span class="fl">0.5</span>), <span class="at">cex=</span><span class="fl">0.7</span>)</span>
<span id="cb48-4"><a href="descritiva.html#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">density</span>(alturas), <span class="at">col=</span><span class="st">&quot;red&quot;</span>)             </span>
<span id="cb48-5"><a href="descritiva.html#cb48-5" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">density</span>(alturas, <span class="at">adjust=</span><span class="dv">2</span>), <span class="at">lty=</span><span class="st">&quot;dotted&quot;</span>)  </span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-55"></span>
<img src="_main_files/figure-html/unnamed-chunk-55-1.png" alt="A linha vermelha é uma aproximação da Função de Densidade da frequência relativa de observação (a linhe preta é a curva da função densidade de uma distribuição Normal com média e variâncias dadas pelos dados" width="672" />
<p class="caption">
Figure 3.17: A linha vermelha é uma aproximação da Função de Densidade da frequência relativa de observação (a linhe preta é a curva da função densidade de uma distribuição Normal com média e variâncias dadas pelos dados
</p>
</div>
<p><br />
</p>
<p>Uma aproximação para a <strong>área sob a curva da Função de Densidade</strong> pode ser soma das áreas de cada retângulo, onde cada um deles tem:</p>
<ul>
<li>Base = <span class="math inline">\(\Delta_{i}\)</span>; e,\</li>
<li>Altura = Densidade da proporção= <span class="math inline">\(\frac{f_{i}}{\Delta_{i}}\)</span>.</li>
</ul>
<p>Portanto, a área de cada retângulo é igual à proporção (<span class="math inline">\(f_{i}\)</span>) da classe (<span class="math inline">\(i\)</span>) e, assim, a soma de todas essas áreas será igual a 1:</p>
<p><br />
</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="descritiva.html#cb49-1" aria-hidden="true" tabindex="-1"></a>(<span class="fl">0.10</span><span class="sc">*</span><span class="fl">0.5</span>)<span class="sc">+</span>(<span class="fl">0.10</span><span class="sc">*</span><span class="fl">1.333</span>)<span class="sc">+</span>(<span class="fl">0.10</span><span class="sc">*</span><span class="fl">3.833</span>)<span class="sc">+</span>(<span class="fl">0.10</span><span class="sc">*</span><span class="fl">2.833</span>)<span class="sc">+</span>(<span class="fl">0.10</span><span class="sc">*</span><span class="dv">1</span>)<span class="sc">+</span>(<span class="fl">0.10</span><span class="sc">*</span><span class="fl">0.50</span>)</span></code></pre></div>
<pre><code>## [1] 0.9999</code></pre>
<p><br />
</p>
<p>A <strong>área da curva da Função de Densidade delimitada por dois valores quaisquer</strong> é uma analogia para a probabilidade de que um determinado valor de altura de um estudante (amostrado aleatoriamente dentre todos os 60 estudantes) esteja contida nesse intervalo.</p>
<p><strong>Equivale dizer que</strong>, amostrando-se aleatoriamente um estudante dentre todos os 60 alunos, a probabilidade de que a altura desse estudante estaje contida entre os valores mínimo e máximo da amostra é, <strong>naturalmente</strong>, igual a 1 (100%)</p>
<p><br />
</p>
</div>
</div>
<div id="apresentação-tabular-de-dados-qualitativos" class="section level2 hasAnchor" number="3.7">
<h2><span class="header-section-number">3.7</span> Apresentação tabular de dados qualitativos<a href="descritiva.html#apresentação-tabular-de-dados-qualitativos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Frequentemente pesquisas são conduzidas tendo por base respostas de natureza binária como, por exemplo:</p>
<ul>
<li>sim ou não;</li>
<li>gosto ou não gosto;</li>
<li>voto em “A” ou voto em “B”; ou,</li>
<li>concordo ou não concordo.</li>
</ul>
<p>Como resultado final, são obtidas proporções que expressam a frequência absoluta com que cada uma dessas variáveis (ou seus níveis) foi observada em relação ao total estudado.</p>
<p>Para essas situações, variados tipos de apresentações tabulares podem ser produzidos como a tabela abaixo, onde são apresentadas as proporções observadas de cada nível da variável estudada (“tipo de família”, com quatro níveis diferentes), de um levantamento amostral feito pela Agência do Censo dos Estados Unidos em 2005.</p>
<p><br />
</p>
<table style="width:100%;">
<colgroup>
<col width="33%" />
<col width="25%" />
<col width="16%" />
<col width="25%" />
</colgroup>
<thead>
<tr class="header">
<th>Tipo de família</th>
<th>Número (milhões)</th>
<th>Freq. abs.</th>
<th>Freq. rel. (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Casal com filhos</td>
<td>24,1</td>
<td>0,22</td>
<td>22</td>
</tr>
<tr class="even">
<td>Casal sem filhos</td>
<td>31,1</td>
<td>0,28</td>
<td>28</td>
</tr>
<tr class="odd">
<td>Solteiro, sem parceiro</td>
<td>19,1</td>
<td>0,17</td>
<td>17</td>
</tr>
<tr class="even">
<td>Morando sozinho</td>
<td>30,1</td>
<td>0,27</td>
<td>27</td>
</tr>
<tr class="odd">
<td>Outros domicílios</td>
<td>6,7</td>
<td>0,06</td>
<td>6</td>
</tr>
</tbody>
</table>
<p>A apresentação gráfica desses dados pode feita, por exemplo, por um <em>Gráfico de colunas</em> ou um <em>Gráfico de setores</em>.</p>
<p><br />
</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="descritiva.html#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb51-2"><a href="descritiva.html#cb51-2" aria-hidden="true" tabindex="-1"></a>dados<span class="ot">=</span><span class="fu">data.frame</span>(<span class="at">tipo=</span><span class="fu">c</span>(<span class="st">&quot;Casal com filhos&quot;</span>,</span>
<span id="cb51-3"><a href="descritiva.html#cb51-3" aria-hidden="true" tabindex="-1"></a>                          <span class="st">&quot;Casal sem filhos&quot;</span>,</span>
<span id="cb51-4"><a href="descritiva.html#cb51-4" aria-hidden="true" tabindex="-1"></a>                          <span class="st">&quot;Solteiro, s/parceiro&quot;</span>,</span>
<span id="cb51-5"><a href="descritiva.html#cb51-5" aria-hidden="true" tabindex="-1"></a>                          <span class="st">&quot;Morando sozinho&quot;</span>,</span>
<span id="cb51-6"><a href="descritiva.html#cb51-6" aria-hidden="true" tabindex="-1"></a>                          <span class="st">&quot;Outros domicíclios&quot;</span>),</span>
<span id="cb51-7"><a href="descritiva.html#cb51-7" aria-hidden="true" tabindex="-1"></a>                 <span class="at">quant=</span><span class="fu">c</span>(<span class="fl">24.1</span>, <span class="fl">31.1</span>, </span>
<span id="cb51-8"><a href="descritiva.html#cb51-8" aria-hidden="true" tabindex="-1"></a>                       <span class="fl">19.1</span>, <span class="fl">30.1</span>,</span>
<span id="cb51-9"><a href="descritiva.html#cb51-9" aria-hidden="true" tabindex="-1"></a>                       <span class="fl">6.7</span>))</span>
<span id="cb51-10"><a href="descritiva.html#cb51-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-11"><a href="descritiva.html#cb51-11" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dados, <span class="fu">aes</span>(<span class="at">x=</span>tipo, <span class="at">y=</span>quant, <span class="at">color=</span>tipo)) <span class="sc">+</span></span>
<span id="cb51-12"><a href="descritiva.html#cb51-12" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_bar</span>(<span class="at">stat=</span><span class="st">&quot;identity&quot;</span>, <span class="at">position=</span><span class="fu">position_dodge</span>())<span class="sc">+</span></span>
<span id="cb51-13"><a href="descritiva.html#cb51-13" aria-hidden="true" tabindex="-1"></a><span class="fu">ggtitle</span>(<span class="st">&quot;Estrutura domiciliar dos Estados Unidos, 2005&quot;</span>) <span class="sc">+</span></span>
<span id="cb51-14"><a href="descritiva.html#cb51-14" aria-hidden="true" tabindex="-1"></a><span class="fu">theme</span>(<span class="at">legend.position=</span><span class="st">&quot;bottom&quot;</span>)<span class="sc">+</span></span>
<span id="cb51-15"><a href="descritiva.html#cb51-15" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label=</span>quant), <span class="at">vjust=</span><span class="fl">1.6</span>, <span class="at">color=</span><span class="st">&quot;white&quot;</span>, <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="fl">0.9</span>), <span class="at">size=</span><span class="fl">3.5</span>)<span class="sc">+</span></span>
<span id="cb51-16"><a href="descritiva.html#cb51-16" aria-hidden="true" tabindex="-1"></a><span class="fu">scale_fill_brewer</span>(<span class="at">palette=</span><span class="st">&quot;Paired&quot;</span>)<span class="sc">+</span></span>
<span id="cb51-17"><a href="descritiva.html#cb51-17" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_minimal</span>()<span class="sc">+</span></span>
<span id="cb51-18"><a href="descritiva.html#cb51-18" aria-hidden="true" tabindex="-1"></a><span class="fu">xlab</span>(<span class="st">&quot;&quot;</span>)  <span class="sc">+</span></span>
<span id="cb51-19"><a href="descritiva.html#cb51-19" aria-hidden="true" tabindex="-1"></a><span class="fu">ylab</span>(<span class="st">&quot;Frequência absoluta observada (milhões)&quot;</span>)<span class="sc">+</span></span>
<span id="cb51-20"><a href="descritiva.html#cb51-20" aria-hidden="true" tabindex="-1"></a><span class="fu">labs</span>(<span class="at">colour =</span> <span class="st">&quot;Tipos de domicílios&quot;</span>) </span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-57"></span>
<img src="_main_files/figure-html/unnamed-chunk-57-1.png" alt="Gráfico de barras" width="672" />
<p class="caption">
Figure 3.18: Gráfico de barras
</p>
</div>
<p><br />
</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="descritiva.html#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb52-2"><a href="descritiva.html#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span>
<span id="cb52-3"><a href="descritiva.html#cb52-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-4"><a href="descritiva.html#cb52-4" aria-hidden="true" tabindex="-1"></a>blank_theme<span class="ot">=</span><span class="fu">theme_minimal</span>()<span class="sc">+</span></span>
<span id="cb52-5"><a href="descritiva.html#cb52-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb52-6"><a href="descritiva.html#cb52-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb52-7"><a href="descritiva.html#cb52-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb52-8"><a href="descritiva.html#cb52-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.border =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb52-9"><a href="descritiva.html#cb52-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid=</span><span class="fu">element_blank</span>(),</span>
<span id="cb52-10"><a href="descritiva.html#cb52-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.ticks =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb52-11"><a href="descritiva.html#cb52-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title=</span><span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">14</span>, <span class="at">face=</span><span class="st">&quot;bold&quot;</span>)</span>
<span id="cb52-12"><a href="descritiva.html#cb52-12" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb52-13"><a href="descritiva.html#cb52-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-14"><a href="descritiva.html#cb52-14" aria-hidden="true" tabindex="-1"></a>bp<span class="ot">=</span><span class="fu">ggplot</span>(dados, <span class="fu">aes</span>(<span class="at">x=</span><span class="st">&quot;&quot;</span>, <span class="at">y=</span>quant, <span class="at">fill=</span>tipo))<span class="sc">+</span></span>
<span id="cb52-15"><a href="descritiva.html#cb52-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">width =</span> <span class="dv">1</span>, <span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>)</span>
<span id="cb52-16"><a href="descritiva.html#cb52-16" aria-hidden="true" tabindex="-1"></a>pie<span class="ot">=</span>bp <span class="sc">+</span> <span class="fu">coord_polar</span>(<span class="st">&quot;y&quot;</span>, <span class="at">start=</span><span class="dv">0</span>)</span>
<span id="cb52-17"><a href="descritiva.html#cb52-17" aria-hidden="true" tabindex="-1"></a>pie <span class="sc">+</span> </span>
<span id="cb52-18"><a href="descritiva.html#cb52-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="st">&quot;Blues&quot;</span>)<span class="sc">+</span></span>
<span id="cb52-19"><a href="descritiva.html#cb52-19" aria-hidden="true" tabindex="-1"></a>  blank_theme <span class="sc">+</span></span>
<span id="cb52-20"><a href="descritiva.html#cb52-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x=</span><span class="fu">element_blank</span>()) <span class="sc">+</span></span>
<span id="cb52-21"><a href="descritiva.html#cb52-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">x =</span>  <span class="fl">1.2</span>,<span class="at">label =</span> quant), <span class="at">position =</span> <span class="fu">position_stack</span>(<span class="at">vjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb52-22"><a href="descritiva.html#cb52-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Estrutura domiciliar dos Estados Unidos, 2005&quot;</span>) <span class="sc">+</span></span>
<span id="cb52-23"><a href="descritiva.html#cb52-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;right&quot;</span>, <span class="at">legend.justification =</span> <span class="st">&quot;center&quot;</span>, <span class="at">legend.direction =</span> <span class="st">&quot;vertical&quot;</span>,</span>
<span id="cb52-24"><a href="descritiva.html#cb52-24" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.spacing.x =</span> <span class="fu">unit</span>(<span class="fl">0.5</span>, <span class="st">&#39;cm&#39;</span>),<span class="at">legend.spacing.y =</span> <span class="fu">unit</span>(<span class="fl">0.5</span>, <span class="st">&#39;cm&#39;</span>))<span class="sc">+</span></span>
<span id="cb52-25"><a href="descritiva.html#cb52-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill =</span> <span class="fu">guide_legend</span>(<span class="at">title =</span> <span class="st">&quot;Tipos de domicílios&quot;</span>,</span>
<span id="cb52-26"><a href="descritiva.html#cb52-26" aria-hidden="true" tabindex="-1"></a>                             <span class="at">label.position =</span> <span class="st">&quot;right&quot;</span>,</span>
<span id="cb52-27"><a href="descritiva.html#cb52-27" aria-hidden="true" tabindex="-1"></a>                             <span class="at">title.position =</span> <span class="st">&quot;top&quot;</span>, <span class="at">title.vjust =</span> <span class="dv">1</span>)) </span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-58"></span>
<img src="_main_files/figure-html/unnamed-chunk-58-1.png" alt="Gráfico de setores" width="672" />
<p class="caption">
Figure 3.19: Gráfico de setores
</p>
</div>
<p><br />
</p>
<p>Outro tipo de apresentação tabular de dados qualitativos são as <em>Tabelas de Contingência</em>.</p>
<p>As tabelas de contingência são usadas para associar duas ou mais variáveis qualitativas (ou seus níveis) às respostas obtidas, na forma das frequências absoluta e relativa observadas em cada uma dessas variáveis (ou seus níveis).</p>
<p>O uso desse tipo de tabela é comum quando se pretende investigar se as variáveis estudadas têm alguma associação por meio de testes não paramétricos. Esse tipo de apresentação facilita a extração de informações relacionadas às probabilidades marginais ou condicionadas de cada uma variáveis ou seus níveis.</p>
<p><br />
</p>
<table>
<colgroup>
<col width="35%" />
<col width="31%" />
<col width="32%" />
</colgroup>
<thead>
<tr class="header">
<th>Inclinação partidária</th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>Democrata</td>
<td>Republicano</td>
</tr>
<tr class="even">
<td>Casal com filhos</td>
<td>762</td>
<td>468</td>
</tr>
<tr class="odd">
<td>Casal sem filhos</td>
<td>484</td>
<td>477</td>
</tr>
<tr class="even">
<td>Total</td>
<td>1246</td>
<td>945</td>
</tr>
<tr class="odd">
<td>———————–</td>
<td>——————–</td>
<td>———————</td>
</tr>
</tbody>
</table>
<p><br />
</p>
<table>
<colgroup>
<col width="26%" />
<col width="28%" />
<col width="26%" />
<col width="19%" />
</colgroup>
<thead>
<tr class="header">
<th>Inclinação partidária</th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>Democrata (milhões)</td>
<td>Republicano (milhões)</td>
<td>Total (milhões)</td>
</tr>
<tr class="even">
<td>Casal com filhos</td>
<td>18,0</td>
<td>6,1</td>
<td>24,1</td>
</tr>
<tr class="odd">
<td>Casal sem filhos</td>
<td>29,1</td>
<td>2,0</td>
<td>31,1</td>
</tr>
<tr class="even">
<td>Total</td>
<td>47,1</td>
<td>8,1</td>
<td>55,2</td>
</tr>
</tbody>
</table>
<p>As representações gráficas são análogas às mostradas no exemplo anterior.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="conceitos_gerais.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="probabilidade.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/03-descritiva.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
