<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>3.3 Sínteses numéricas descritivas | apostila.knit</title>
  <meta name="description" content="Apostila com alguns tópicos de estatística e probabilidade." />
  <meta name="generator" content="bookdown 0.34 and GitBook 2.6.7" />

  <meta property="og:title" content="3.3 Sínteses numéricas descritivas | apostila.knit" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="https://fjrcosta.github.io/apostila/images/logo-uel.png" />
  <meta property="og:description" content="Apostila com alguns tópicos de estatística e probabilidade." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="3.3 Sínteses numéricas descritivas | apostila.knit" />
  
  <meta name="twitter:description" content="Apostila com alguns tópicos de estatística e probabilidade." />
  <meta name="twitter:image" content="https://fjrcosta.github.io/apostila/images/logo-uel.png" />




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="dados-brutos-em-rol-diagrama-de-ramos-folhas-e-de-dispersão-unidimensional.html"/>
<link rel="next" href="medidas-de-forma-assimetria-curtose.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Índice</a></li>

<li class="divider"></li>
<li><a href="index.html#section" id="toc-section"></a></li>
<li class="chapter" data-level="1" data-path="introdução-histórica-da-estatística.html"><a href="introdução-histórica-da-estatística.html"><i class="fa fa-check"></i><b>1</b> Introdução histórica da estatística</a>
<ul>
<li class="chapter" data-level="1.1" data-path="primeiros-levantamentos-estudos-e-publicações-demografia-e-aritmética-política.html"><a href="primeiros-levantamentos-estudos-e-publicações-demografia-e-aritmética-política.html"><i class="fa fa-check"></i><b>1.1</b> Primeiros levantamentos, estudos e publicações &amp; Demografia e aritmética política</a></li>
<li class="chapter" data-level="1.2" data-path="visualização-de-dados-estudos-e-primeiras-publicações.html"><a href="visualização-de-dados-estudos-e-primeiras-publicações.html"><i class="fa fa-check"></i><b>1.2</b> Visualização de dados &amp; Estudos e primeiras publicações</a></li>
<li class="chapter" data-level="1.3" data-path="nomes-notáveis.html"><a href="nomes-notáveis.html"><i class="fa fa-check"></i><b>1.3</b> Nomes notáveis</a></li>
<li class="chapter" data-level="1.4" data-path="revista-biometrika.html"><a href="revista-biometrika.html"><i class="fa fa-check"></i><b>1.4</b> Revista Biometrika</a></li>
<li class="chapter" data-level="1.5" data-path="eugenia.html"><a href="eugenia.html"><i class="fa fa-check"></i><b>1.5</b> Eugenia</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="introdução-conceitual-essencial.html"><a href="introdução-conceitual-essencial.html"><i class="fa fa-check"></i><b>2</b> Introdução conceitual essencial</a>
<ul>
<li class="chapter" data-level="2.1" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html"><i class="fa fa-check"></i><b>2.1</b> Estatística descritiva</a></li>
<li class="chapter" data-level="2.2" data-path="estatística-inferencial.html"><a href="estatística-inferencial.html"><i class="fa fa-check"></i><b>2.2</b> Estatística inferencial</a></li>
<li class="chapter" data-level="2.3" data-path="produção-de-conhecimento.html"><a href="produção-de-conhecimento.html"><i class="fa fa-check"></i><b>2.3</b> Produção de conhecimento</a></li>
<li class="chapter" data-level="2.4" data-path="população-universo-amostra.html"><a href="população-universo-amostra.html"><i class="fa fa-check"></i><b>2.4</b> População (universo) &amp; amostra</a></li>
<li class="chapter" data-level="2.5" data-path="parâmetros-e-estatísticas.html"><a href="parâmetros-e-estatísticas.html"><i class="fa fa-check"></i><b>2.5</b> Parâmetros e estatísticas</a></li>
<li class="chapter" data-level="2.6" data-path="tipos-de-variáveis.html"><a href="tipos-de-variáveis.html"><i class="fa fa-check"></i><b>2.6</b> Tipos de variáveis</a></li>
<li class="chapter" data-level="2.7" data-path="indexação-de-dados-i.html"><a href="indexação-de-dados-i.html"><i class="fa fa-check"></i><b>2.7</b> Indexação de dados (<span class="math inline">\(i\)</span>)</a></li>
<li class="chapter" data-level="2.8" data-path="noções-básicas-sobre-somatórios-sigma.html"><a href="noções-básicas-sobre-somatórios-sigma.html"><i class="fa fa-check"></i><b>2.8</b> Noções básicas sobre somatórios (<span class="math inline">\(\Sigma\)</span>)</a></li>
<li class="chapter" data-level="2.9" data-path="análise-combinatória-diagramas-de-árvore-permutações-arranjos-combinações.html"><a href="análise-combinatória-diagramas-de-árvore-permutações-arranjos-combinações.html"><i class="fa fa-check"></i><b>2.9</b> Análise combinatória: diagramas de árvore, permutações (arranjos) &amp; combinações</a>
<ul>
<li class="chapter" data-level="2.9.1" data-path="análise-combinatória-diagramas-de-árvore-permutações-arranjos-combinações.html"><a href="análise-combinatória-diagramas-de-árvore-permutações-arranjos-combinações.html#permutações-ou-arranjos"><i class="fa fa-check"></i><b>2.9.1</b> Permutações ou arranjos</a></li>
<li class="chapter" data-level="2.9.2" data-path="análise-combinatória-diagramas-de-árvore-permutações-arranjos-combinações.html"><a href="análise-combinatória-diagramas-de-árvore-permutações-arranjos-combinações.html#combinações"><i class="fa fa-check"></i><b>2.9.2</b> Combinações</a></li>
<li class="chapter" data-level="2.9.3" data-path="análise-combinatória-diagramas-de-árvore-permutações-arranjos-combinações.html"><a href="análise-combinatória-diagramas-de-árvore-permutações-arranjos-combinações.html#observações-acerca-de-alguns-fatoriais"><i class="fa fa-check"></i><b>2.9.3</b> Observações acerca de alguns fatoriais</a></li>
</ul></li>
<li class="chapter" data-level="2.10" data-path="conectivos-lógicos.html"><a href="conectivos-lógicos.html"><i class="fa fa-check"></i><b>2.10</b> Conectivos lógicos</a></li>
<li class="chapter" data-level="2.11" data-path="leis-de-de-morgan.html"><a href="leis-de-de-morgan.html"><i class="fa fa-check"></i><b>2.11</b> Leis de De Morgan</a></li>
<li class="chapter" data-level="2.12" data-path="noções-básicas-para-o-uso-de-calculadora-cassio-fx-82ms.html"><a href="noções-básicas-para-o-uso-de-calculadora-cassio-fx-82ms.html"><i class="fa fa-check"></i><b>2.12</b> Noções básicas para o uso de calculadora (Cassio fx-82MS)</a></li>
<li class="chapter" data-level="2.13" data-path="instalação-do-software-r-em-conjunto-com-a-interface-gráfica-rstudio.html"><a href="instalação-do-software-r-em-conjunto-com-a-interface-gráfica-rstudio.html"><i class="fa fa-check"></i><b>2.13</b> Instalação do software R em conjunto com a interface gráfica RStudio</a>
<ul>
<li class="chapter" data-level="2.13.1" data-path="instalação-do-software-r-em-conjunto-com-a-interface-gráfica-rstudio.html"><a href="instalação-do-software-r-em-conjunto-com-a-interface-gráfica-rstudio.html#rstudio"><i class="fa fa-check"></i><b>2.13.1</b> RStudio</a></li>
<li class="chapter" data-level="2.13.2" data-path="instalação-do-software-r-em-conjunto-com-a-interface-gráfica-rstudio.html"><a href="instalação-do-software-r-em-conjunto-com-a-interface-gráfica-rstudio.html#pacotes"><i class="fa fa-check"></i><b>2.13.2</b> Pacotes</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="introdução-à-estatística-descritiva.html"><a href="introdução-à-estatística-descritiva.html"><i class="fa fa-check"></i><b>3</b> Introdução à estatística descritiva</a>
<ul>
<li class="chapter" data-level="3.1" data-path="análise-exploratória.html"><a href="análise-exploratória.html"><i class="fa fa-check"></i><b>3.1</b> Análise exploratória</a></li>
<li class="chapter" data-level="3.2" data-path="dados-brutos-em-rol-diagrama-de-ramos-folhas-e-de-dispersão-unidimensional.html"><a href="dados-brutos-em-rol-diagrama-de-ramos-folhas-e-de-dispersão-unidimensional.html"><i class="fa fa-check"></i><b>3.2</b> Dados brutos, em rol, diagrama de ramos &amp; folhas e de dispersão unidimensional</a></li>
<li class="chapter" data-level="3.3" data-path="sínteses-numéricas-descritivas.html"><a href="sínteses-numéricas-descritivas.html"><i class="fa fa-check"></i><b>3.3</b> Sínteses numéricas descritivas</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="sínteses-numéricas-descritivas.html"><a href="sínteses-numéricas-descritivas.html#medidas-de-tendência-central-posição"><i class="fa fa-check"></i><b>3.3.1</b> Medidas de tendência central (posição)</a></li>
<li class="chapter" data-level="3.3.2" data-path="sínteses-numéricas-descritivas.html"><a href="sínteses-numéricas-descritivas.html#medidas-de-dispersão-variabilidade"><i class="fa fa-check"></i><b>3.3.2</b> Medidas de dispersão (variabilidade)</a></li>
<li class="chapter" data-level="3.3.3" data-path="sínteses-numéricas-descritivas.html"><a href="sínteses-numéricas-descritivas.html#medidas-de-subdivisão-separatrizes"><i class="fa fa-check"></i><b>3.3.3</b> Medidas de subdivisão (separatrizes)</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="medidas-de-forma-assimetria-curtose.html"><a href="medidas-de-forma-assimetria-curtose.html"><i class="fa fa-check"></i><b>3.4</b> Medidas de forma (assimetria &amp; curtose)</a></li>
<li class="chapter" data-level="3.5" data-path="apresentação-tabular-de-dados.html"><a href="apresentação-tabular-de-dados.html"><i class="fa fa-check"></i><b>3.5</b> Apresentação tabular de dados</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="apresentação-tabular-de-dados.html"><a href="apresentação-tabular-de-dados.html#apresentação-tabular-de-dados-qualitativos"><i class="fa fa-check"></i><b>3.5.1</b> Apresentação tabular de dados qualitativos</a></li>
<li class="chapter" data-level="3.5.2" data-path="apresentação-tabular-de-dados.html"><a href="apresentação-tabular-de-dados.html#apresentação-tabular-de-dados-quantitativos"><i class="fa fa-check"></i><b>3.5.2</b> Apresentação tabular de dados quantitativos</a></li>
<li class="chapter" data-level="3.5.3" data-path="apresentação-tabular-de-dados.html"><a href="apresentação-tabular-de-dados.html#média-1"><i class="fa fa-check"></i><b>3.5.3</b> Média</a></li>
<li class="chapter" data-level="3.5.4" data-path="apresentação-tabular-de-dados.html"><a href="apresentação-tabular-de-dados.html#moda-1"><i class="fa fa-check"></i><b>3.5.4</b> Moda</a></li>
<li class="chapter" data-level="3.5.5" data-path="apresentação-tabular-de-dados.html"><a href="apresentação-tabular-de-dados.html#variância"><i class="fa fa-check"></i><b>3.5.5</b> Variância</a></li>
<li class="chapter" data-level="3.5.6" data-path="apresentação-tabular-de-dados.html"><a href="apresentação-tabular-de-dados.html#quartis"><i class="fa fa-check"></i><b>3.5.6</b> Quartis</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="apresentação-gráfica-de-dados.html"><a href="apresentação-gráfica-de-dados.html"><i class="fa fa-check"></i><b>3.6</b> Apresentação gráfica de dados</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="apresentação-gráfica-de-dados.html"><a href="apresentação-gráfica-de-dados.html#gráficos-para-uma-variável-qualitativa"><i class="fa fa-check"></i><b>3.6.1</b> Gráficos para uma variável qualitativa</a></li>
<li class="chapter" data-level="3.6.2" data-path="apresentação-gráfica-de-dados.html"><a href="apresentação-gráfica-de-dados.html#gráficos-para-uma-variável-quantitativa"><i class="fa fa-check"></i><b>3.6.2</b> Gráficos para uma variável quantitativa</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="introdução-ao-cálculo-de-probabilidades.html"><a href="introdução-ao-cálculo-de-probabilidades.html"><i class="fa fa-check"></i><b>4</b> Introdução ao cálculo de probabilidades</a>
<ul>
<li class="chapter" data-level="4.1" data-path="conceitos-essenciais.html"><a href="conceitos-essenciais.html"><i class="fa fa-check"></i><b>4.1</b> Conceitos essenciais</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="conceitos-essenciais.html"><a href="conceitos-essenciais.html#experimentos-determinísticos-e-experimentos-probabilísticos-aleatórios"><i class="fa fa-check"></i><b>4.1.1</b> Experimentos determinísticos e experimentos probabilísticos (aleatórios)</a></li>
<li class="chapter" data-level="4.1.2" data-path="conceitos-essenciais.html"><a href="conceitos-essenciais.html#o-espaço-amostral-como-um-conjunto"><i class="fa fa-check"></i><b>4.1.2</b> O espaço amostral como um conjunto</a></li>
<li class="chapter" data-level="4.1.3" data-path="conceitos-essenciais.html"><a href="conceitos-essenciais.html#evento"><i class="fa fa-check"></i><b>4.1.3</b> Evento</a></li>
<li class="chapter" data-level="4.1.4" data-path="conceitos-essenciais.html"><a href="conceitos-essenciais.html#diagramas-de-venn-para-representar-o-espaço-amostral-e-eventos-de-interesse"><i class="fa fa-check"></i><b>4.1.4</b> Diagramas de Venn para representar o espaço amostral e eventos de interesse</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="probabilidade.html"><a href="probabilidade.html"><i class="fa fa-check"></i><b>4.2</b> Probabilidade</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="probabilidade.html"><a href="probabilidade.html#introdução-histórica"><i class="fa fa-check"></i><b>4.2.1</b> Introdução histórica</a></li>
<li class="chapter" data-level="4.2.2" data-path="probabilidade.html"><a href="probabilidade.html#conceito-clássico-ou-a-priori"><i class="fa fa-check"></i><b>4.2.2</b> Conceito clássico ou <em>a priori</em></a></li>
<li class="chapter" data-level="4.2.3" data-path="probabilidade.html"><a href="probabilidade.html#conceito-frequentista-ou-a-posteriori"><i class="fa fa-check"></i><b>4.2.3</b> Conceito frequentista ou <em>a posteriori</em></a></li>
<li class="chapter" data-level="4.2.4" data-path="probabilidade.html"><a href="probabilidade.html#conceito-axiomático"><i class="fa fa-check"></i><b>4.2.4</b> Conceito axiomático</a></li>
<li class="chapter" data-level="4.2.5" data-path="probabilidade.html"><a href="probabilidade.html#probabilidade-da-união-de-eventos"><i class="fa fa-check"></i><b>4.2.5</b> Probabilidade da união de eventos</a></li>
<li class="chapter" data-level="4.2.6" data-path="probabilidade.html"><a href="probabilidade.html#probabilidade-de-eventos-condicionados"><i class="fa fa-check"></i><b>4.2.6</b> Probabilidade de eventos condicionados</a></li>
<li class="chapter" data-level="4.2.7" data-path="probabilidade.html"><a href="probabilidade.html#dependência-e-independência-de-eventos"><i class="fa fa-check"></i><b>4.2.7</b> Dependência e independência de eventos</a></li>
<li class="chapter" data-level="4.2.8" data-path="probabilidade.html"><a href="probabilidade.html#probabilidade-da-interseção-de-eventos-independentes"><i class="fa fa-check"></i><b>4.2.8</b> Probabilidade da interseção de eventos independentes</a></li>
<li class="chapter" data-level="4.2.9" data-path="probabilidade.html"><a href="probabilidade.html#demonstração-clássica-de-independência"><i class="fa fa-check"></i><b>4.2.9</b> Demonstração clássica de independência</a></li>
<li class="chapter" data-level="4.2.10" data-path="probabilidade.html"><a href="probabilidade.html#demonstração-clássica-de-dependência"><i class="fa fa-check"></i><b>4.2.10</b> Demonstração clássica de dependência</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="teorema-de-bayes.html"><a href="teorema-de-bayes.html"><i class="fa fa-check"></i><b>4.3</b> Teorema de Bayes</a></li>
<li class="chapter" data-level="4.4" data-path="teoremas-da-teoria-das-probabilidades.html"><a href="teoremas-da-teoria-das-probabilidades.html"><i class="fa fa-check"></i><b>4.4</b> Teoremas da Teoria das probabilidades</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="teoremas-da-teoria-das-probabilidades.html"><a href="teoremas-da-teoria-das-probabilidades.html#teorema-01"><i class="fa fa-check"></i><b>4.4.1</b> Teorema 01</a></li>
<li class="chapter" data-level="4.4.2" data-path="teoremas-da-teoria-das-probabilidades.html"><a href="teoremas-da-teoria-das-probabilidades.html#teorema-02"><i class="fa fa-check"></i><b>4.4.2</b> Teorema 02</a></li>
<li class="chapter" data-level="4.4.3" data-path="teoremas-da-teoria-das-probabilidades.html"><a href="teoremas-da-teoria-das-probabilidades.html#teorema-03"><i class="fa fa-check"></i><b>4.4.3</b> Teorema 03</a></li>
<li class="chapter" data-level="4.4.4" data-path="teoremas-da-teoria-das-probabilidades.html"><a href="teoremas-da-teoria-das-probabilidades.html#teorema-04"><i class="fa fa-check"></i><b>4.4.4</b> Teorema 04</a></li>
<li class="chapter" data-level="4.4.5" data-path="teoremas-da-teoria-das-probabilidades.html"><a href="teoremas-da-teoria-das-probabilidades.html#teorema-05"><i class="fa fa-check"></i><b>4.4.5</b> Teorema 05</a></li>
<li class="chapter" data-level="4.4.6" data-path="teoremas-da-teoria-das-probabilidades.html"><a href="teoremas-da-teoria-das-probabilidades.html#teorema-06"><i class="fa fa-check"></i><b>4.4.6</b> Teorema 06</a></li>
<li class="chapter" data-level="4.4.7" data-path="teoremas-da-teoria-das-probabilidades.html"><a href="teoremas-da-teoria-das-probabilidades.html#teorema-07"><i class="fa fa-check"></i><b>4.4.7</b> Teorema 07</a></li>
<li class="chapter" data-level="4.4.8" data-path="teoremas-da-teoria-das-probabilidades.html"><a href="teoremas-da-teoria-das-probabilidades.html#teorema-08"><i class="fa fa-check"></i><b>4.4.8</b> Teorema 08</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="introdução-a-variáveis-aleatórias.html"><a href="introdução-a-variáveis-aleatórias.html"><i class="fa fa-check"></i><b>5</b> Introdução a variáveis aleatórias</a>
<ul>
<li class="chapter" data-level="5.1" data-path="função-discreta-de-distribuição-de-probabilidade.html"><a href="função-discreta-de-distribuição-de-probabilidade.html"><i class="fa fa-check"></i><b>5.1</b> Função discreta de distribuição de probabilidade</a></li>
<li class="chapter" data-level="5.2" data-path="função-de-densidade-de-probabilidade.html"><a href="função-de-densidade-de-probabilidade.html"><i class="fa fa-check"></i><b>5.2</b> Função de densidade de probabilidade</a></li>
<li class="chapter" data-level="5.3" data-path="esperança-e-variância-de-uma-variável-aleatória-discreta.html"><a href="esperança-e-variância-de-uma-variável-aleatória-discreta.html"><i class="fa fa-check"></i><b>5.3</b> Esperança e variância de uma variável aleatória discreta</a></li>
<li class="chapter" data-level="5.4" data-path="esperança-e-variância-de-uma-variável-aleatória-contínua.html"><a href="esperança-e-variância-de-uma-variável-aleatória-contínua.html"><i class="fa fa-check"></i><b>5.4</b> Esperança e variância de uma variável aleatória contínua</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="introdução-a-modelos-teóricos-de-probabilidade.html"><a href="introdução-a-modelos-teóricos-de-probabilidade.html"><i class="fa fa-check"></i><b>6</b> Introdução a modelos teóricos de probabilidade</a>
<ul>
<li class="chapter" data-level="6.1" data-path="modelos-teóricos-discretos.html"><a href="modelos-teóricos-discretos.html"><i class="fa fa-check"></i><b>6.1</b> Modelos teóricos discretos</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="modelos-teóricos-discretos.html"><a href="modelos-teóricos-discretos.html#bernoulli"><i class="fa fa-check"></i><b>6.1.1</b> Bernoulli</a></li>
<li class="chapter" data-level="6.1.2" data-path="modelos-teóricos-discretos.html"><a href="modelos-teóricos-discretos.html#binomial"><i class="fa fa-check"></i><b>6.1.2</b> Binomial</a></li>
<li class="chapter" data-level="6.1.3" data-path="modelos-teóricos-discretos.html"><a href="modelos-teóricos-discretos.html#poisson"><i class="fa fa-check"></i><b>6.1.3</b> Poisson</a></li>
<li class="chapter" data-level="6.1.4" data-path="modelos-teóricos-discretos.html"><a href="modelos-teóricos-discretos.html#multinomial"><i class="fa fa-check"></i><b>6.1.4</b> Multinomial</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="modelos-téoricos-do-tempo-de-espera.html"><a href="modelos-téoricos-do-tempo-de-espera.html"><i class="fa fa-check"></i><b>6.2</b> Modelos téoricos do tempo de espera</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="modelos-téoricos-do-tempo-de-espera.html"><a href="modelos-téoricos-do-tempo-de-espera.html#geométrica"><i class="fa fa-check"></i><b>6.2.1</b> Geométrica</a></li>
<li class="chapter" data-level="6.2.2" data-path="modelos-téoricos-do-tempo-de-espera.html"><a href="modelos-téoricos-do-tempo-de-espera.html#binomial-negativa"><i class="fa fa-check"></i><b>6.2.2</b> Binomial Negativa</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="modelos-teóricos-contínuos.html"><a href="modelos-teóricos-contínuos.html"><i class="fa fa-check"></i><b>6.3</b> Modelos teóricos contínuos</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="modelos-teóricos-contínuos.html"><a href="modelos-teóricos-contínuos.html#uniforme"><i class="fa fa-check"></i><b>6.3.1</b> Uniforme</a></li>
<li class="chapter" data-level="6.3.2" data-path="modelos-teóricos-contínuos.html"><a href="modelos-teóricos-contínuos.html#exponencial"><i class="fa fa-check"></i><b>6.3.2</b> Exponencial</a></li>
<li class="chapter" data-level="6.3.3" data-path="modelos-teóricos-contínuos.html"><a href="modelos-teóricos-contínuos.html#normal"><i class="fa fa-check"></i><b>6.3.3</b> Normal</a></li>
<li class="chapter" data-level="6.3.4" data-path="modelos-teóricos-contínuos.html"><a href="modelos-teóricos-contínuos.html#student-t"><i class="fa fa-check"></i><b>6.3.4</b> Student “t”</a></li>
<li class="chapter" data-level="6.3.5" data-path="modelos-teóricos-contínuos.html"><a href="modelos-teóricos-contínuos.html#qui-quadrado"><i class="fa fa-check"></i><b>6.3.5</b> Qui-Quadrado</a></li>
<li class="chapter" data-level="6.3.6" data-path="modelos-teóricos-contínuos.html"><a href="modelos-teóricos-contínuos.html#fisher-snedecor-f"><i class="fa fa-check"></i><b>6.3.6</b> Fisher-Snedecor “F”</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="tabelas.html"><a href="tabelas.html"><i class="fa fa-check"></i><b>6.4</b> Tabelas</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="planejamento_pesquisas.html"><a href="planejamento_pesquisas.html"><i class="fa fa-check"></i><b>7</b> Introdução ao planejamento de pesquisas</a>
<ul>
<li class="chapter" data-level="7.1" data-path="planejamento-de-pesquisas.html"><a href="planejamento-de-pesquisas.html"><i class="fa fa-check"></i><b>7.1</b> Planejamento de pesquisas</a></li>
<li class="chapter" data-level="7.2" data-path="tipos-de-pesquisas.html"><a href="tipos-de-pesquisas.html"><i class="fa fa-check"></i><b>7.2</b> Tipos de pesquisas</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="tipos-de-pesquisas.html"><a href="tipos-de-pesquisas.html#quanto-à-finalidade"><i class="fa fa-check"></i><b>7.2.1</b> Quanto à finalidade</a></li>
<li class="chapter" data-level="7.2.2" data-path="tipos-de-pesquisas.html"><a href="tipos-de-pesquisas.html#quanto-à-forma-de-abordagem"><i class="fa fa-check"></i><b>7.2.2</b> Quanto à forma de abordagem</a></li>
<li class="chapter" data-level="7.2.3" data-path="tipos-de-pesquisas.html"><a href="tipos-de-pesquisas.html#quanto-aos-objetivos"><i class="fa fa-check"></i><b>7.2.3</b> Quanto aos objetivos</a></li>
<li class="chapter" data-level="7.2.4" data-path="tipos-de-pesquisas.html"><a href="tipos-de-pesquisas.html#quanto-ao-desenvolvimento-no-tempo"><i class="fa fa-check"></i><b>7.2.4</b> Quanto ao desenvolvimento no tempo</a></li>
<li class="chapter" data-level="7.2.5" data-path="tipos-de-pesquisas.html"><a href="tipos-de-pesquisas.html#quanto-à-natureza"><i class="fa fa-check"></i><b>7.2.5</b> Quanto à natureza</a></li>
<li class="chapter" data-level="7.2.6" data-path="tipos-de-pesquisas.html"><a href="tipos-de-pesquisas.html#quanto-à-forma-de-obtenção-dos-dados"><i class="fa fa-check"></i><b>7.2.6</b> Quanto à forma de obtenção dos dados</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="principais-etapas-de-uma-pesquisa.html"><a href="principais-etapas-de-uma-pesquisa.html"><i class="fa fa-check"></i><b>7.3</b> Principais etapas de uma pesquisa:</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="principais-etapas-de-uma-pesquisa.html"><a href="principais-etapas-de-uma-pesquisa.html#objetivo"><i class="fa fa-check"></i><b>7.3.1</b> Objetivo</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="população.html"><a href="população.html"><i class="fa fa-check"></i><b>7.4</b> População</a></li>
<li class="chapter" data-level="7.5" data-path="censo.html"><a href="censo.html"><i class="fa fa-check"></i><b>7.5</b> Censo</a></li>
<li class="chapter" data-level="7.6" data-path="amostra.html"><a href="amostra.html"><i class="fa fa-check"></i><b>7.6</b> Amostra</a></li>
<li class="chapter" data-level="7.7" data-path="planejamento-do-levantamento-amostral.html"><a href="planejamento-do-levantamento-amostral.html"><i class="fa fa-check"></i><b>7.7</b> Planejamento do levantamento amostral</a></li>
<li class="chapter" data-level="7.8" data-path="elaboração-dos-questionários.html"><a href="elaboração-dos-questionários.html"><i class="fa fa-check"></i><b>7.8</b> Elaboração dos questionários</a>
<ul>
<li class="chapter" data-level="7.8.1" data-path="elaboração-dos-questionários.html"><a href="elaboração-dos-questionários.html#tipos-de-perguntas"><i class="fa fa-check"></i><b>7.8.1</b> Tipos de perguntas:</a></li>
<li class="chapter" data-level="7.8.2" data-path="elaboração-dos-questionários.html"><a href="elaboração-dos-questionários.html#execução-do-levantamento-amostral"><i class="fa fa-check"></i><b>7.8.2</b> Execução do levantamento amostral</a></li>
<li class="chapter" data-level="7.8.3" data-path="elaboração-dos-questionários.html"><a href="elaboração-dos-questionários.html#análise-exploratória-dos-dados"><i class="fa fa-check"></i><b>7.8.3</b> Análise exploratória dos dados</a></li>
<li class="chapter" data-level="7.8.4" data-path="elaboração-dos-questionários.html"><a href="elaboração-dos-questionários.html#resultados-e-conclusões"><i class="fa fa-check"></i><b>7.8.4</b> Resultados e conclusões</a></li>
</ul></li>
<li class="chapter" data-level="7.9" data-path="técnicas-de-amostragem.html"><a href="técnicas-de-amostragem.html"><i class="fa fa-check"></i><b>7.9</b> Técnicas de amostragem</a></li>
<li class="chapter" data-level="7.10" data-path="amostragem-probabilística.html"><a href="amostragem-probabilística.html"><i class="fa fa-check"></i><b>7.10</b> Amostragem probabilística</a>
<ul>
<li class="chapter" data-level="7.10.1" data-path="amostragem-probabilística.html"><a href="amostragem-probabilística.html#amostragem-aleatória-simples-aas"><i class="fa fa-check"></i><b>7.10.1</b> Amostragem aleatória simples (AAS)</a></li>
<li class="chapter" data-level="7.10.2" data-path="amostragem-probabilística.html"><a href="amostragem-probabilística.html#amostragem-aleatória-sistemática"><i class="fa fa-check"></i><b>7.10.2</b> Amostragem aleatória sistemática</a></li>
<li class="chapter" data-level="7.10.3" data-path="amostragem-probabilística.html"><a href="amostragem-probabilística.html#amostragem-aleatória-estratificada"><i class="fa fa-check"></i><b>7.10.3</b> Amostragem aleatória estratificada</a></li>
<li class="chapter" data-level="7.10.4" data-path="amostragem-probabilística.html"><a href="amostragem-probabilística.html#amostragem-aleatória-por-conglomerados"><i class="fa fa-check"></i><b>7.10.4</b> Amostragem aleatória por conglomerados</a></li>
</ul></li>
<li class="chapter" data-level="7.11" data-path="amostragem-não-probabilística.html"><a href="amostragem-não-probabilística.html"><i class="fa fa-check"></i><b>7.11</b> Amostragem não probabilística</a>
<ul>
<li class="chapter" data-level="7.11.1" data-path="amostragem-não-probabilística.html"><a href="amostragem-não-probabilística.html#amostragem-por-conveniência"><i class="fa fa-check"></i><b>7.11.1</b> Amostragem por conveniência</a></li>
<li class="chapter" data-level="7.11.2" data-path="amostragem-não-probabilística.html"><a href="amostragem-não-probabilística.html#amostragem-por-cotas"><i class="fa fa-check"></i><b>7.11.2</b> Amostragem por cotas</a></li>
</ul></li>
<li class="chapter" data-level="7.12" data-path="dimensionamento-de-amostras.html"><a href="dimensionamento-de-amostras.html"><i class="fa fa-check"></i><b>7.12</b> Dimensionamento de amostras</a>
<ul>
<li class="chapter" data-level="7.12.1" data-path="dimensionamento-de-amostras.html"><a href="dimensionamento-de-amostras.html#erros"><i class="fa fa-check"></i><b>7.12.1</b> Erros</a></li>
<li class="chapter" data-level="7.12.2" data-path="dimensionamento-de-amostras.html"><a href="dimensionamento-de-amostras.html#determinação-do-tamanho-de-uma-amostra-para-estimação-da-média-populacional"><i class="fa fa-check"></i><b>7.12.2</b> Determinação do tamanho de uma amostra para estimação da média populacional</a></li>
<li class="chapter" data-level="7.12.3" data-path="dimensionamento-de-amostras.html"><a href="dimensionamento-de-amostras.html#determinação-do-tamanho-de-uma-amostra-para-estimação-da-proporção-populacional"><i class="fa fa-check"></i><b>7.12.3</b> Determinação do tamanho de uma amostra para estimação da proporção populacional</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="introdução-às-estatísticas-epidemiológicas.html"><a href="introdução-às-estatísticas-epidemiológicas.html"><i class="fa fa-check"></i><b>8</b> Introdução às estatísticas epidemiológicas</a>
<ul>
<li class="chapter" data-level="8.1" data-path="terminologia.html"><a href="terminologia.html"><i class="fa fa-check"></i><b>8.1</b> Terminologia</a></li>
<li class="chapter" data-level="8.2" data-path="medidas-de-risco-morte-associação-e-correlação.html"><a href="medidas-de-risco-morte-associação-e-correlação.html"><i class="fa fa-check"></i><b>8.2</b> Medidas de risco, morte, associação e correlação</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="medidas-de-risco-morte-associação-e-correlação.html"><a href="medidas-de-risco-morte-associação-e-correlação.html#incidência"><i class="fa fa-check"></i><b>8.2.1</b> Incidência</a></li>
<li class="chapter" data-level="8.2.2" data-path="medidas-de-risco-morte-associação-e-correlação.html"><a href="medidas-de-risco-morte-associação-e-correlação.html#prevalência"><i class="fa fa-check"></i><b>8.2.2</b> Prevalência</a></li>
<li class="chapter" data-level="8.2.3" data-path="medidas-de-risco-morte-associação-e-correlação.html"><a href="medidas-de-risco-morte-associação-e-correlação.html#relação-entre-prevalência-e-incidência"><i class="fa fa-check"></i><b>8.2.3</b> Relação entre prevalência e incidência</a></li>
<li class="chapter" data-level="8.2.4" data-path="medidas-de-risco-morte-associação-e-correlação.html"><a href="medidas-de-risco-morte-associação-e-correlação.html#quadro-comparativo-entre-medidas-de-incidência-e-de-prevalência"><i class="fa fa-check"></i><b>8.2.4</b> Quadro comparativo entre medidas de incidência e de prevalência</a></li>
<li class="chapter" data-level="8.2.5" data-path="medidas-de-risco-morte-associação-e-correlação.html"><a href="medidas-de-risco-morte-associação-e-correlação.html#incidência-cumulativa---ic-risco"><i class="fa fa-check"></i><b>8.2.5</b> Incidência cumulativa - IC (Risco)}</a></li>
<li class="chapter" data-level="8.2.6" data-path="medidas-de-risco-morte-associação-e-correlação.html"><a href="medidas-de-risco-morte-associação-e-correlação.html#quadro-comparativo-entre-medidas-de-risco-e-prevalência"><i class="fa fa-check"></i><b>8.2.6</b> Quadro comparativo entre medidas de risco e prevalência</a></li>
<li class="chapter" data-level="8.2.7" data-path="medidas-de-risco-morte-associação-e-correlação.html"><a href="medidas-de-risco-morte-associação-e-correlação.html#fatalidade-dos-casos-fc"><i class="fa fa-check"></i><b>8.2.7</b> Fatalidade dos Casos (FC)</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="sobrevida.html"><a href="sobrevida.html"><i class="fa fa-check"></i><b>8.3</b> Sobrevida</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="sobrevida.html"><a href="sobrevida.html#taxas-de-mortalidade-tm"><i class="fa fa-check"></i><b>8.3.1</b> Taxas de mortalidade (TM)</a></li>
<li class="chapter" data-level="8.3.2" data-path="sobrevida.html"><a href="sobrevida.html#taxas-mais-específicas"><i class="fa fa-check"></i><b>8.3.2</b> Taxas mais específicas</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="medidas-de-associação.html"><a href="medidas-de-associação.html"><i class="fa fa-check"></i><b>8.4</b> Medidas de associação</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="medidas-de-associação.html"><a href="medidas-de-associação.html#incidência-observada-de-nascimentos-com-baixo-peso-entre-mães-expostas-ao-risco-fumantes"><i class="fa fa-check"></i><b>8.4.1</b> Incidência observada de nascimentos com baixo peso entre mães expostas ao risco (fumantes)</a></li>
<li class="chapter" data-level="8.4.2" data-path="medidas-de-associação.html"><a href="medidas-de-associação.html#incidência-observada-de-nascimentos-com-baixo-peso-entre-mães-não-expostas-ao-risco-não-fumantes"><i class="fa fa-check"></i><b>8.4.2</b> Incidência observada de nascimentos com baixo peso entre mães não expostas ao risco (não fumantes)</a></li>
<li class="chapter" data-level="8.4.3" data-path="medidas-de-associação.html"><a href="medidas-de-associação.html#prevalência-de-nascimentos-com-baixo-peso-na-população-estudada"><i class="fa fa-check"></i><b>8.4.3</b> Prevalência de nascimentos com baixo peso na população estudada</a></li>
<li class="chapter" data-level="8.4.4" data-path="medidas-de-associação.html"><a href="medidas-de-associação.html#diferença-de-risco-risco-atribuível---ra"><i class="fa fa-check"></i><b>8.4.4</b> Diferença de risco (Risco atribuível - RA)</a></li>
<li class="chapter" data-level="8.4.5" data-path="medidas-de-associação.html"><a href="medidas-de-associação.html#razão-de-risco-risco-relativo---rr"><i class="fa fa-check"></i><b>8.4.5</b> Razão de risco (Risco relativo - RR)</a></li>
<li class="chapter" data-level="8.4.6" data-path="medidas-de-associação.html"><a href="medidas-de-associação.html#risco-atribuível-proporcional-fração-etiológica---fe"><i class="fa fa-check"></i><b>8.4.6</b> Risco atribuível proporcional (Fração etiológica - FE)</a></li>
<li class="chapter" data-level="8.4.7" data-path="medidas-de-associação.html"><a href="medidas-de-associação.html#odds-ratio-razão-das-chances"><i class="fa fa-check"></i><b>8.4.7</b> <em>Odds ratio</em> (Razão das chances)</a></li>
<li class="chapter" data-level="8.4.8" data-path="medidas-de-associação.html"><a href="medidas-de-associação.html#correlação-linear-de-pearson"><i class="fa fa-check"></i><b>8.4.8</b> Correlação linear de Pearson</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="intervalos-de-confiança.html"><a href="intervalos-de-confiança.html"><i class="fa fa-check"></i><b>8.5</b> Intervalos de confiança</a>
<ul>
<li class="chapter" data-level="8.5.1" data-path="intervalos-de-confiança.html"><a href="intervalos-de-confiança.html#razão-de-risco-risco-relativo---rr-1"><i class="fa fa-check"></i><b>8.5.1</b> Razão de risco (Risco relativo - RR)</a></li>
<li class="chapter" data-level="8.5.2" data-path="intervalos-de-confiança.html"><a href="intervalos-de-confiança.html#razão-de-chances-odds-ratio---or"><i class="fa fa-check"></i><b>8.5.2</b> Razão de chances ( <em>odds ratio</em> - OR)</a></li>
<li class="chapter" data-level="8.5.3" data-path="intervalos-de-confiança.html"><a href="intervalos-de-confiança.html#diferença-de-risco-risco-atribuível---ra-1"><i class="fa fa-check"></i><b>8.5.3</b> Diferença de risco (Risco atribuível - RA)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="introdução-à-distribuição-das-médias-e-diferenças-entre-médias-amostrais-e-seus-intervalos-de-confiança.html"><a href="introdução-à-distribuição-das-médias-e-diferenças-entre-médias-amostrais-e-seus-intervalos-de-confiança.html"><i class="fa fa-check"></i><b>9</b> Introdução à distribuição das médias e diferenças entre médias amostrais e seus intervalos de confiança</a>
<ul>
<li class="chapter" data-level="9.1" data-path="distribuições-amostrais.html"><a href="distribuições-amostrais.html"><i class="fa fa-check"></i><b>9.1</b> Distribuições amostrais</a></li>
<li class="chapter" data-level="9.2" data-path="intervalos-de-confiança-1.html"><a href="intervalos-de-confiança-1.html"><i class="fa fa-check"></i><b>9.2</b> Intervalos de confiança</a></li>
<li class="chapter" data-level="9.3" data-path="distribuição-das-médias-amostrais-e-seus-intervalos-de-confiança.html"><a href="distribuição-das-médias-amostrais-e-seus-intervalos-de-confiança.html"><i class="fa fa-check"></i><b>9.3</b> Distribuição das médias amostrais e seus intervalos de confiança</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="distribuição-das-médias-amostrais-e-seus-intervalos-de-confiança.html"><a href="distribuição-das-médias-amostrais-e-seus-intervalos-de-confiança.html#fator-de-correção-para-populações-finitas"><i class="fa fa-check"></i><b>9.3.1</b> Fator de correção para populações finitas</a></li>
<li class="chapter" data-level="9.3.2" data-path="distribuição-das-médias-amostrais-e-seus-intervalos-de-confiança.html"><a href="distribuição-das-médias-amostrais-e-seus-intervalos-de-confiança.html#intervalo-de-confiança-para-médias-amostrais"><i class="fa fa-check"></i><b>9.3.2</b> Intervalo de confiança para médias amostrais</a></li>
<li class="chapter" data-level="9.3.3" data-path="distribuição-das-médias-amostrais-e-seus-intervalos-de-confiança.html"><a href="distribuição-das-médias-amostrais-e-seus-intervalos-de-confiança.html#intervalo-de-confiança-bilateral-para-uma-média-amostral-sob-variância-populacional-conhecida-figura-reffigfig28"><i class="fa fa-check"></i><b>9.3.3</b> Intervalo de confiança bilateral para uma média amostral sob variância populacional conhecida (Figura @ref(fig:fig28))</a></li>
<li class="chapter" data-level="9.3.4" data-path="distribuição-das-médias-amostrais-e-seus-intervalos-de-confiança.html"><a href="distribuição-das-médias-amostrais-e-seus-intervalos-de-confiança.html#intervalo-de-confiança-para-uma-média-amostral-sob-variância-populacional-desconhecida-mas-amostras-não-tão-pequenas-n-ge-30-figura-reffigfig55"><i class="fa fa-check"></i><b>9.3.4</b> Intervalo de confiança para uma média amostral sob variância populacional desconhecida mas amostras não tão pequenas: <span class="math inline">\(n \ge 30\)</span> (Figura @ref(fig:fig55))</a></li>
<li class="chapter" data-level="9.3.5" data-path="distribuição-das-médias-amostrais-e-seus-intervalos-de-confiança.html"><a href="distribuição-das-médias-amostrais-e-seus-intervalos-de-confiança.html#intervalo-de-confiança-para-uma-média-amostral-sob-variância-populacional-desconhecida-e-amostras-de-qualquer-tamanho-figura-reffigfig58"><i class="fa fa-check"></i><b>9.3.5</b> Intervalo de confiança para uma média amostral sob variância populacional desconhecida e amostras de qualquer tamanho (Figura @ref(fig:fig58))</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="distribuição-das-diferenças-de-médias-amostrais-independentes-e-seus-intervalos-de-confiança.html"><a href="distribuição-das-diferenças-de-médias-amostrais-independentes-e-seus-intervalos-de-confiança.html"><i class="fa fa-check"></i><b>9.4</b> Distribuição das diferenças de médias amostrais independentes e seus intervalos de confiança</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="distribuição-das-diferenças-de-médias-amostrais-independentes-e-seus-intervalos-de-confiança.html"><a href="distribuição-das-diferenças-de-médias-amostrais-independentes-e-seus-intervalos-de-confiança.html#intervalos-de-confiança-para-a-diferença-entre-duas-médias-amostrais-com-variância-populacionais-conhecidas"><i class="fa fa-check"></i><b>9.4.1</b> Intervalos de confiança para a diferença entre duas médias amostrais com variância populacionais conhecidas</a></li>
<li class="chapter" data-level="9.4.2" data-path="distribuição-das-diferenças-de-médias-amostrais-independentes-e-seus-intervalos-de-confiança.html"><a href="distribuição-das-diferenças-de-médias-amostrais-independentes-e-seus-intervalos-de-confiança.html#intervalos-de-confiança-para-a-diferença-entre-duas-médias-amostrais-com-variâncias-populacionais-desconhecidas-mas-admitidas-iguais"><i class="fa fa-check"></i><b>9.4.2</b> Intervalos de confiança para a diferença entre duas médias amostrais com variâncias populacionais desconhecidas mas admitidas iguais</a></li>
<li class="chapter" data-level="9.4.3" data-path="distribuição-das-diferenças-de-médias-amostrais-independentes-e-seus-intervalos-de-confiança.html"><a href="distribuição-das-diferenças-de-médias-amostrais-independentes-e-seus-intervalos-de-confiança.html#intervalos-de-confiança-para-a-diferença-entre-duas-médias-amostrais-com-variâncias-populacionais-desconhecidas-e-desiguais"><i class="fa fa-check"></i><b>9.4.3</b> Intervalos de confiança para a diferença entre duas médias amostrais com variâncias populacionais desconhecidas e desiguais</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="distribuição-das-diferenças-de-médias-amostrais-dependentes-e-seus-intervalos-de-confiança.html"><a href="distribuição-das-diferenças-de-médias-amostrais-dependentes-e-seus-intervalos-de-confiança.html"><i class="fa fa-check"></i><b>9.5</b> Distribuição das diferenças de médias amostrais dependentes e seus intervalos de confiança</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="introdução-à-distribuição-das-proporções-amostrais-e-seus-intervalos-de-confiança.html"><a href="introdução-à-distribuição-das-proporções-amostrais-e-seus-intervalos-de-confiança.html"><i class="fa fa-check"></i><b>10</b> Introdução à distribuição das proporções amostrais e seus intervalos de confiança</a>
<ul>
<li class="chapter" data-level="10.1" data-path="conceito-elementar-de-uma-proporção.html"><a href="conceito-elementar-de-uma-proporção.html"><i class="fa fa-check"></i><b>10.1</b> Conceito elementar de uma proporção</a></li>
<li class="chapter" data-level="10.2" data-path="distribuição-das-proporções-amostrais.html"><a href="distribuição-das-proporções-amostrais.html"><i class="fa fa-check"></i><b>10.2</b> Distribuição das proporções amostrais</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="distribuição-das-proporções-amostrais.html"><a href="distribuição-das-proporções-amostrais.html#simulações-ilustrativas-da-aproximação-da-distribuição-das-proporções-amostrais-pela-distribuição-normal"><i class="fa fa-check"></i><b>10.2.1</b> Simulações ilustrativas da aproximação da distribuição das proporções amostrais pela distribuição Normal</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="pobabilidades-associadas-à-observação-de-uma-proporção-amostral-hatp.html"><a href="pobabilidades-associadas-à-observação-de-uma-proporção-amostral-hatp.html"><i class="fa fa-check"></i><b>10.3</b> Pobabilidades associadas à observação de uma proporção amostral <span class="math inline">\(\hat{p}\)</span></a></li>
<li class="chapter" data-level="10.4" data-path="a-aleatoriedade-das-proporções-amostrais-e-o-tamanho-amostral.html"><a href="a-aleatoriedade-das-proporções-amostrais-e-o-tamanho-amostral.html"><i class="fa fa-check"></i><b>10.4</b> A aleatoriedade das proporções amostrais e o tamanho amostral</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="a-aleatoriedade-das-proporções-amostrais-e-o-tamanho-amostral.html"><a href="a-aleatoriedade-das-proporções-amostrais-e-o-tamanho-amostral.html#simulações-ilustrativas-sobre-as-flutuações-das-proporções-amostrais-e-o-erro-amostral-fixado"><i class="fa fa-check"></i><b>10.4.1</b> Simulações ilustrativas sobre as flutuações das proporções amostrais e o erro amostral fixado</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="intervalos-de-confiança-para-proporções-amostrais.html"><a href="intervalos-de-confiança-para-proporções-amostrais.html"><i class="fa fa-check"></i><b>10.5</b> Intervalos de confiança para proporções amostrais</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="intervalos-de-confiança-para-proporções-amostrais.html"><a href="intervalos-de-confiança-para-proporções-amostrais.html#intervalos-de-confiança-para-a-diferença-entre-duas-proporções-amostrais"><i class="fa fa-check"></i><b>10.5.1</b> Intervalos de confiança para a diferença entre duas proporções amostrais</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="teste_hipoteses.html"><a href="teste_hipoteses.html"><i class="fa fa-check"></i><b>11</b> Introdução a testes de hipóteses</a>
<ul>
<li class="chapter" data-level="11.1" data-path="filosofia-da-ciência.html"><a href="filosofia-da-ciência.html"><i class="fa fa-check"></i><b>11.1</b> Filosofia da ciência</a></li>
<li class="chapter" data-level="11.2" data-path="história.html"><a href="história.html"><i class="fa fa-check"></i><b>11.2</b> História</a></li>
<li class="chapter" data-level="11.3" data-path="conceitos.html"><a href="conceitos.html"><i class="fa fa-check"></i><b>11.3</b> Conceitos</a></li>
<li class="chapter" data-level="11.4" data-path="natureza-dos-erros.html"><a href="natureza-dos-erros.html"><i class="fa fa-check"></i><b>11.4</b> Natureza dos erros</a></li>
<li class="chapter" data-level="11.5" data-path="recomendações-gerais.html"><a href="recomendações-gerais.html"><i class="fa fa-check"></i><b>11.5</b> Recomendações gerais</a></li>
<li class="chapter" data-level="11.6" data-path="efeito-do-limite-central.html"><a href="efeito-do-limite-central.html"><i class="fa fa-check"></i><b>11.6</b> Efeito do limite central</a>
<ul>
<li class="chapter" data-level="11.6.1" data-path="efeito-do-limite-central.html"><a href="efeito-do-limite-central.html#erro-global"><i class="fa fa-check"></i><b>11.6.1</b> Erro global</a></li>
</ul></li>
<li class="chapter" data-level="11.7" data-path="estruturas-das-hipóteses.html"><a href="estruturas-das-hipóteses.html"><i class="fa fa-check"></i><b>11.7</b> Estruturas das hipóteses</a>
<ul>
<li class="chapter" data-level="11.7.1" data-path="estruturas-das-hipóteses.html"><a href="estruturas-das-hipóteses.html#interpretação-gráfica-dos-níveis-de-significânciaconfiança"><i class="fa fa-check"></i><b>11.7.1</b> Interpretação gráfica dos níveis de significância/confiança</a></li>
<li class="chapter" data-level="11.7.2" data-path="estruturas-das-hipóteses.html"><a href="estruturas-das-hipóteses.html#teste-de-hipóteses-bilateral"><i class="fa fa-check"></i><b>11.7.2</b> Teste de hipóteses Bilateral</a></li>
<li class="chapter" data-level="11.7.3" data-path="estruturas-das-hipóteses.html"><a href="estruturas-das-hipóteses.html#teste-de-hipóteses-unilateral-à-esquerda"><i class="fa fa-check"></i><b>11.7.3</b> Teste de hipóteses Unilateral à esquerda</a></li>
<li class="chapter" data-level="11.7.4" data-path="estruturas-das-hipóteses.html"><a href="estruturas-das-hipóteses.html#teste-de-hipóteses-unilateral-à-direita"><i class="fa fa-check"></i><b>11.7.4</b> Teste de hipóteses Unilateral à direita</a></li>
</ul></li>
<li class="chapter" data-level="11.8" data-path="teste-de-uma-média-amostral.html"><a href="teste-de-uma-média-amostral.html"><i class="fa fa-check"></i><b>11.8</b> Teste de uma média amostral</a>
<ul>
<li class="chapter" data-level="11.8.1" data-path="teste-de-uma-média-amostral.html"><a href="teste-de-uma-média-amostral.html#cenários-possíveis"><i class="fa fa-check"></i><b>11.8.1</b> Cenários possíveis</a></li>
<li class="chapter" data-level="11.8.2" data-path="teste-de-uma-média-amostral.html"><a href="teste-de-uma-média-amostral.html#roteiro-geral"><i class="fa fa-check"></i><b>11.8.2</b> Roteiro geral</a></li>
<li class="chapter" data-level="11.8.3" data-path="teste-de-uma-média-amostral.html"><a href="teste-de-uma-média-amostral.html#probabilidade-dos-intervalos-de-confiança-para-os-testes-de-hipóteses-com-o-uso-da-estatística-z-z-sim-mathcaln01"><i class="fa fa-check"></i><b>11.8.3</b> Probabilidade dos intervalos de confiança para os testes de hipóteses com o uso da estatística Z (<span class="math inline">\(Z \sim \mathcal{N}(0,1)\)</span>):</a></li>
<li class="chapter" data-level="11.8.4" data-path="teste-de-uma-média-amostral.html"><a href="teste-de-uma-média-amostral.html#probabilidade-dos-intervalos-de-confiança-para-os-testes-de-hipóteses-com-o-uso-da-estatística-t-tsim-t_n-1"><i class="fa fa-check"></i><b>11.8.4</b> Probabilidade dos intervalos de confiança para os testes de hipóteses com o uso da estatística T (<span class="math inline">\(T\sim t_{(n-1)}\)</span>):</a></li>
</ul></li>
<li class="chapter" data-level="11.9" data-path="teste-de-médias-amostrais-independentes-de-duas-populações-normais.html"><a href="teste-de-médias-amostrais-independentes-de-duas-populações-normais.html"><i class="fa fa-check"></i><b>11.9</b> Teste de médias amostrais independentes de duas populações Normais</a>
<ul>
<li class="chapter" data-level="11.9.1" data-path="teste-de-médias-amostrais-independentes-de-duas-populações-normais.html"><a href="teste-de-médias-amostrais-independentes-de-duas-populações-normais.html#as-estruturas-possíveis-dos-testes-de-hipóteses-relacionados-às-suas-médias-serão"><i class="fa fa-check"></i><b>11.9.1</b> As estruturas possíveis dos testes de hipóteses relacionados às suas médias serão:</a></li>
<li class="chapter" data-level="11.9.2" data-path="teste-de-médias-amostrais-independentes-de-duas-populações-normais.html"><a href="teste-de-médias-amostrais-independentes-de-duas-populações-normais.html#testes-de-hipóteses-para-as-médias-de-duas-populações-com-variâncias-conhecidas-ou-não-conhecidas-mas-o-tamanho-das-amostras-é-grande"><i class="fa fa-check"></i><b>11.9.2</b> Testes de hipóteses para as médias de duas populações com variâncias conhecidas (ou não conhecidas mas o tamanho das amostras é grande)</a></li>
<li class="chapter" data-level="11.9.3" data-path="teste-de-médias-amostrais-independentes-de-duas-populações-normais.html"><a href="teste-de-médias-amostrais-independentes-de-duas-populações-normais.html#testes-de-hipóteses-para-as-médias-de-duas-populações-normais-com-variâncias-desconhecidas-mas-iguais-teste-t-homocedástico-sigma_12sigma_22"><i class="fa fa-check"></i><b>11.9.3</b> Testes de hipóteses para as médias de duas populações Normais com variâncias desconhecidas mas iguais: teste “t’’ homocedástico (<span class="math inline">\(\sigma_{1}^{2}=\sigma_{2}^{2}=?\)</span>)</a></li>
<li class="chapter" data-level="11.9.4" data-path="teste-de-médias-amostrais-independentes-de-duas-populações-normais.html"><a href="teste-de-médias-amostrais-independentes-de-duas-populações-normais.html#teste-de-hipóteses-para-as-médias-de-duas-populações-normais-com-variâncias-desconhecidas-e-desiguais-teste-t-heterocedástico-sigma_12-neq-sigma_22"><i class="fa fa-check"></i><b>11.9.4</b> Teste de hipóteses para as médias de duas populações Normais com variâncias desconhecidas e desiguais: teste “``t’’ heterocedástico (<span class="math inline">\(\sigma_{1}^{2} \neq \sigma_{2}^{2}=?\)</span>)</a></li>
</ul></li>
<li class="chapter" data-level="11.10" data-path="teste-de-uma-proporção-amostral.html"><a href="teste-de-uma-proporção-amostral.html"><i class="fa fa-check"></i><b>11.10</b> Teste de uma proporção amostral</a>
<ul>
<li class="chapter" data-level="11.10.1" data-path="teste-de-uma-proporção-amostral.html"><a href="teste-de-uma-proporção-amostral.html#estruturas-possíveis-para-as-hipóteses"><i class="fa fa-check"></i><b>11.10.1</b> Estruturas possíveis para as hipóteses</a></li>
<li class="chapter" data-level="11.10.2" data-path="teste-de-uma-proporção-amostral.html"><a href="teste-de-uma-proporção-amostral.html#probabilidade-dos-intervalos-de-confiança-para-os-testes-de-hipóteses-com-o-uso-da-estatística-z-z-sim-mathcaln01-1"><i class="fa fa-check"></i><b>11.10.2</b> Probabilidade dos intervalos de confiança para os testes de hipóteses com o uso da estatística Z (<span class="math inline">\(Z \sim \mathcal{N}(0,1)\)</span>):</a></li>
</ul></li>
<li class="chapter" data-level="11.11" data-path="testes-não-paramétricos.html"><a href="testes-não-paramétricos.html"><i class="fa fa-check"></i><b>11.11</b> Testes não paramétricos</a>
<ul>
<li class="chapter" data-level="11.11.1" data-path="testes-não-paramétricos.html"><a href="testes-não-paramétricos.html#teste-qui-quadrado-para-verificação-da-independência-homogeneidade"><i class="fa fa-check"></i><b>11.11.1</b> Teste Qui-quadrado para verificação da independência (homogeneidade)</a></li>
<li class="chapter" data-level="11.11.2" data-path="testes-não-paramétricos.html"><a href="testes-não-paramétricos.html#correção-de-continuidade-em-tabelas-2x2"><i class="fa fa-check"></i><b>11.11.2</b> Correção de continuidade em tabelas 2x2</a></li>
<li class="chapter" data-level="11.11.3" data-path="testes-não-paramétricos.html"><a href="testes-não-paramétricos.html#coeficiente-de-contingência-de-pearson-modificado-c"><i class="fa fa-check"></i><b>11.11.3</b> Coeficiente de contingência de Pearson (modificado: <span class="math inline">\(C^{*})\)</span> }</a></li>
<li class="chapter" data-level="11.11.4" data-path="testes-não-paramétricos.html"><a href="testes-não-paramétricos.html#teste-qui-quadrado-para-verificação-da-qualidade-do-ajuste-a-uma-distribuição-teórica-de-probabilidade"><i class="fa fa-check"></i><b>11.11.4</b> Teste Qui-quadrado para verificação da qualidade do ajuste a uma distribuição teórica de probabilidade</a></li>
<li class="chapter" data-level="11.11.5" data-path="testes-não-paramétricos.html"><a href="testes-não-paramétricos.html#teste-de-significância-para-as-médias-de-duas-populações-dependentes"><i class="fa fa-check"></i><b>11.11.5</b> Teste de significância para as médias de duas populações dependentes</a></li>
</ul></li>
<li class="chapter" data-level="11.12" data-path="fluxograma-auxiliar-para-escolha-da-estatística-do-teste-de-hipóteses.html"><a href="fluxograma-auxiliar-para-escolha-da-estatística-do-teste-de-hipóteses.html"><i class="fa fa-check"></i><b>11.12</b> Fluxograma auxiliar para escolha da estatística do teste de hipóteses</a></li>
<li class="chapter" data-level="11.13" data-path="tabelas-1.html"><a href="tabelas-1.html"><i class="fa fa-check"></i><b>11.13</b> Tabelas</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://fjrcosta.github.io/apostila/" target="blank">FJCosta Github</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"><div class="line-block">UNIVERSIDADE ESTADUAL DE LONDRINA<br />
CCE - Centro de Ciências Exatas<br />
DSTA - Departamento de Estatística<br />
Apostila de Estatística<br />
Prof. M.e Eng.<span class="math inline">\(^{o}\)</span> Felinto Junior Da Costa</div></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="sínteses-numéricas-descritivas" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> Sínteses numéricas descritivas<a href="sínteses-numéricas-descritivas.html#sínteses-numéricas-descritivas" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><br />
</p>
<p>Além da apresentação elementar de algumas informações relacionadas aos dados brutos da amostra, tais como os valores <em>mínimo</em> e <em>máximo</em> observados, a estatística descritiva possui muitas outras ferramentas para <em>condensar</em> a informação contida nos dados.</p>
<p><br />
</p>
<p>São chamadas de <em>sínteses numéricas</em>, medidas que condensam variados aspectos relacionados aos valores dos dados. As principais <em>sínteses numéricas</em> são:</p>
<p><br />
</p>
<ul>
<li>de tendência central (posição): média (simples ou aritmética, geométrica, harmônica, anarmônica, quadrática, biquadrática), moda e mediana;</li>
<li>de dispersão (variabilidade): absolutas (amplitude total, variância e desvio padrão) ou relativas (coeficiente de variação, unidades padronizadas); e,</li>
<li>de subdivisão (separatrizes, quantis): mediana (50%), quartis (25%, 50%, 75%), decis (10%, ….90%) e percentis (1%….99%).</li>
</ul>
<p><br />
</p>
<p>Uma medida de posição ou dispersão é dita <strong>resistente</strong> quando forem pouco afetadas pela alteração de uma pequena porção dos dados. A mediana é uma medida resistente, já a média e a variância não são.</p>
<div id="medidas-de-tendência-central-posição" class="section level3 hasAnchor" number="3.3.1">
<h3><span class="header-section-number">3.3.1</span> Medidas de tendência central (posição)<a href="sínteses-numéricas-descritivas.html#medidas-de-tendência-central-posição" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="média" class="section level4 hasAnchor" number="3.3.1.1">
<h4><span class="header-section-number">3.3.1.1</span> Média<a href="sínteses-numéricas-descritivas.html#média" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p><br />
</p>
<p>Sejam <span class="math inline">\(x_{1}, x_{2}, ..., x_{n}\)</span> os <span class="math inline">\(n\)</span> valores assumidos pela variável <span class="math inline">\(X\)</span> (dados brutos). A <em>média aritmética simples</em> será dada por:</p>
<p><br />
</p>
<p><span class="math display">\[
\stackrel{-}{x}=\frac{\sum _{i=1}^{n}{x}_{i}}{n}
\]</span></p>
<p><br />
</p>
<p>Algumas propriedades da média aritmética:</p>
<p><br />
</p>
<ul>
<li>somando-se (ou subtraindo-se) cada um dos elementos do conjunto de dados por uma constante arbitrária qualquer <span class="math inline">\(k\)</span>, a média aritmética ficará adicionada (ou subtraída) dessa essa constante <span class="math inline">\(k\)</span></li>
</ul>
<p><br />
</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="sínteses-numéricas-descritivas.html#cb18-1" tabindex="-1"></a>alturas_ad<span class="ot">=</span>alturas<span class="fl">+0.05</span></span>
<span id="cb18-2"><a href="sínteses-numéricas-descritivas.html#cb18-2" tabindex="-1"></a></span>
<span id="cb18-3"><a href="sínteses-numéricas-descritivas.html#cb18-3" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb18-4"><a href="sínteses-numéricas-descritivas.html#cb18-4" tabindex="-1"></a></span>
<span id="cb18-5"><a href="sínteses-numéricas-descritivas.html#cb18-5" tabindex="-1"></a><span class="fu">stripchart</span>(alturas,<span class="at">method =</span> <span class="st">&quot;stack&quot;</span>,  <span class="at">at=</span><span class="fl">0.5</span>, </span>
<span id="cb18-6"><a href="sínteses-numéricas-descritivas.html#cb18-6" tabindex="-1"></a><span class="at">main=</span><span class="st">&quot;&quot;</span>,<span class="at">pch =</span> <span class="dv">20</span>,</span>
<span id="cb18-7"><a href="sínteses-numéricas-descritivas.html#cb18-7" tabindex="-1"></a><span class="at">col=</span><span class="st">&quot;blue&quot;</span>, <span class="at">cex=</span><span class="dv">1</span>, <span class="at">xlab=</span><span class="st">&quot;Alturas originais dos estudantes (m)&quot;</span>, </span>
<span id="cb18-8"><a href="sínteses-numéricas-descritivas.html#cb18-8" tabindex="-1"></a><span class="at">ylab=</span><span class="st">&quot;Quantidades observadas (un)&quot;</span>)</span>
<span id="cb18-9"><a href="sínteses-numéricas-descritivas.html#cb18-9" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">mean</span>(alturas), <span class="at">col=</span><span class="st">&quot;red&quot;</span>) </span>
<span id="cb18-10"><a href="sínteses-numéricas-descritivas.html#cb18-10" tabindex="-1"></a><span class="fu">text</span>(<span class="fu">mean</span>(alturas)<span class="sc">-</span><span class="fl">0.2</span>, <span class="dv">1</span>, <span class="st">&quot;Média=1,69 m&quot;</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">srt=</span><span class="dv">90</span>) </span>
<span id="cb18-11"><a href="sínteses-numéricas-descritivas.html#cb18-11" tabindex="-1"></a></span>
<span id="cb18-12"><a href="sínteses-numéricas-descritivas.html#cb18-12" tabindex="-1"></a><span class="fu">stripchart</span>(alturas_ad,<span class="at">method =</span> <span class="st">&quot;stack&quot;</span>,  <span class="at">at=</span><span class="fl">0.5</span>, </span>
<span id="cb18-13"><a href="sínteses-numéricas-descritivas.html#cb18-13" tabindex="-1"></a><span class="at">main=</span><span class="st">&quot;&quot;</span>,<span class="at">pch =</span> <span class="dv">20</span>,</span>
<span id="cb18-14"><a href="sínteses-numéricas-descritivas.html#cb18-14" tabindex="-1"></a><span class="at">col=</span><span class="st">&quot;blue&quot;</span>, <span class="at">cex=</span><span class="dv">1</span>, <span class="at">xlab=</span><span class="st">&quot;Alt. dos estudantes (m) adic. de 5cm&quot;</span>, </span>
<span id="cb18-15"><a href="sínteses-numéricas-descritivas.html#cb18-15" tabindex="-1"></a><span class="at">ylab=</span><span class="st">&quot;Quantidades observadas (un)&quot;</span>)</span>
<span id="cb18-16"><a href="sínteses-numéricas-descritivas.html#cb18-16" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">mean</span>(alturas_ad), <span class="at">col=</span><span class="st">&quot;red&quot;</span>) </span>
<span id="cb18-17"><a href="sínteses-numéricas-descritivas.html#cb18-17" tabindex="-1"></a><span class="fu">text</span>(<span class="fu">mean</span>(alturas_ad)<span class="sc">-</span><span class="fl">0.2</span>, <span class="dv">1</span>, <span class="st">&quot;Média=1,74 m&quot;</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">srt=</span><span class="dv">90</span>) </span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-21"></span>
<img src="apostila_files/figure-html/unnamed-chunk-21-1.png" alt="Mudanças na média pela adição (subtração) de uma constante $k=0.05$" width="80%" />
<p class="caption">
Figure 3.3: Mudanças na média pela adição (subtração) de uma constante <span class="math inline">\(k=0.05\)</span>
</p>
</div>
<p><br />
</p>
<ul>
<li>multiplicando-se (ou dividindo-se) cada um dos elementos do conjunto de dados por uma constante arbitrária <span class="math inline">\(k\)</span>, a média aritmética ficará multiplicada (ou dividida) por essa constante <span class="math inline">\(k\)</span></li>
</ul>
<p><br />
</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="sínteses-numéricas-descritivas.html#cb19-1" tabindex="-1"></a>alturas_mult<span class="ot">=</span>alturas<span class="sc">*</span><span class="fl">1.2</span></span>
<span id="cb19-2"><a href="sínteses-numéricas-descritivas.html#cb19-2" tabindex="-1"></a></span>
<span id="cb19-3"><a href="sínteses-numéricas-descritivas.html#cb19-3" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb19-4"><a href="sínteses-numéricas-descritivas.html#cb19-4" tabindex="-1"></a></span>
<span id="cb19-5"><a href="sínteses-numéricas-descritivas.html#cb19-5" tabindex="-1"></a><span class="fu">stripchart</span>(alturas,<span class="at">method =</span> <span class="st">&quot;stack&quot;</span>,  <span class="at">at=</span><span class="fl">0.5</span>, </span>
<span id="cb19-6"><a href="sínteses-numéricas-descritivas.html#cb19-6" tabindex="-1"></a><span class="at">main=</span><span class="st">&quot;&quot;</span>,<span class="at">pch =</span> <span class="dv">20</span>,</span>
<span id="cb19-7"><a href="sínteses-numéricas-descritivas.html#cb19-7" tabindex="-1"></a><span class="at">col=</span><span class="st">&quot;blue&quot;</span>,  <span class="at">xlab=</span><span class="st">&quot;Alturas originais dos estudantes (m)&quot;</span>, </span>
<span id="cb19-8"><a href="sínteses-numéricas-descritivas.html#cb19-8" tabindex="-1"></a><span class="at">ylab=</span><span class="st">&quot;Quantidades observadas (un)&quot;</span>)</span>
<span id="cb19-9"><a href="sínteses-numéricas-descritivas.html#cb19-9" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">mean</span>(alturas), <span class="at">col=</span><span class="st">&quot;red&quot;</span>) </span>
<span id="cb19-10"><a href="sínteses-numéricas-descritivas.html#cb19-10" tabindex="-1"></a><span class="fu">text</span>(<span class="fu">mean</span>(alturas)<span class="sc">-</span><span class="fl">0.1</span>, <span class="dv">1</span>, <span class="st">&quot;Média=1,69 m&quot;</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">srt=</span><span class="dv">90</span>) </span>
<span id="cb19-11"><a href="sínteses-numéricas-descritivas.html#cb19-11" tabindex="-1"></a></span>
<span id="cb19-12"><a href="sínteses-numéricas-descritivas.html#cb19-12" tabindex="-1"></a></span>
<span id="cb19-13"><a href="sínteses-numéricas-descritivas.html#cb19-13" tabindex="-1"></a><span class="fu">stripchart</span>(alturas_mult,<span class="at">method =</span> <span class="st">&quot;stack&quot;</span>,  <span class="at">at=</span><span class="fl">0.5</span>, </span>
<span id="cb19-14"><a href="sínteses-numéricas-descritivas.html#cb19-14" tabindex="-1"></a><span class="at">main=</span><span class="st">&quot;&quot;</span>,<span class="at">pch =</span> <span class="dv">20</span>,</span>
<span id="cb19-15"><a href="sínteses-numéricas-descritivas.html#cb19-15" tabindex="-1"></a><span class="at">col=</span><span class="st">&quot;blue&quot;</span>,  <span class="at">xlab=</span><span class="st">&quot;Alt. dos estudantes (m) mult. por 1,2&quot;</span>, </span>
<span id="cb19-16"><a href="sínteses-numéricas-descritivas.html#cb19-16" tabindex="-1"></a><span class="at">ylab=</span><span class="st">&quot;Quantidades observadas (un)&quot;</span>)</span>
<span id="cb19-17"><a href="sínteses-numéricas-descritivas.html#cb19-17" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">mean</span>(alturas_mult), <span class="at">col=</span><span class="st">&quot;red&quot;</span>) </span>
<span id="cb19-18"><a href="sínteses-numéricas-descritivas.html#cb19-18" tabindex="-1"></a><span class="fu">text</span>(<span class="fu">mean</span>(alturas_mult)<span class="sc">-</span><span class="fl">0.1</span>, <span class="dv">1</span>, <span class="st">&quot;Média= 2,02 m&quot;</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">srt=</span><span class="dv">90</span>) </span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-22"></span>
<img src="apostila_files/figure-html/unnamed-chunk-22-1.png" alt="Mudanças na média pela multiplicação (divisão) de uma constante $k=1.2$" width="80%" />
<p class="caption">
Figure 3.4: Mudanças na média pela multiplicação (divisão) de uma constante <span class="math inline">\(k=1.2\)</span>
</p>
</div>
<p><br />
</p>
<ul>
<li>a soma dos desvios observados entre cada um dos valores assumidos pela variável <span class="math inline">\(X\)</span> e sua média <span class="math inline">\(\stackrel{-}{x}\)</span> é nula;</li>
<li>a soma dos quadrados dos desvios é mínima;</li>
<li>em uma distribuição de frequências, a soma dos produtos dos desvios entre a média o valor médio de cada uma das classes, pelas respectivas frequências é nula; e,</li>
<li>multiplicando-se (ou dividindo-se) todas as frequências de uma distribuição por uma constante arbitrária, a média aritmética não se altera.</li>
</ul>
<p><br />
</p>
<p>Usando os dados das medidas das alturas dos 60 estudantes teremos o seguinte valor para a <strong>média</strong>:</p>
<p><br />
</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="sínteses-numéricas-descritivas.html#cb20-1" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">mean</span>(alturas),<span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 1.69</code></pre>
</div>
<div id="moda" class="section level4 hasAnchor" number="3.3.1.2">
<h4><span class="header-section-number">3.3.1.2</span> Moda<a href="sínteses-numéricas-descritivas.html#moda" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p><br />
</p>
<p>Moda é o valor que ocorre com maior frequência na amostra. Uma amostra pode se apresentar como:</p>
<p><br />
</p>
<ul>
<li>unimodal;</li>
<li>bimodal;</li>
<li>plurimodal; ou,</li>
<li>amodal.</li>
</ul>
<p><br />
</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="sínteses-numéricas-descritivas.html#cb22-1" tabindex="-1"></a>tab_alturas<span class="ot">=</span><span class="fu">table</span>(alturas)</span>
<span id="cb22-2"><a href="sínteses-numéricas-descritivas.html#cb22-2" tabindex="-1"></a></span>
<span id="cb22-3"><a href="sínteses-numéricas-descritivas.html#cb22-3" tabindex="-1"></a>tab_alturas</span></code></pre></div>
<pre><code>## alturas
## 1.41 1.44 1.47 1.54 1.55 1.56 1.57 1.58 1.61 1.62 1.63 1.64 1.65 1.66 1.67 1.68 
##    1    1    1    1    1    3    1    2    1    2    1    2    4    5    4    3 
## 1.69 1.71 1.72 1.73 1.74 1.75 1.76 1.77 1.78 1.79 1.82 1.83 1.84 1.85 1.86 1.93 
##    1    2    2    5    1    1    2    1    2    1    1    2    1    1    1    1 
## 1.95    2 
##    1    1</code></pre>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="sínteses-numéricas-descritivas.html#cb24-1" tabindex="-1"></a><span class="fu">barplot</span>(tab_alturas,</span>
<span id="cb24-2"><a href="sínteses-numéricas-descritivas.html#cb24-2" tabindex="-1"></a>        <span class="at">main=</span><span class="st">&quot;Valores observados da alturas dos estudantes&quot;</span>,</span>
<span id="cb24-3"><a href="sínteses-numéricas-descritivas.html#cb24-3" tabindex="-1"></a>        <span class="at">xlab=</span><span class="st">&quot;Altura (cm)&quot;</span>,</span>
<span id="cb24-4"><a href="sínteses-numéricas-descritivas.html#cb24-4" tabindex="-1"></a>        <span class="at">ylab=</span><span class="st">&quot;Quantidade observada (un)&quot;</span>,</span>
<span id="cb24-5"><a href="sínteses-numéricas-descritivas.html#cb24-5" tabindex="-1"></a>        <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">6</span>),</span>
<span id="cb24-6"><a href="sínteses-numéricas-descritivas.html#cb24-6" tabindex="-1"></a>        <span class="at">col=</span><span class="st">&quot;blue&quot;</span>,</span>
<span id="cb24-7"><a href="sínteses-numéricas-descritivas.html#cb24-7" tabindex="-1"></a>        <span class="at">las=</span><span class="dv">0</span>, </span>
<span id="cb24-8"><a href="sínteses-numéricas-descritivas.html#cb24-8" tabindex="-1"></a>        <span class="at">hor=</span><span class="st">&quot;FALSE&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-24"></span>
<img src="apostila_files/figure-html/unnamed-chunk-24-1.png" alt="Bimodal: 1,66 m e 1,73 m" width="672" />
<p class="caption">
Figure 3.5: Bimodal: 1,66 m e 1,73 m
</p>
</div>
<p><br />
</p>
<p>Usando os dados das medidas das alturas dos 60 estudantes teremos os seguintes valores para a <strong>moda</strong>:</p>
<p><br />
</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="sínteses-numéricas-descritivas.html#cb25-1" tabindex="-1"></a><span class="co"># função em R para extrair a moda:</span></span>
<span id="cb25-2"><a href="sínteses-numéricas-descritivas.html#cb25-2" tabindex="-1"></a></span>
<span id="cb25-3"><a href="sínteses-numéricas-descritivas.html#cb25-3" tabindex="-1"></a>Modes <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb25-4"><a href="sínteses-numéricas-descritivas.html#cb25-4" tabindex="-1"></a>  ux <span class="ot">&lt;-</span> <span class="fu">unique</span>(x)</span>
<span id="cb25-5"><a href="sínteses-numéricas-descritivas.html#cb25-5" tabindex="-1"></a>  tab <span class="ot">&lt;-</span> <span class="fu">tabulate</span>(<span class="fu">match</span>(x, ux))</span>
<span id="cb25-6"><a href="sínteses-numéricas-descritivas.html#cb25-6" tabindex="-1"></a>  ux[tab <span class="sc">==</span> <span class="fu">max</span>(tab)]</span>
<span id="cb25-7"><a href="sínteses-numéricas-descritivas.html#cb25-7" tabindex="-1"></a>}</span>
<span id="cb25-8"><a href="sínteses-numéricas-descritivas.html#cb25-8" tabindex="-1"></a></span>
<span id="cb25-9"><a href="sínteses-numéricas-descritivas.html#cb25-9" tabindex="-1"></a><span class="fu">Modes</span>(alturas)</span></code></pre></div>
<pre><code>## [1] 1.66 1.73</code></pre>
</div>
<div id="mediana" class="section level4 hasAnchor" number="3.3.1.3">
<h4><span class="header-section-number">3.3.1.3</span> Mediana<a href="sínteses-numéricas-descritivas.html#mediana" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p><br />
</p>
<p>Mediana é uma medida quantitativa tal que divide a amostra ordenada dos dados em duas partes com <em>igual quantidade de dados</em> tais que na primeira delas as observações ossuem valores menores que sua medida e na outra parte as observações possuem valores superiores a ela.</p>
<br />

<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-26"></span>
<img src="images3/vetor_posicao.jpg" alt="Entendendo a indexação de dados" width="50%" />
<p class="caption">
Figure 3.6: Entendendo a indexação de dados
</p>
</div>
<p><br />
</p>
<p>Por essa razão, a mediana é uma medida separatriz (de subdivisão) de 50%, equivalente ao <span class="math inline">\(2^{o}\)</span> quartil, ao <span class="math inline">\(5^{o}\)</span> decil e ao <span class="math inline">\(50^{o}\)</span> percentil. Para sua estimação necessitamos saber qual a <strong>posição</strong> que ela ocupa no rol de dados e assim, duas situações podem ocorrer:</p>
<p><br />
</p>
<p>1- se a amostra possui um número <strong>ímpar</strong> (<span class="math inline">\(n\)</span>) de elementos: a medida da mediana igual ao valor do <span class="math inline">\(i-ésimo\)</span> elemento da <strong>amostra ordenada</strong> (a medida da mediana será um valor, de fato, observado) tal que:</p>
<p><span class="math display">\[
Md=x_{i}
\]</span><br />
</p>
<p>com:</p>
<ul>
<li><span class="math inline">\(i=\frac{n+1}{2}\)</span> (<span class="math inline">\(n\)</span> é o número de observações);</li>
</ul>
<p><br />
</p>
<p>2- se a amostra possui um número <strong>par</strong> (<span class="math inline">\(n\)</span>) de elementos: a medida da mediana será a <strong>média aritmética</strong> dos valores dos elementos nas posições imediatamente anterior (<span class="math inline">\(i_{ant}\)</span>) e posterior (<span class="math inline">\(i_{post}\)</span>) à sua posição central virtual (a medida de mediana não será, portanto, um valor observado):</p>
<p><br />
</p>
<p><span class="math display">\[
Md=média(x_{i_{ant}} ; x_{i_{post}})
\]</span></p>
<p><br />
</p>
<p>com:</p>
<p><br />
</p>
<ul>
<li><span class="math inline">\(i_{ant} = \frac{n}{2}\)</span> e <span class="math inline">\(i_{post} =\frac{n}{2}+1\)</span> (<span class="math inline">\(n\)</span> é o número de observações).</li>
</ul>
<p><br />
</p>
<p>Sendo uma <strong>separatriz</strong>, sua posição <span class="math inline">\(L\)</span> pode ser também calculada pela expressão mais geral (para qualquer percentil) que logo mais será apresentada.</p>
<p><br />
</p>
<p>Mediana para dados apresentados na forma de uma <strong>distribuição de frequências</strong>:</p>
<p><br />
</p>
<p><span class="math display">\[
Md = l_{inf} + [ \frac{(\frac{n}{2} -  F_{(i_{md}-1)})}{n_{md}} ]\times \Delta_{i}
\]</span></p>
<p><br />
</p>
<p>onde:</p>
<p><br />
- <span class="math inline">\(l_{inf}\)</span>: limite inferior da <strong>classe mediana</strong>: a classe que contem o elemento de ordem <span class="math inline">\(\frac{n}{2}\)</span>;
- <span class="math inline">\(F_{(i_{md}-1)}\)</span>: é a frequência absoluta acumulada até a <strong>classe anterior à classe mediana</strong>;
- <span class="math inline">\(n_{md}\)</span>: é a frequência absoluta da <strong>classe mediana</strong>; e,
- <span class="math inline">\(\Delta_{i}\)</span>: é o intervalo de cada classe.</p>
<p><br />
</p>
<p>Usando os dados das medidas das alturas dos 60 estudantes teremos o seguinte valor para a <strong>mediana</strong>:</p>
<p><br />
</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="sínteses-numéricas-descritivas.html#cb27-1" tabindex="-1"></a><span class="fu">sort</span>(alturas)</span></code></pre></div>
<pre><code>##  [1] 1.41 1.44 1.47 1.54 1.55 1.56 1.56 1.56 1.57 1.58 1.58 1.61 1.62 1.62 1.63
## [16] 1.64 1.64 1.65 1.65 1.65 1.65 1.66 1.66 1.66 1.66 1.66 1.67 1.67 1.67 1.67
## [31] 1.68 1.68 1.68 1.69 1.71 1.71 1.72 1.72 1.73 1.73 1.73 1.73 1.73 1.74 1.75
## [46] 1.76 1.76 1.77 1.78 1.78 1.79 1.82 1.83 1.83 1.84 1.85 1.86 1.93 1.95 2.00</code></pre>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="sínteses-numéricas-descritivas.html#cb29-1" tabindex="-1"></a><span class="fu">median</span>(alturas)</span></code></pre></div>
<pre><code>## [1] 1.675</code></pre>
<p><br />
</p>
</div>
<div id="diferentes-posições-da-média-moda-e-mediana" class="section level4 hasAnchor" number="3.3.1.4">
<h4><span class="header-section-number">3.3.1.4</span> Diferentes posições da média, moda e mediana<a href="sínteses-numéricas-descritivas.html#diferentes-posições-da-média-moda-e-mediana" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p><br />
</p>
<p>Essas três medidas podem se apresentar com valores em posições alternadas quando as comparamos:<br />
</p>
<ul>
<li>quando a moda=mediana=média temos uma distribuição de frequências razoavelmente <strong>simétrica</strong>;</li>
<li>quando a moda <span class="math inline">\(\leq\)</span> mediana <span class="math inline">\(\leq\)</span> média (há uma quantidade maior de dados com grandes valores, arrastando a média para a direita, para cima) temos uma distribuição de frequências <strong>positivamente assimétrica</strong>, ; e,<br />
</li>
<li>quando a moda <span class="math inline">\(\geq\)</span> mediana <span class="math inline">\(\geq\)</span> média (há uma quantidade maior de dados com pequenos valores, arrastando a média para a esquerda, para baixo) temos uma distribuição de frequências <strong>negativamente assimétrica</strong>.</li>
</ul>
<p><br />
</p>
<p><br />
</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="sínteses-numéricas-descritivas.html#cb31-1" tabindex="-1"></a><span class="fu">barplot</span>(tab_alturas,</span>
<span id="cb31-2"><a href="sínteses-numéricas-descritivas.html#cb31-2" tabindex="-1"></a>        <span class="at">main=</span><span class="st">&quot;Valores observados da alturas dos estudantes&quot;</span>,</span>
<span id="cb31-3"><a href="sínteses-numéricas-descritivas.html#cb31-3" tabindex="-1"></a>        <span class="at">xlab=</span><span class="st">&quot;Altura (cm)&quot;</span>,</span>
<span id="cb31-4"><a href="sínteses-numéricas-descritivas.html#cb31-4" tabindex="-1"></a>        <span class="at">ylab=</span><span class="st">&quot;Quantidade observada (un)&quot;</span>,</span>
<span id="cb31-5"><a href="sínteses-numéricas-descritivas.html#cb31-5" tabindex="-1"></a>        <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">6</span>),</span>
<span id="cb31-6"><a href="sínteses-numéricas-descritivas.html#cb31-6" tabindex="-1"></a>        <span class="at">col=</span><span class="st">&quot;blue&quot;</span>,</span>
<span id="cb31-7"><a href="sínteses-numéricas-descritivas.html#cb31-7" tabindex="-1"></a>        <span class="at">las=</span><span class="dv">0</span>, </span>
<span id="cb31-8"><a href="sínteses-numéricas-descritivas.html#cb31-8" tabindex="-1"></a>        <span class="at">hor=</span><span class="st">&quot;FALSE&quot;</span>)</span>
<span id="cb31-9"><a href="sínteses-numéricas-descritivas.html#cb31-9" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">mean</span>(<span class="fl">19.9</span>, <span class="fl">21.1</span>), <span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span>
<span id="cb31-10"><a href="sínteses-numéricas-descritivas.html#cb31-10" tabindex="-1"></a><span class="fu">text</span>( <span class="fu">mean</span>(<span class="fl">19.9</span>, <span class="fl">21.1</span>)<span class="sc">-</span><span class="fl">0.5</span>, <span class="dv">5</span>, <span class="st">&quot;Média=1,69 m&quot;</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">srt=</span><span class="dv">90</span>)</span>
<span id="cb31-11"><a href="sínteses-numéricas-descritivas.html#cb31-11" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">median</span>(<span class="fl">18.7</span> , <span class="fl">19.9</span>), <span class="at">col=</span><span class="st">&quot;darkgreen&quot;</span>) </span>
<span id="cb31-12"><a href="sínteses-numéricas-descritivas.html#cb31-12" tabindex="-1"></a><span class="fu">text</span>(<span class="fu">median</span>(<span class="fl">18.7</span> , <span class="fl">19.9</span>)<span class="sc">-</span><span class="fl">0.5</span>, <span class="dv">5</span>, <span class="st">&quot;Mediana=1,675 m&quot;</span>, <span class="at">col =</span> <span class="st">&quot;darkgreen&quot;</span>, <span class="at">srt=</span><span class="dv">90</span>)</span>
<span id="cb31-13"><a href="sínteses-numéricas-descritivas.html#cb31-13" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">c</span>(<span class="fl">16.3</span>, <span class="fl">23.5</span>), <span class="at">col=</span><span class="st">&quot;darkgrey&quot;</span>) </span>
<span id="cb31-14"><a href="sínteses-numéricas-descritivas.html#cb31-14" tabindex="-1"></a><span class="fu">text</span>(<span class="fu">c</span>(<span class="fl">16.3-0.5</span>, <span class="fl">23.5-0.5</span>), <span class="dv">5</span>, <span class="fu">c</span>(<span class="st">&quot;Moda=1,66&quot;</span>,<span class="st">&quot;Moda=1,73&quot;</span>), <span class="at">col =</span> <span class="st">&quot;darkgray&quot;</span>, <span class="at">srt=</span><span class="dv">90</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-29"></span>
<img src="apostila_files/figure-html/unnamed-chunk-29-1.png" alt="Valores observados das alturas dos estudantes e as posições da média, moda e mediana" width="80%" />
<p class="caption">
Figure 3.7: Valores observados das alturas dos estudantes e as posições da média, moda e mediana
</p>
</div>
<p><br />
</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-30"></span>
<img src="images3/comp_sinteses.jpg" alt="Quadro comparativo entre as medidas de tendência central (posição)" width="80%" />
<p class="caption">
Figure 3.8: Quadro comparativo entre as medidas de tendência central (posição)
</p>
</div>
</div>
</div>
<div id="medidas-de-dispersão-variabilidade" class="section level3 hasAnchor" number="3.3.2">
<h3><span class="header-section-number">3.3.2</span> Medidas de dispersão (variabilidade)<a href="sínteses-numéricas-descritivas.html#medidas-de-dispersão-variabilidade" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><br />
</p>
<p>O conhecimento de uma medida de tendência central nos provê uma informação útil mas incompleta. As medidas de dispersão nos ajudam a ter uma perspectiva melhor dos dados.</p>
<p><br />
</p>
<ul>
<li>amplitude total dos dados;</li>
<li>desvio padrão (variância): é considerada a mais útil das medidas de dispersão;<br />
</li>
<li>coeficiente de variação; e,</li>
<li>unidades padronizadas.</li>
</ul>
<p><br />
</p>
<p>Diferentes tipos quanto à dimensão (unidade):</p>
<p><br />
</p>
<ul>
<li><strong>medidas absolutas</strong> são aquelas expressas na mesma unidade de medida da variável do fenômeno estudado (<span class="math inline">\(m;kg;\frac{R\$}{mês};\dots\)</span>);<br />
</li>
<li><strong>medidas relativas</strong> são adimiensionais e assim podem ser usadas para se comparar a variabilidade de dois ou mais conjuntos de dados, mesmo quando as variáveis se refiram a diferentes fenômenos ou que sejam expressas, originalmente, em diferentes unidades.</li>
</ul>
<p><br />
</p>
<div id="amplitude-total-dos-dados" class="section level4 hasAnchor" number="3.3.2.1">
<h4><span class="header-section-number">3.3.2.1</span> Amplitude total dos dados<a href="sínteses-numéricas-descritivas.html#amplitude-total-dos-dados" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p><br />
</p>
<p>A amplitude total dos dados é a simples diferença entre o <strong>maior</strong> e o <strong>menor</strong> dos valores observados:</p>
<p><br />
</p>
<p><span class="math display">\[
A=x_{max} - x_{min}
\]</span></p>
<p><br />
</p>
</div>
<div id="estimação-da-variância-e-desvio-padrão" class="section level4 hasAnchor" number="3.3.2.2">
<h4><span class="header-section-number">3.3.2.2</span> Estimação da variância (e desvio padrão)<a href="sínteses-numéricas-descritivas.html#estimação-da-variância-e-desvio-padrão" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p><br />
</p>
<p>Sejam <span class="math inline">\(x_{1}, x_{2}, ..., x_{n}\)</span> os <span class="math inline">\(n\)</span> valores assumidos pela variável <span class="math inline">\(X\)</span>. Dá-se o nome de desvios a contar da média as diferenças entre cada uma das observações e a média: <span class="math inline">\(x_{i} - \stackrel{-}{x}\)</span> com <span class="math inline">\(i=1,2,...,n\)</span>.</p>
<p><br />
</p>
<p>Não é possível considerar a possibilidade de se adotar o valor médio desses desvios pois uma das propriedades da média é que a soma dos desvios em torno de si é nula.</p>
<p><br />
</p>
<p><span class="math display">\[
\stackrel{-}{d} = \frac{\sum _{i=1}^{n}\left(x_{i}-\stackrel{-}{x}\right)}{n}
\]</span>
<span class="math display">\[
\sum _{i=1}^{n}\left(x_{i}-\stackrel{-}{x}\right)=0
\]</span></p>
<p><br />
</p>
<p>constitui-se numa restrição linear dos desvios porque qualquer <span class="math inline">\(n-1\)</span> deles completamente determina o outro. Tampouco se considera a possibilidade de se adotar o valor médio desses desvios em módulo, pelas dificuldades teóricas em problemas de inferência.</p>
<p><br />
</p>
<p><span class="math display">\[
\stackrel{-}{d}  = \frac{\sum _{i=1}^{n}\left|x_{i}-\stackrel{-}{x}\right|}{n}
\]</span></p>
<p><br />
</p>
<p>Uma alternativa é adotar o valor médio do <strong>quadrado</strong> desses desvios.</p>
<p><br />
</p>
<p><span class="math display">\[
S^{2}=\frac{\sum _{i=1}^{n}\left(x_{i}-\stackrel{-}{x}\right)^{2}}{n-1}
\]</span></p>
<p><br />
</p>
<p>ou,</p>
<p><br />
</p>
<p><span class="math display">\[
S^{2}=\frac{1}{(n-1)} \times \left[ \sum _{i=1}^{n} (x_{i}^{2}) - \frac{({\sum _{i=1}^{n}x_{i})}^{2} }{n}\right]
\]</span></p>
<p><br />
</p>
<p>Diz-se que a variância amostral (variância <em>ajustada</em>) possui <span class="math inline">\((n-1)\)</span> graus de liberdade, denotado pela letra grega <span class="math inline">\(\nu\)</span>. A perda de <em>um</em> grau de liberdade deve-se à necessidade de se substituir a média populacional desconhecida (<span class="math inline">\(\mu\)</span>) por sua estimativa amostral (<span class="math inline">\(\stackrel{-}{x}\)</span>), deduzida a partir dos dados coletados.</p>
<p><br />
</p>
<p>Pode-se demonstrar que em razão dessa restrição a melhor estimativa para a variância populacional é obtida dividindo-se a soma dos quadrados dos desvios por <span class="math inline">\((n-1)\)</span>. Assim <span class="math inline">\(S^{2}\)</span> será um estimador não tendencioso para a variância amostral ao ser dividido por <span class="math inline">\((n-1)\)</span>.</p>
<p><br />
</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="sínteses-numéricas-descritivas.html#cb32-1" tabindex="-1"></a>IC.Na <span class="ot">=</span> <span class="cf">function</span> (N, n, mu, sigma) {</span>
<span id="cb32-2"><a href="sínteses-numéricas-descritivas.html#cb32-2" tabindex="-1"></a>  dados<span class="ot">=</span><span class="fu">data.frame</span>()</span>
<span id="cb32-3"><a href="sínteses-numéricas-descritivas.html#cb32-3" tabindex="-1"></a>  <span class="fu">plot</span>(<span class="dv">0</span>, <span class="dv">0</span>, </span>
<span id="cb32-4"><a href="sínteses-numéricas-descritivas.html#cb32-4" tabindex="-1"></a>       <span class="at">type=</span><span class="st">&quot;n&quot;</span>, </span>
<span id="cb32-5"><a href="sínteses-numéricas-descritivas.html#cb32-5" tabindex="-1"></a>       <span class="at">xlim=</span><span class="fu">c</span>(sigma<span class="fl">-0.1</span><span class="sc">*</span>sigma,sigma<span class="fl">+0.1</span><span class="sc">*</span>sigma), </span>
<span id="cb32-6"><a href="sínteses-numéricas-descritivas.html#cb32-6" tabindex="-1"></a>       <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,N), </span>
<span id="cb32-7"><a href="sínteses-numéricas-descritivas.html#cb32-7" tabindex="-1"></a>       <span class="at">bty=</span><span class="st">&quot;l&quot;</span>,</span>
<span id="cb32-8"><a href="sínteses-numéricas-descritivas.html#cb32-8" tabindex="-1"></a>       <span class="at">xlab=</span><span class="st">&quot;Desvio padrão&quot;</span>, </span>
<span id="cb32-9"><a href="sínteses-numéricas-descritivas.html#cb32-9" tabindex="-1"></a>       <span class="at">ylab=</span><span class="st">&quot;Amostras extraídas&quot;</span>, </span>
<span id="cb32-10"><a href="sínteses-numéricas-descritivas.html#cb32-10" tabindex="-1"></a>       <span class="at">main=</span><span class="fu">paste0</span>(<span class="st">&quot;Flutuação dos valores dos desvios padrão </span><span class="sc">\n</span><span class="st">obtidos em &quot;</span>, N,<span class="st">&quot; amostras de tamanho &quot;</span>,n), </span>
<span id="cb32-11"><a href="sínteses-numéricas-descritivas.html#cb32-11" tabindex="-1"></a>       <span class="at">sub=</span><span class="fu">paste0</span>(<span class="st">&quot;A população de origem tem uma distribuição ~ N  (\u03bc:&quot;</span>,mu,<span class="st">&quot; ; \u03c3:&quot;</span>, sigma,<span class="st">&quot;)&quot;</span>))</span>
<span id="cb32-12"><a href="sínteses-numéricas-descritivas.html#cb32-12" tabindex="-1"></a>  <span class="fu">abline</span>(<span class="at">v=</span>sigma, <span class="at">col=</span><span class="st">&#39;darkgreen&#39;</span>, <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb32-13"><a href="sínteses-numéricas-descritivas.html#cb32-13" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>N) {</span>
<span id="cb32-14"><a href="sínteses-numéricas-descritivas.html#cb32-14" tabindex="-1"></a>  x <span class="ot">=</span> <span class="fu">rnorm</span>(n, mu, sigma)</span>
<span id="cb32-15"><a href="sínteses-numéricas-descritivas.html#cb32-15" tabindex="-1"></a>  media <span class="ot">=</span> <span class="fu">mean</span>(x)</span>
<span id="cb32-16"><a href="sínteses-numéricas-descritivas.html#cb32-16" tabindex="-1"></a>  sd <span class="ot">=</span> <span class="fu">sqrt</span>(<span class="fu">sum</span>((x<span class="sc">-</span><span class="fu">mean</span>(x))<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span>(n<span class="dv">-1</span>))</span>
<span id="cb32-17"><a href="sínteses-numéricas-descritivas.html#cb32-17" tabindex="-1"></a>  sd_vies <span class="ot">=</span> <span class="fu">sqrt</span>(<span class="fu">sum</span>((x<span class="sc">-</span><span class="fu">mean</span>(x))<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span>(n))</span>
<span id="cb32-18"><a href="sínteses-numéricas-descritivas.html#cb32-18" tabindex="-1"></a>  temp<span class="ot">=</span><span class="fu">cbind</span>(mu, media, sd, sd_vies)</span>
<span id="cb32-19"><a href="sínteses-numéricas-descritivas.html#cb32-19" tabindex="-1"></a>  dados<span class="ot">=</span><span class="fu">rbind</span>(dados, temp)</span>
<span id="cb32-20"><a href="sínteses-numéricas-descritivas.html#cb32-20" tabindex="-1"></a>  plotx <span class="ot">=</span> <span class="fu">c</span>(sd)</span>
<span id="cb32-21"><a href="sínteses-numéricas-descritivas.html#cb32-21" tabindex="-1"></a>  ploty <span class="ot">=</span> <span class="fu">c</span>(i,i)</span>
<span id="cb32-22"><a href="sínteses-numéricas-descritivas.html#cb32-22" tabindex="-1"></a>  <span class="cf">if</span> ( sd <span class="sc">&lt;</span> sigma) <span class="fu">points</span>(sd, i, <span class="at">col=</span><span class="st">&quot;blue&quot;</span>,<span class="at">cex=</span><span class="dv">1</span>)<span class="sc">+</span><span class="fu">text</span>(<span class="at">y=</span>i<span class="sc">+</span><span class="dv">3</span>,<span class="at">x=</span>sd, <span class="at">labels=</span><span class="fu">round</span>(sd,<span class="dv">3</span>), <span class="at">cex=</span><span class="dv">1</span>, <span class="at">col=</span><span class="st">&#39;blue&#39;</span>)</span>
<span id="cb32-23"><a href="sínteses-numéricas-descritivas.html#cb32-23" tabindex="-1"></a>  <span class="cf">else</span> </span>
<span id="cb32-24"><a href="sínteses-numéricas-descritivas.html#cb32-24" tabindex="-1"></a>    <span class="fu">points</span>(sd, i, <span class="at">col=</span><span class="st">&quot;blue&quot;</span>, <span class="at">cex=</span><span class="dv">1</span>)<span class="sc">+</span><span class="fu">text</span>(<span class="at">y=</span>i<span class="sc">+</span><span class="dv">3</span>,<span class="at">x=</span>sd, <span class="at">labels=</span><span class="fu">round</span>(sd,<span class="dv">3</span>), <span class="at">cex=</span><span class="dv">1</span>, <span class="at">col=</span><span class="st">&#39;blue&#39;</span>) </span>
<span id="cb32-25"><a href="sínteses-numéricas-descritivas.html#cb32-25" tabindex="-1"></a>  plotx <span class="ot">=</span> <span class="fu">c</span>(sd_vies)</span>
<span id="cb32-26"><a href="sínteses-numéricas-descritivas.html#cb32-26" tabindex="-1"></a>  ploty <span class="ot">=</span> <span class="fu">c</span>(i,i)</span>
<span id="cb32-27"><a href="sínteses-numéricas-descritivas.html#cb32-27" tabindex="-1"></a>  <span class="cf">if</span> ( sd_vies <span class="sc">&lt;</span> sigma) <span class="fu">points</span>(sd_vies, i, <span class="at">col=</span><span class="st">&quot;red&quot;</span>,<span class="at">cex=</span><span class="dv">1</span>)<span class="sc">+</span><span class="fu">text</span>(<span class="at">y=</span>i<span class="sc">+</span><span class="dv">3</span>,<span class="at">x=</span>sd_vies, <span class="at">labels=</span><span class="fu">round</span>(sd_vies,<span class="dv">3</span>), <span class="at">cex=</span><span class="dv">1</span>, <span class="at">col=</span><span class="st">&#39;red&#39;</span>)</span>
<span id="cb32-28"><a href="sínteses-numéricas-descritivas.html#cb32-28" tabindex="-1"></a>  <span class="cf">else</span> </span>
<span id="cb32-29"><a href="sínteses-numéricas-descritivas.html#cb32-29" tabindex="-1"></a>    <span class="fu">points</span>(sd_vies, i, <span class="at">col=</span><span class="st">&quot;red&quot;</span>, <span class="at">cex=</span><span class="dv">1</span>)<span class="sc">+</span><span class="fu">text</span>(<span class="at">y=</span>i<span class="sc">+</span><span class="dv">3</span>,<span class="at">x=</span>sd_vies, <span class="at">labels=</span><span class="fu">round</span>(sd_vies,<span class="dv">3</span>), <span class="at">cex=</span><span class="dv">1</span>, <span class="at">col=</span><span class="st">&#39;red&#39;</span>) </span>
<span id="cb32-30"><a href="sínteses-numéricas-descritivas.html#cb32-30" tabindex="-1"></a>} </span>
<span id="cb32-31"><a href="sínteses-numéricas-descritivas.html#cb32-31" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">mean</span>(dados<span class="sc">$</span>sd), <span class="at">col=</span><span class="st">&#39;blue&#39;</span>, <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb32-32"><a href="sínteses-numéricas-descritivas.html#cb32-32" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">mean</span>(dados<span class="sc">$</span>sd_vies), <span class="at">col=</span><span class="st">&#39;red&#39;</span>, <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb32-33"><a href="sínteses-numéricas-descritivas.html#cb32-33" tabindex="-1"></a>}</span></code></pre></div>
<p><br />
</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="sínteses-numéricas-descritivas.html#cb33-1" tabindex="-1"></a><span class="fu">IC.Na</span>(<span class="at">N=</span><span class="dv">100</span>, <span class="at">n=</span><span class="dv">15</span>, <span class="at">mu=</span><span class="dv">170</span>, <span class="at">sigma=</span><span class="dv">7</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-32"></span>
<img src="apostila_files/figure-html/unnamed-chunk-32-1.png" alt="Flutuação dos valores do desvio padrão obtidos pelo estimador não viesado (em azul) e pelo estimador viesado (em vermelho) para diversas amostras extraídas de uma mesma população distribuição $\sim N (\mu; \sigma)$ (em verde o desvio padrão populacional, em azul a média dos desvios padrão amostrais correta e em vermelho a estimada de modo viesado)" width="100%" />
<p class="caption">
Figure 3.9: Flutuação dos valores do desvio padrão obtidos pelo estimador não viesado (em azul) e pelo estimador viesado (em vermelho) para diversas amostras extraídas de uma mesma população distribuição <span class="math inline">\(\sim N (\mu; \sigma)\)</span> (em verde o desvio padrão populacional, em azul a média dos desvios padrão amostrais correta e em vermelho a estimada de modo viesado)
</p>
</div>
<p><br />
</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-33"></span>
<img src="apostila_files/figure-html/unnamed-chunk-33-1.png" alt="A distribuição das variâncias amostrais segue uma curva aproximada pela distribuição Qui-quadrado com (n-1) graus de liberdade" width="80%" />
<p class="caption">
Figure 3.10: A distribuição das variâncias amostrais segue uma curva aproximada pela distribuição Qui-quadrado com (n-1) graus de liberdade
</p>
</div>
<p><br />
</p>
<p>Uma medida de dispersão que apresenta a mesma unidade que a das observações originais é o <strong>desvio-padrão</strong>, definido como a raiz quadrada positiva da variância.</p>
<p><br />
</p>
<p><span class="math display">\[
S= \sqrt{\frac{\sum _{i=1}^{n}\left(x_{i}-\stackrel{-}{x}\right)^{2}}{n-1}}
\]</span></p>
<p><br />
</p>
<p>Tanto a variância quanto o desvio padrão indicam, em média, qual será o erro (desvio) cometido ao tentar substituir cada observação pela medida resumo do conjunto de dados (média).</p>
<p><br />
</p>
<p>Usando os dados das medidas das alturas dos 60 estudantes teremos o seguinte valor para a <strong>variância</strong> (com unidade igual a <span class="math inline">\(m^{2}\)</span>) e o <strong>desvio padrão</strong> (com unidade igual a <span class="math inline">\(m\)</span>):</p>
<p><br />
</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="sínteses-numéricas-descritivas.html#cb34-1" tabindex="-1"></a><span class="co"># Variãncia</span></span>
<span id="cb34-2"><a href="sínteses-numéricas-descritivas.html#cb34-2" tabindex="-1"></a><span class="fu">var</span>(alturas)</span></code></pre></div>
<pre><code>## [1] 0.0130809</code></pre>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="sínteses-numéricas-descritivas.html#cb36-1" tabindex="-1"></a><span class="co"># Desvio padrão</span></span>
<span id="cb36-2"><a href="sínteses-numéricas-descritivas.html#cb36-2" tabindex="-1"></a><span class="fu">sd</span>(alturas) </span></code></pre></div>
<pre><code>## [1] 0.1143718</code></pre>
<p>Propriedades da variância:</p>
<p><br />
</p>
<ul>
<li>somando-se (ou subtraindo-se) cada um dos elementos do conjunto de dados por uma constante arbitrária, a variância (e o desvio padrão) não se altera; e,</li>
<li>multiplicando-se (ou dividindo-se) cada um dos elementos do conjunto de dados por uma constante arbitrária, a variância ficará multiplicada (ou dividida) pelo quadrado dessa constante. O desvio padrão fica multiplicado (ou dividido) por essa constante</li>
</ul>
<p><br />
</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="sínteses-numéricas-descritivas.html#cb38-1" tabindex="-1"></a><span class="co"># Adicionando-se uma constante k=0.05</span></span>
<span id="cb38-2"><a href="sínteses-numéricas-descritivas.html#cb38-2" tabindex="-1"></a>alturas_ad<span class="ot">=</span>alturas<span class="fl">+0.05</span></span>
<span id="cb38-3"><a href="sínteses-numéricas-descritivas.html#cb38-3" tabindex="-1"></a></span>
<span id="cb38-4"><a href="sínteses-numéricas-descritivas.html#cb38-4" tabindex="-1"></a><span class="co"># Variância não se altera</span></span>
<span id="cb38-5"><a href="sínteses-numéricas-descritivas.html#cb38-5" tabindex="-1"></a>var_ad<span class="ot">=</span> <span class="fu">var</span>(alturas_ad)</span>
<span id="cb38-6"><a href="sínteses-numéricas-descritivas.html#cb38-6" tabindex="-1"></a>var_ad</span></code></pre></div>
<pre><code>## [1] 0.0130809</code></pre>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="sínteses-numéricas-descritivas.html#cb40-1" tabindex="-1"></a><span class="co"># Multiplicando-se uma constante k=1.2</span></span>
<span id="cb40-2"><a href="sínteses-numéricas-descritivas.html#cb40-2" tabindex="-1"></a>alturas_mult<span class="ot">=</span>alturas<span class="sc">*</span><span class="fl">1.2</span></span>
<span id="cb40-3"><a href="sínteses-numéricas-descritivas.html#cb40-3" tabindex="-1"></a></span>
<span id="cb40-4"><a href="sínteses-numéricas-descritivas.html#cb40-4" tabindex="-1"></a><span class="co"># Variância fica multiplicada (dividida) pelo quadrado dessa constante)</span></span>
<span id="cb40-5"><a href="sínteses-numéricas-descritivas.html#cb40-5" tabindex="-1"></a><span class="fu">var</span>(alturas_mult)</span></code></pre></div>
<pre><code>## [1] 0.0188365</code></pre>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="sínteses-numéricas-descritivas.html#cb42-1" tabindex="-1"></a><span class="fu">all.equal</span>(<span class="fu">var</span>(alturas_mult), <span class="fu">var</span>(alturas)<span class="sc">*</span>(<span class="fl">1.2</span><span class="sc">^</span><span class="dv">2</span>)) </span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
</div>
<div id="coeficiente-de-variação." class="section level4 hasAnchor" number="3.3.2.3">
<h4><span class="header-section-number">3.3.2.3</span> Coeficiente de variação.<a href="sínteses-numéricas-descritivas.html#coeficiente-de-variação." class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p><br />
</p>
<p>O coeficiente de variação (uma medida adimensional) é dado pela razão do desvio padrão pela média:</p>
<p><br />
</p>
<p><span class="math display">\[
CV(\%)= 100\cdot(\frac{s}{\stackrel{-}{x}})
\]</span></p>
<p><br />
</p>
<p><br />
</p>
<table>
<caption>
Classificação da variabilidade a partir da medida do
Coeficiente de variação
</caption>
<thead>
<tr class="header">
<th style="text-align: center;">
Classificação
</th>
<th style="text-align: center;">
Medida do Coeficiente de variação (CV
%)
</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">
Baixo
</td>
<td style="text-align: center;">
<span class="math inline"><em>C</em><em>V</em> ≤ 10%</span>
</td>
</tr>
<tr class="even">
<td style="text-align: center;">
Médio
</td>
<td style="text-align: center;">
<span class="math inline">10% ≤ <em>C</em><em>V</em> ≤ 20%</span>
</td>
</tr>
<tr class="odd">
<td style="text-align: center;">
Alto
</td>
<td style="text-align: center;">
<span class="math inline">20% ≤ <em>C</em><em>V</em> ≤ 30%</span>
</td>
</tr>
<tr class="even">
<td style="text-align: center;">
Muito alto
</td>
<td style="text-align: center;">
<span class="math inline"><em>C</em><em>V</em> ≥ 30%</span>
</td>
</tr>
</tbody>
</table>
</div>
<div id="padronização-z-scores" class="section level4 hasAnchor" number="3.3.2.4">
<h4><span class="header-section-number">3.3.2.4</span> Padronização (<em>z-scores</em>)<a href="sínteses-numéricas-descritivas.html#padronização-z-scores" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p><br />
</p>
<p>À conversão do valor assumido por uma variável em unidades de desvio padrão acima (ou abaixo) do valor médio de sua distribuição é dado o nome de <em>padronização</em>. Essa métrica permite comparações com outras, procedentes de outros fenômenos.</p>
<p><br />
</p>
<p>Para padronizar (achar o seu <em>z-score</em> Z) o valor de uma variável procede-se segundo a fórmula:</p>
<p><br />
</p>
<p><span class="math display">\[
Z=\frac{x_{i} - \stackrel{-}{x}}{s}
\]</span></p>
<p><br />
O valor <span class="math inline">\(Z\)</span> expressa quantos desvios esse dado está acima (ou abaixo) da média da distribuição.</p>
<p><br />
</p>
<p>Pelo <em>Teorema de Tchebichev</em> pode-se estimar a probabilidade mínima dos dados situados a certa distância de <span class="math inline">\(k\)</span> desvios da média dessa distribuição:</p>
<p><br />
</p>
<p><span class="math display">\[
P(|X-\mu|\ge k\sigma) \leq 1 - \frac{1}{k^{2}}
\]</span></p>
<p><br />
</p>
<p>Assim, se <span class="math inline">\(k=2\)</span> <strong>ao menos</strong> 75% das observações devem estar entre a média e dois desvios padrões acima ou abaixo da média.</p>
<p><br />
</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="sínteses-numéricas-descritivas.html#cb44-1" tabindex="-1"></a>med<span class="ot">=</span><span class="fu">round</span>(<span class="fu">mean</span>(alturas),<span class="dv">2</span>)</span>
<span id="cb44-2"><a href="sínteses-numéricas-descritivas.html#cb44-2" tabindex="-1"></a>desv<span class="ot">=</span> <span class="fu">round</span>(<span class="fu">sd</span>(alturas),<span class="dv">2</span>)</span></code></pre></div>
<p><br />
</p>
<p>No exemplo das alturas dos estudantes temos a média de 1.69 m e um desvio padrão de 0.11 m. Assim, <strong>ao menos</strong> 75% das alturas deverão estar entre 1.47 m e 1.91 m.</p>
<p><br />
</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="sínteses-numéricas-descritivas.html#cb45-1" tabindex="-1"></a><span class="fu">sort</span>(alturas)</span></code></pre></div>
<pre><code>##  [1] 1.41 1.44 1.47 1.54 1.55 1.56 1.56 1.56 1.57 1.58 1.58 1.61 1.62 1.62 1.63
## [16] 1.64 1.64 1.65 1.65 1.65 1.65 1.66 1.66 1.66 1.66 1.66 1.67 1.67 1.67 1.67
## [31] 1.68 1.68 1.68 1.69 1.71 1.71 1.72 1.72 1.73 1.73 1.73 1.73 1.73 1.74 1.75
## [46] 1.76 1.76 1.77 1.78 1.78 1.79 1.82 1.83 1.83 1.84 1.85 1.86 1.93 1.95 2.00</code></pre>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="sínteses-numéricas-descritivas.html#cb47-1" tabindex="-1"></a><span class="co"># Duas observações menores que 1,47m e trẽs maiores que 1,91m.</span></span>
<span id="cb47-2"><a href="sínteses-numéricas-descritivas.html#cb47-2" tabindex="-1"></a><span class="co"># Assim, 54 observações dentro do intervalo, equivalendo a 91,66% do total.</span></span></code></pre></div>
</div>
</div>
<div id="medidas-de-subdivisão-separatrizes" class="section level3 hasAnchor" number="3.3.3">
<h3><span class="header-section-number">3.3.3</span> Medidas de subdivisão (separatrizes)<a href="sínteses-numéricas-descritivas.html#medidas-de-subdivisão-separatrizes" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><br />
</p>
<p>Separatrizes (quantis) são valores que delimitam uma proporção de observações existentes de um conjunto de dados previamente ordenados menores que ele. Os quantis mais expressivos são:</p>
<p><br />
</p>
<ul>
<li>1<span class="math inline">\(^{o}\)</span> Quartil (<span class="math inline">\(q_{0,25}\)</span>): 25% dos dados possuem valores abaixo desse valor e 75% estão acima;</li>
<li>2<span class="math inline">\(^{o}\)</span> Quartil ou mediana (<span class="math inline">\(q_{0,50}\)</span>): 50% dos dados possuem valores abaixo desse valor e 50% estão acima; e,</li>
<li>3<span class="math inline">\(^{o}\)</span> Quartil (<span class="math inline">\(q_{0,75}\)</span>): 75% dos dados possuem valores abaixo desse valor e 25% estão acima.</li>
</ul>
<p><br />
</p>
<p>De modo geral, um <em>quantil</em> de ordem <span class="math inline">\(p\)</span> (ou também <span class="math inline">\(p-quantil\)</span>, indicado por <span class="math inline">\(q_{p}\)</span>) é uma medida onde <span class="math inline">\(p\)</span> é uma proporção qualquer (limitada no intervalo 0 &lt; p &lt; 1), tal que 100<span class="math inline">\(p\)</span>% das observações sejam menores que seu valor <span class="math inline">\(q_{p}\)</span>. Um importante gráfico que mais adiante será exposto em detalhes é o <em>Boxplot</em> que, além da mediana, para sua confecção necessitamos de duas outras separatrizes: o 1<span class="math inline">\(^{o}\)</span> e 3<span class="math inline">\(^{o}\)</span> quartis. \</p>
<p><br />
Há muitos modos de se estabelecer os quantis descritos na literatura. O próprio <a href="https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/quantile">R</a> apresenta 9 modos diferentes:</p>
<p><br />
</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="sínteses-numéricas-descritivas.html#cb48-1" tabindex="-1"></a><span class="fu">quantile</span>(alturas, <span class="at">type=</span><span class="dv">1</span>)</span></code></pre></div>
<pre><code>##   0%  25%  50%  75% 100% 
## 1.41 1.63 1.67 1.75 2.00</code></pre>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="sínteses-numéricas-descritivas.html#cb50-1" tabindex="-1"></a><span class="fu">quantile</span>(alturas, <span class="at">type=</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>##    0%   25%   50%   75%  100% 
## 1.410 1.635 1.675 1.755 2.000</code></pre>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="sínteses-numéricas-descritivas.html#cb52-1" tabindex="-1"></a><span class="fu">quantile</span>(alturas, <span class="at">type=</span><span class="dv">3</span>)</span></code></pre></div>
<pre><code>##   0%  25%  50%  75% 100% 
## 1.41 1.63 1.67 1.75 2.00</code></pre>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="sínteses-numéricas-descritivas.html#cb54-1" tabindex="-1"></a><span class="fu">quantile</span>(alturas, <span class="at">type=</span><span class="dv">4</span>)</span></code></pre></div>
<pre><code>##   0%  25%  50%  75% 100% 
## 1.41 1.63 1.67 1.75 2.00</code></pre>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="sínteses-numéricas-descritivas.html#cb56-1" tabindex="-1"></a><span class="fu">quantile</span>(alturas, <span class="at">type=</span><span class="dv">5</span>)</span></code></pre></div>
<pre><code>##    0%   25%   50%   75%  100% 
## 1.410 1.635 1.675 1.755 2.000</code></pre>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="sínteses-numéricas-descritivas.html#cb58-1" tabindex="-1"></a><span class="fu">quantile</span>(alturas, <span class="at">type=</span><span class="dv">6</span>)</span></code></pre></div>
<pre><code>##     0%    25%    50%    75%   100% 
## 1.4100 1.6325 1.6750 1.7575 2.0000</code></pre>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="sínteses-numéricas-descritivas.html#cb60-1" tabindex="-1"></a><span class="fu">quantile</span>(alturas, <span class="at">type=</span><span class="dv">7</span>)</span></code></pre></div>
<pre><code>##     0%    25%    50%    75%   100% 
## 1.4100 1.6375 1.6750 1.7525 2.0000</code></pre>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="sínteses-numéricas-descritivas.html#cb62-1" tabindex="-1"></a><span class="fu">quantile</span>(alturas, <span class="at">type=</span><span class="dv">8</span>)</span></code></pre></div>
<pre><code>##       0%      25%      50%      75%     100% 
## 1.410000 1.634167 1.675000 1.755833 2.000000</code></pre>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="sínteses-numéricas-descritivas.html#cb64-1" tabindex="-1"></a><span class="fu">quantile</span>(alturas, <span class="at">type=</span><span class="dv">9</span>)</span></code></pre></div>
<pre><code>##       0%      25%      50%      75%     100% 
## 1.410000 1.634375 1.675000 1.755625 2.000000</code></pre>
<p> </p>
<p>Para grandes conjuntos de dados a diferença entre os quantis determinados sob esses diferentes modos será despresível. De modo geral, para se calcular a posição <em>L</em> de um quantil qualquer de ordem <em>p</em> em um rol de dados pode-se usar a seguinte regra empírica:</p>
<p><span class="math display">\[
L_{p}=\frac{p}{100} \times (n+1)
\]</span><br />
</p>
<p>Onde:</p>
<p><br />
</p>
<ul>
<li><em>p</em> é a <strong>ordem</strong> do quantil em % (50% no caso mediana, por exemplo);</li>
<li><em>n</em> é o número de dados do rol; e,</li>
<li><em>L</em> é a <strong>posição</strong> do valor referente ao quantil desejado.</li>
</ul>
<p><br />
</p>
<p><br />
</p>
<p>Assim, para a determinação dos quartis, o valor de <em>p</em> seria:</p>
<p><br />
</p>
<ul>
<li>para o <em>primeiro quartil</em> (<span class="math inline">\(Q_{1}\)</span>): <span class="math inline">\(L_{q_{0,25}}=\frac{25}{100} \times (n+1)\)</span>;</li>
<li>para o <em>segundo quartil</em> (a mediana ou <span class="math inline">\(Q_{2}\)</span>): <span class="math inline">\(L_{q_{0,50}}=\frac{50}{100} \times (n+1)\)</span>; ou,<br />
</li>
<li>para o <em>terceiro quartil</em> (<span class="math inline">\(Q_{3}\)</span>): <span class="math inline">\(L_{q_{0,75}}=\frac{75}{100} \times (n+1)\)</span>.</li>
</ul>
<p><br />
</p>
<p>Novamente podemos nos deparar com <strong>duas situações possíveis</strong> para o valor calculado para a posição <em>L</em>:</p>
<p><br />
</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-40"></span>
<img src="images3/vetor_posicao.jpg" alt="Entendendo a indexação de dados" width="60%" />
<p class="caption">
Figure 3.11: Entendendo a indexação de dados
</p>
</div>
<p><br />
</p>
<ul>
<li>se valor calculado da <strong>posição</strong> L for um inteiro, essa será a posição onde encontraremos o valor referente ao quantil desejado;<br />
</li>
<li>se o valor calculado da <strong>posição L</strong> for fracionário, o valor desse quantil será determinado pela média entre os dois valores dos dados que estão nas <strong>posições</strong> imediatamente anterior e imediatamente posterior à posição <strong>L</strong> calculada.</li>
</ul>
<p><br />
</p>
<p>Juntamente com as observações mínima (<span class="math inline">\(x_{i}\)</span>) e máxima (<span class="math inline">\(x_{n}\)</span>), o 1<span class="math inline">\(^{o}\)</span>, 2<span class="math inline">\(^{o}\)</span> e 3<span class="math inline">\(^{o}\)</span> Quartis são importantes para se ter uma boa idéia da assimetria da distribuição dos dados.</p>
<p><br />
</p>
<p>Para uma distribuição simétrica (ou aproximadamente simétrica) deveremos observar (Distribuição Gaussiana):</p>
<p><br />
</p>
<ul>
<li>a dispersão inferior: <span class="math inline">\(q_{2} - x_{1} \approx x_{n} - q_{2}\)</span> à dispersão superior ;</li>
<li><span class="math inline">\(q_{2} - q_{1} \approx q_{3} - q_{2}\)</span>; e,</li>
<li><span class="math inline">\(q_{1} - x_{1} \approx x_{n} - q_{3}\)</span>.</li>
</ul>
<p><br />
</p>
<p>Para nosso conjunto de dados, segundo a regra empírica apresentada teremos as seguintes posições para determinação dos valores dos quartis:</p>
<p><br />
</p>
<ul>
<li>para o <em>primeiro quartil</em>:</li>
</ul>
<p><span class="math display">\[\begin{align*}
L_{Q_{1}} &amp; =\frac{p}{100} \times (n+1) \\
          &amp; =\frac{25}{100} \times (60+1) \\
          &amp; = 0,25*61 \\
          &amp; = 15,25
\end{align*}\]</span><br />
</p>
<ul>
<li>para o <em>segundo quartil</em>:</li>
</ul>
<p><span class="math display">\[\begin{align*}
L_{Q_{2}} &amp; =\frac{p}{100} \times (n+1) \\
          &amp; =\frac{50}{100} \times (60+1) \\
          &amp; = 0,5*61 \\
          &amp; = 30,5
\end{align*}\]</span></p>
<p><br />
- para o <em>terceiro quartil</em>:</p>
<p><span class="math display">\[\begin{align*}
L_{Q_{3}} &amp; =\frac{p}{100} \times (n+1) \\
          &amp; =\frac{75}{100} \times (60+1) \\
          &amp; = 0,75*61 \\
          &amp; = 45,75
\end{align*}\]</span></p>
<p><br />
</p>
<p>E os quartis serão:</p>
<p><br />
</p>
<p>-<span class="math inline">\(Q_{1}\)</span>=1,635
-<span class="math inline">\(Q_{2}\)</span>=1,675
-<span class="math inline">\(Q_{3}\)</span>=1,755</p>
<p><br />
</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="dados-brutos-em-rol-diagrama-de-ramos-folhas-e-de-dispersão-unidimensional.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="medidas-de-forma-assimetria-curtose.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/03-descritiva.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["apostila.pdf", "apostila.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
